/**
  * \file VecFmncVPreset.cpp
  * vector VecFmncVPreset (implementation)
  * \author Alexander Wirthmueller
  * \date created: 7 Mar 2016
  * \date modified: 7 Mar 2016
  */

#include "VecFmncVPreset.h"

/******************************************************************************
 namespace VecFmncVPreset
 ******************************************************************************/

uint VecFmncVPreset::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "void") return VOID;
	else if (s == "prefmncactlist.run") return PREFMNCACTLIST_RUN;
	else if (s == "prefmncadm") return PREFMNCADM;
	else if (s == "prefmncadrlist.aty") return PREFMNCADRLIST_ATY;
	else if (s == "prefmncadrlist.cry") return PREFMNCADRLIST_CRY;
	else if (s == "prefmncadrlist.cty") return PREFMNCADRLIST_CTY;
	else if (s == "prefmncadrlist.hkt") return PREFMNCADRLIST_HKT;
	else if (s == "prefmncadrlist.hku") return PREFMNCADRLIST_HKU;
	else if (s == "prefmncartlist.org") return PREFMNCARTLIST_ORG;
	else if (s == "prefmncartlist.srf") return PREFMNCARTLIST_SRF;
	else if (s == "prefmncartlist.tol") return PREFMNCARTLIST_TOL;
	else if (s == "prefmncbilapos.x1") return PREFMNCBILAPOS_X1;
	else if (s == "prefmncbilapos.x2") return PREFMNCBILAPOS_X2;
	else if (s == "prefmncbillist.dat") return PREFMNCBILLIST_DAT;
	else if (s == "prefmncbillist.fil") return PREFMNCBILLIST_FIL;
	else if (s == "prefmncbillist.prj") return PREFMNCBILLIST_PRJ;
	else if (s == "prefmncbillist.srf") return PREFMNCBILLIST_SRF;
	else if (s == "prefmncbillist.ste") return PREFMNCBILLIST_STE;
	else if (s == "prefmncfablist.org") return PREFMNCFABLIST_ORG;
	else if (s == "prefmncfillist.fnm") return PREFMNCFILLIST_FNM;
	else if (s == "prefmncfillist.ret") return PREFMNCFILLIST_RET;
	else if (s == "prefmncfillist.reu") return PREFMNCFILLIST_REU;
	else if (s == "prefmncfpjlist.bio") return PREFMNCFPJLIST_BIO;
	else if (s == "prefmncfpjlist.fab") return PREFMNCFPJLIST_FAB;
	else if (s == "prefmncfpjlist.srf") return PREFMNCFPJLIST_SRF;
	else if (s == "prefmncfpjlist.ste") return PREFMNCFPJLIST_STE;
	else if (s == "prefmncfuslist.fab") return PREFMNCFUSLIST_FAB;
	else if (s == "prefmncfuslist.fpj") return PREFMNCFUSLIST_FPJ;
	else if (s == "prefmncfuslist.prs") return PREFMNCFUSLIST_PRS;
	else if (s == "prefmncfuslist.srf") return PREFMNCFUSLIST_SRF;
	else if (s == "prefmncfuslist.ste") return PREFMNCFUSLIST_STE;
	else if (s == "prefmncgrp") return PREFMNCGRP;
	else if (s == "prefmncip") return PREFMNCIP;
	else if (s == "prefmncixacc") return PREFMNCIXACC;
	else if (s == "prefmncixlcl") return PREFMNCIXLCL;
	else if (s == "prefmncixord") return PREFMNCIXORD;
	else if (s == "prefmncixpre") return PREFMNCIXPRE;
	else if (s == "prefmncixuacact") return PREFMNCIXUACACT;
	else if (s == "prefmncixuacadr") return PREFMNCIXUACADR;
	else if (s == "prefmncixuacart") return PREFMNCIXUACART;
	else if (s == "prefmncixuacbil") return PREFMNCIXUACBIL;
	else if (s == "prefmncixuacfab") return PREFMNCIXUACFAB;
	else if (s == "prefmncixuacfil") return PREFMNCIXUACFIL;
	else if (s == "prefmncixuacfpj") return PREFMNCIXUACFPJ;
	else if (s == "prefmncixuacfus") return PREFMNCIXUACFUS;
	else if (s == "prefmncixuacorg") return PREFMNCIXUACORG;
	else if (s == "prefmncixuacpco") return PREFMNCIXUACPCO;
	else if (s == "prefmncixuacprj") return PREFMNCIXUACPRJ;
	else if (s == "prefmncixuacprs") return PREFMNCIXUACPRS;
	else if (s == "prefmncixuacrun") return PREFMNCIXUACRUN;
	else if (s == "prefmncixuacsep") return PREFMNCIXUACSEP;
	else if (s == "prefmncixuacski") return PREFMNCIXUACSKI;
	else if (s == "prefmncixuacsmp") return PREFMNCIXUACSMP;
	else if (s == "prefmncixuacstp") return PREFMNCIXUACSTP;
	else if (s == "prefmncixuactol") return PREFMNCIXUACTOL;
	else if (s == "prefmncixuactty") return PREFMNCIXUACTTY;
	else if (s == "prefmncixuacusg") return PREFMNCIXUACUSG;
	else if (s == "prefmncixuacusr") return PREFMNCIXUACUSR;
	else if (s == "prefmncjrefnotify") return PREFMNCJREFNOTIFY;
	else if (s == "prefmncjrefsess") return PREFMNCJREFSESS;
	else if (s == "prefmncorgadetail.x1") return PREFMNCORGADETAIL_X1;
	else if (s == "prefmncorglist.adr") return PREFMNCORGLIST_ADR;
	else if (s == "prefmncorglist.drv") return PREFMNCORGLIST_DRV;
	else if (s == "prefmncorglist.srf") return PREFMNCORGLIST_SRF;
	else if (s == "prefmncorglist.sup") return PREFMNCORGLIST_SUP;
	else if (s == "prefmncorglist.tit") return PREFMNCORGLIST_TIT;
	else if (s == "prefmncorgmnperson.x1") return PREFMNCORGMNPERSON_X1;
	else if (s == "prefmncown") return PREFMNCOWN;
	else if (s == "prefmncpcolist.dat") return PREFMNCPCOLIST_DAT;
	else if (s == "prefmncpcolist.fil") return PREFMNCPCOLIST_FIL;
	else if (s == "prefmncpcolist.pco") return PREFMNCPCOLIST_PCO;
	else if (s == "prefmncpcolist.spl") return PREFMNCPCOLIST_SPL;
	else if (s == "prefmncpcolist.srf") return PREFMNCPCOLIST_SRF;
	else if (s == "prefmncpcolist.ste") return PREFMNCPCOLIST_STE;
	else if (s == "prefmncprjlist.ste") return PREFMNCPRJLIST_STE;
	else if (s == "prefmncprjlist.tit") return PREFMNCPRJLIST_TIT;
	else if (s == "prefmncprsadetail.x1") return PREFMNCPRSADETAIL_X1;
	else if (s == "prefmncprslist.adr") return PREFMNCPRSLIST_ADR;
	else if (s == "prefmncprslist.grp") return PREFMNCPRSLIST_GRP;
	else if (s == "prefmncprslist.lnm") return PREFMNCPRSLIST_LNM;
	else if (s == "prefmncprslist.org") return PREFMNCPRSLIST_ORG;
	else if (s == "prefmncprslist.own") return PREFMNCPRSLIST_OWN;
	else if (s == "prefmncprsmnorg.x1") return PREFMNCPRSMNORG_X1;
	else if (s == "prefmncrefact") return PREFMNCREFACT;
	else if (s == "prefmncrefadr") return PREFMNCREFADR;
	else if (s == "prefmncrefart") return PREFMNCREFART;
	else if (s == "prefmncrefbil") return PREFMNCREFBIL;
	else if (s == "prefmncreffab") return PREFMNCREFFAB;
	else if (s == "prefmncreffil") return PREFMNCREFFIL;
	else if (s == "prefmncreffpj") return PREFMNCREFFPJ;
	else if (s == "prefmncreffus") return PREFMNCREFFUS;
	else if (s == "prefmncreforg") return PREFMNCREFORG;
	else if (s == "prefmncrefpco") return PREFMNCREFPCO;
	else if (s == "prefmncrefprj") return PREFMNCREFPRJ;
	else if (s == "prefmncrefprs") return PREFMNCREFPRS;
	else if (s == "prefmncrefrun") return PREFMNCREFRUN;
	else if (s == "prefmncrefsel") return PREFMNCREFSEL;
	else if (s == "prefmncrefsep") return PREFMNCREFSEP;
	else if (s == "prefmncrefses") return PREFMNCREFSES;
	else if (s == "prefmncrefski") return PREFMNCREFSKI;
	else if (s == "prefmncrefsmp") return PREFMNCREFSMP;
	else if (s == "prefmncrefste") return PREFMNCREFSTE;
	else if (s == "prefmncrefstp") return PREFMNCREFSTP;
	else if (s == "prefmncreftol") return PREFMNCREFTOL;
	else if (s == "prefmncreftty") return PREFMNCREFTTY;
	else if (s == "prefmncrefusg") return PREFMNCREFUSG;
	else if (s == "prefmncrefusr") return PREFMNCREFUSR;
	else if (s == "prefmncrunlist.prj") return PREFMNCRUNLIST_PRJ;
	else if (s == "prefmncrunlist.ste") return PREFMNCRUNLIST_STE;
	else if (s == "prefmncrunlist.tit") return PREFMNCRUNLIST_TIT;
	else if (s == "prefmncsepapar.x1") return PREFMNCSEPAPAR_X1;
	else if (s == "prefmncsepapar.x2") return PREFMNCSEPAPAR_X2;
	else if (s == "prefmncseplist.act") return PREFMNCSEPLIST_ACT;
	else if (s == "prefmncseplist.rlt") return PREFMNCSEPLIST_RLT;
	else if (s == "prefmncseplist.rlu") return PREFMNCSEPLIST_RLU;
	else if (s == "prefmncseplist.sta") return PREFMNCSEPLIST_STA;
	else if (s == "prefmncseplist.stp") return PREFMNCSEPLIST_STP;
	else if (s == "prefmncsess") return PREFMNCSESS;
	else if (s == "prefmncskilist.art") return PREFMNCSKILIST_ART;
	else if (s == "prefmncskilist.org") return PREFMNCSKILIST_ORG;
	else if (s == "prefmncsmpapar.x1") return PREFMNCSMPAPAR_X1;
	else if (s == "prefmncsmplist.art") return PREFMNCSMPLIST_ART;
	else if (s == "prefmncsmplist.srf") return PREFMNCSMPLIST_SRF;
	else if (s == "prefmncsmplist.ste") return PREFMNCSMPLIST_STE;
	else if (s == "prefmncsmplist.sup") return PREFMNCSMPLIST_SUP;
	else if (s == "prefmncstpapar.x1") return PREFMNCSTPAPAR_X1;
	else if (s == "prefmncstpapar.x2") return PREFMNCSTPAPAR_X2;
	else if (s == "prefmncstplist.act") return PREFMNCSTPLIST_ACT;
	else if (s == "prefmncstplist.rlt") return PREFMNCSTPLIST_RLT;
	else if (s == "prefmncstplist.rlu") return PREFMNCSTPLIST_RLU;
	else if (s == "prefmncstplist.sta") return PREFMNCSTPLIST_STA;
	else if (s == "prefmncstplist.stp") return PREFMNCSTPLIST_STP;
	else if (s == "prefmncsysdate") return PREFMNCSYSDATE;
	else if (s == "prefmncsysstamp") return PREFMNCSYSSTAMP;
	else if (s == "prefmncsystime") return PREFMNCSYSTIME;
	else if (s == "prefmnctolaavl.x1") return PREFMNCTOLAAVL_X1;
	else if (s == "prefmnctolaavl.x2") return PREFMNCTOLAAVL_X2;
	else if (s == "prefmnctolaavl.x3") return PREFMNCTOLAAVL_X3;
	else if (s == "prefmnctolachar.x1") return PREFMNCTOLACHAR_X1;
	else if (s == "prefmnctolares.x1") return PREFMNCTOLARES_X1;
	else if (s == "prefmnctolautil.x1") return PREFMNCTOLAUTIL_X1;
	else if (s == "prefmnctolautil.x2") return PREFMNCTOLAUTIL_X2;
	else if (s == "prefmnctollist.fab") return PREFMNCTOLLIST_FAB;
	else if (s == "prefmnctollist.mnf") return PREFMNCTOLLIST_MNF;
	else if (s == "prefmnctollist.tit") return PREFMNCTOLLIST_TIT;
	else if (s == "prefmncttylist.srf") return PREFMNCTTYLIST_SRF;
	else if (s == "prefmncttylist.sup") return PREFMNCTTYLIST_SUP;
	else if (s == "prefmncttylist.tit") return PREFMNCTTYLIST_TIT;
	else if (s == "prefmncusgaaccess.x1") return PREFMNCUSGAACCESS_X1;
	else if (s == "prefmncusglist.srf") return PREFMNCUSGLIST_SRF;
	else if (s == "prefmncusraaccess.x1") return PREFMNCUSRAACCESS_X1;
	else if (s == "prefmncusrlist.prs") return PREFMNCUSRLIST_PRS;
	else if (s == "prefmncusrlist.srf") return PREFMNCUSRLIST_SRF;
	else if (s == "prefmncusrlist.ste") return PREFMNCUSRLIST_STE;
	else if (s == "prefmncusrlist.usg") return PREFMNCUSRLIST_USG;

	return(0);
};

string VecFmncVPreset::getSref(
			const uint ix
		) {
	if (ix == VOID) return("void");
	else if (ix == PREFMNCACTLIST_RUN) return("PreFmncActList.run");
	else if (ix == PREFMNCADM) return("PreFmncAdm");
	else if (ix == PREFMNCADRLIST_ATY) return("PreFmncAdrList.aty");
	else if (ix == PREFMNCADRLIST_CRY) return("PreFmncAdrList.cry");
	else if (ix == PREFMNCADRLIST_CTY) return("PreFmncAdrList.cty");
	else if (ix == PREFMNCADRLIST_HKT) return("PreFmncAdrList.hkt");
	else if (ix == PREFMNCADRLIST_HKU) return("PreFmncAdrList.hku");
	else if (ix == PREFMNCARTLIST_ORG) return("PreFmncArtList.org");
	else if (ix == PREFMNCARTLIST_SRF) return("PreFmncArtList.srf");
	else if (ix == PREFMNCARTLIST_TOL) return("PreFmncArtList.tol");
	else if (ix == PREFMNCBILAPOS_X1) return("PreFmncBilAPos.x1");
	else if (ix == PREFMNCBILAPOS_X2) return("PreFmncBilAPos.x2");
	else if (ix == PREFMNCBILLIST_DAT) return("PreFmncBilList.dat");
	else if (ix == PREFMNCBILLIST_FIL) return("PreFmncBilList.fil");
	else if (ix == PREFMNCBILLIST_PRJ) return("PreFmncBilList.prj");
	else if (ix == PREFMNCBILLIST_SRF) return("PreFmncBilList.srf");
	else if (ix == PREFMNCBILLIST_STE) return("PreFmncBilList.ste");
	else if (ix == PREFMNCFABLIST_ORG) return("PreFmncFabList.org");
	else if (ix == PREFMNCFILLIST_FNM) return("PreFmncFilList.fnm");
	else if (ix == PREFMNCFILLIST_RET) return("PreFmncFilList.ret");
	else if (ix == PREFMNCFILLIST_REU) return("PreFmncFilList.reu");
	else if (ix == PREFMNCFPJLIST_BIO) return("PreFmncFpjList.bio");
	else if (ix == PREFMNCFPJLIST_FAB) return("PreFmncFpjList.fab");
	else if (ix == PREFMNCFPJLIST_SRF) return("PreFmncFpjList.srf");
	else if (ix == PREFMNCFPJLIST_STE) return("PreFmncFpjList.ste");
	else if (ix == PREFMNCFUSLIST_FAB) return("PreFmncFusList.fab");
	else if (ix == PREFMNCFUSLIST_FPJ) return("PreFmncFusList.fpj");
	else if (ix == PREFMNCFUSLIST_PRS) return("PreFmncFusList.prs");
	else if (ix == PREFMNCFUSLIST_SRF) return("PreFmncFusList.srf");
	else if (ix == PREFMNCFUSLIST_STE) return("PreFmncFusList.ste");
	else if (ix == PREFMNCGRP) return("PreFmncGrp");
	else if (ix == PREFMNCIP) return("PreFmncIp");
	else if (ix == PREFMNCIXACC) return("PreFmncIxAcc");
	else if (ix == PREFMNCIXLCL) return("PreFmncIxLcl");
	else if (ix == PREFMNCIXORD) return("PreFmncIxOrd");
	else if (ix == PREFMNCIXPRE) return("PreFmncIxPre");
	else if (ix == PREFMNCIXUACACT) return("PreFmncIxUacAct");
	else if (ix == PREFMNCIXUACADR) return("PreFmncIxUacAdr");
	else if (ix == PREFMNCIXUACART) return("PreFmncIxUacArt");
	else if (ix == PREFMNCIXUACBIL) return("PreFmncIxUacBil");
	else if (ix == PREFMNCIXUACFAB) return("PreFmncIxUacFab");
	else if (ix == PREFMNCIXUACFIL) return("PreFmncIxUacFil");
	else if (ix == PREFMNCIXUACFPJ) return("PreFmncIxUacFpj");
	else if (ix == PREFMNCIXUACFUS) return("PreFmncIxUacFus");
	else if (ix == PREFMNCIXUACORG) return("PreFmncIxUacOrg");
	else if (ix == PREFMNCIXUACPCO) return("PreFmncIxUacPco");
	else if (ix == PREFMNCIXUACPRJ) return("PreFmncIxUacPrj");
	else if (ix == PREFMNCIXUACPRS) return("PreFmncIxUacPrs");
	else if (ix == PREFMNCIXUACRUN) return("PreFmncIxUacRun");
	else if (ix == PREFMNCIXUACSEP) return("PreFmncIxUacSep");
	else if (ix == PREFMNCIXUACSKI) return("PreFmncIxUacSki");
	else if (ix == PREFMNCIXUACSMP) return("PreFmncIxUacSmp");
	else if (ix == PREFMNCIXUACSTP) return("PreFmncIxUacStp");
	else if (ix == PREFMNCIXUACTOL) return("PreFmncIxUacTol");
	else if (ix == PREFMNCIXUACTTY) return("PreFmncIxUacTty");
	else if (ix == PREFMNCIXUACUSG) return("PreFmncIxUacUsg");
	else if (ix == PREFMNCIXUACUSR) return("PreFmncIxUacUsr");
	else if (ix == PREFMNCJREFNOTIFY) return("PreFmncJrefNotify");
	else if (ix == PREFMNCJREFSESS) return("PreFmncJrefSess");
	else if (ix == PREFMNCORGADETAIL_X1) return("PreFmncOrgADetail.x1");
	else if (ix == PREFMNCORGLIST_ADR) return("PreFmncOrgList.adr");
	else if (ix == PREFMNCORGLIST_DRV) return("PreFmncOrgList.drv");
	else if (ix == PREFMNCORGLIST_SRF) return("PreFmncOrgList.srf");
	else if (ix == PREFMNCORGLIST_SUP) return("PreFmncOrgList.sup");
	else if (ix == PREFMNCORGLIST_TIT) return("PreFmncOrgList.tit");
	else if (ix == PREFMNCORGMNPERSON_X1) return("PreFmncOrgMNPerson.x1");
	else if (ix == PREFMNCOWN) return("PreFmncOwn");
	else if (ix == PREFMNCPCOLIST_DAT) return("PreFmncPcoList.dat");
	else if (ix == PREFMNCPCOLIST_FIL) return("PreFmncPcoList.fil");
	else if (ix == PREFMNCPCOLIST_PCO) return("PreFmncPcoList.pco");
	else if (ix == PREFMNCPCOLIST_SPL) return("PreFmncPcoList.spl");
	else if (ix == PREFMNCPCOLIST_SRF) return("PreFmncPcoList.srf");
	else if (ix == PREFMNCPCOLIST_STE) return("PreFmncPcoList.ste");
	else if (ix == PREFMNCPRJLIST_STE) return("PreFmncPrjList.ste");
	else if (ix == PREFMNCPRJLIST_TIT) return("PreFmncPrjList.tit");
	else if (ix == PREFMNCPRSADETAIL_X1) return("PreFmncPrsADetail.x1");
	else if (ix == PREFMNCPRSLIST_ADR) return("PreFmncPrsList.adr");
	else if (ix == PREFMNCPRSLIST_GRP) return("PreFmncPrsList.grp");
	else if (ix == PREFMNCPRSLIST_LNM) return("PreFmncPrsList.lnm");
	else if (ix == PREFMNCPRSLIST_ORG) return("PreFmncPrsList.org");
	else if (ix == PREFMNCPRSLIST_OWN) return("PreFmncPrsList.own");
	else if (ix == PREFMNCPRSMNORG_X1) return("PreFmncPrsMNOrg.x1");
	else if (ix == PREFMNCREFACT) return("PreFmncRefAct");
	else if (ix == PREFMNCREFADR) return("PreFmncRefAdr");
	else if (ix == PREFMNCREFART) return("PreFmncRefArt");
	else if (ix == PREFMNCREFBIL) return("PreFmncRefBil");
	else if (ix == PREFMNCREFFAB) return("PreFmncRefFab");
	else if (ix == PREFMNCREFFIL) return("PreFmncRefFil");
	else if (ix == PREFMNCREFFPJ) return("PreFmncRefFpj");
	else if (ix == PREFMNCREFFUS) return("PreFmncRefFus");
	else if (ix == PREFMNCREFORG) return("PreFmncRefOrg");
	else if (ix == PREFMNCREFPCO) return("PreFmncRefPco");
	else if (ix == PREFMNCREFPRJ) return("PreFmncRefPrj");
	else if (ix == PREFMNCREFPRS) return("PreFmncRefPrs");
	else if (ix == PREFMNCREFRUN) return("PreFmncRefRun");
	else if (ix == PREFMNCREFSEL) return("PreFmncRefSel");
	else if (ix == PREFMNCREFSEP) return("PreFmncRefSep");
	else if (ix == PREFMNCREFSES) return("PreFmncRefSes");
	else if (ix == PREFMNCREFSKI) return("PreFmncRefSki");
	else if (ix == PREFMNCREFSMP) return("PreFmncRefSmp");
	else if (ix == PREFMNCREFSTE) return("PreFmncRefSte");
	else if (ix == PREFMNCREFSTP) return("PreFmncRefStp");
	else if (ix == PREFMNCREFTOL) return("PreFmncRefTol");
	else if (ix == PREFMNCREFTTY) return("PreFmncRefTty");
	else if (ix == PREFMNCREFUSG) return("PreFmncRefUsg");
	else if (ix == PREFMNCREFUSR) return("PreFmncRefUsr");
	else if (ix == PREFMNCRUNLIST_PRJ) return("PreFmncRunList.prj");
	else if (ix == PREFMNCRUNLIST_STE) return("PreFmncRunList.ste");
	else if (ix == PREFMNCRUNLIST_TIT) return("PreFmncRunList.tit");
	else if (ix == PREFMNCSEPAPAR_X1) return("PreFmncSepAPar.x1");
	else if (ix == PREFMNCSEPAPAR_X2) return("PreFmncSepAPar.x2");
	else if (ix == PREFMNCSEPLIST_ACT) return("PreFmncSepList.act");
	else if (ix == PREFMNCSEPLIST_RLT) return("PreFmncSepList.rlt");
	else if (ix == PREFMNCSEPLIST_RLU) return("PreFmncSepList.rlu");
	else if (ix == PREFMNCSEPLIST_STA) return("PreFmncSepList.sta");
	else if (ix == PREFMNCSEPLIST_STP) return("PreFmncSepList.stp");
	else if (ix == PREFMNCSESS) return("PreFmncSess");
	else if (ix == PREFMNCSKILIST_ART) return("PreFmncSkiList.art");
	else if (ix == PREFMNCSKILIST_ORG) return("PreFmncSkiList.org");
	else if (ix == PREFMNCSMPAPAR_X1) return("PreFmncSmpAPar.x1");
	else if (ix == PREFMNCSMPLIST_ART) return("PreFmncSmpList.art");
	else if (ix == PREFMNCSMPLIST_SRF) return("PreFmncSmpList.srf");
	else if (ix == PREFMNCSMPLIST_STE) return("PreFmncSmpList.ste");
	else if (ix == PREFMNCSMPLIST_SUP) return("PreFmncSmpList.sup");
	else if (ix == PREFMNCSTPAPAR_X1) return("PreFmncStpAPar.x1");
	else if (ix == PREFMNCSTPAPAR_X2) return("PreFmncStpAPar.x2");
	else if (ix == PREFMNCSTPLIST_ACT) return("PreFmncStpList.act");
	else if (ix == PREFMNCSTPLIST_RLT) return("PreFmncStpList.rlt");
	else if (ix == PREFMNCSTPLIST_RLU) return("PreFmncStpList.rlu");
	else if (ix == PREFMNCSTPLIST_STA) return("PreFmncStpList.sta");
	else if (ix == PREFMNCSTPLIST_STP) return("PreFmncStpList.stp");
	else if (ix == PREFMNCSYSDATE) return("PreFmncSysdate");
	else if (ix == PREFMNCSYSSTAMP) return("PreFmncSysstamp");
	else if (ix == PREFMNCSYSTIME) return("PreFmncSystime");
	else if (ix == PREFMNCTOLAAVL_X1) return("PreFmncTolAAvl.x1");
	else if (ix == PREFMNCTOLAAVL_X2) return("PreFmncTolAAvl.x2");
	else if (ix == PREFMNCTOLAAVL_X3) return("PreFmncTolAAvl.x3");
	else if (ix == PREFMNCTOLACHAR_X1) return("PreFmncTolAChar.x1");
	else if (ix == PREFMNCTOLARES_X1) return("PreFmncTolARes.x1");
	else if (ix == PREFMNCTOLAUTIL_X1) return("PreFmncTolAUtil.x1");
	else if (ix == PREFMNCTOLAUTIL_X2) return("PreFmncTolAUtil.x2");
	else if (ix == PREFMNCTOLLIST_FAB) return("PreFmncTolList.fab");
	else if (ix == PREFMNCTOLLIST_MNF) return("PreFmncTolList.mnf");
	else if (ix == PREFMNCTOLLIST_TIT) return("PreFmncTolList.tit");
	else if (ix == PREFMNCTTYLIST_SRF) return("PreFmncTtyList.srf");
	else if (ix == PREFMNCTTYLIST_SUP) return("PreFmncTtyList.sup");
	else if (ix == PREFMNCTTYLIST_TIT) return("PreFmncTtyList.tit");
	else if (ix == PREFMNCUSGAACCESS_X1) return("PreFmncUsgAAccess.x1");
	else if (ix == PREFMNCUSGLIST_SRF) return("PreFmncUsgList.srf");
	else if (ix == PREFMNCUSRAACCESS_X1) return("PreFmncUsrAAccess.x1");
	else if (ix == PREFMNCUSRLIST_PRS) return("PreFmncUsrList.prs");
	else if (ix == PREFMNCUSRLIST_SRF) return("PreFmncUsrList.srf");
	else if (ix == PREFMNCUSRLIST_STE) return("PreFmncUsrList.ste");
	else if (ix == PREFMNCUSRLIST_USG) return("PreFmncUsrList.usg");

	return("");
};

string VecFmncVPreset::getTitle(
			const uint ix
			, const uint ixFmncVLocale
		) {
	if (ixFmncVLocale == 1) {
		if (ix == VOID) return("none");
		else if (ix == PREFMNCREFACT) return("activity");
		else if (ix == PREFMNCREFADR) return("address");
		else if (ix == PREFMNCREFART) return("article");
		else if (ix == PREFMNCREFBIL) return("bill");
		else if (ix == PREFMNCREFFAB) return("fab");
		else if (ix == PREFMNCREFFIL) return("file");
		else if (ix == PREFMNCREFFPJ) return("fab project");
		else if (ix == PREFMNCREFFUS) return("fab user");
		else if (ix == PREFMNCREFORG) return("organization");
		else if (ix == PREFMNCREFPCO) return("purchase order");
		else if (ix == PREFMNCREFPRJ) return("project");
		else if (ix == PREFMNCREFPRS) return("person");
		else if (ix == PREFMNCREFRUN) return("run");
		else if (ix == PREFMNCREFSEP) return("step");
		else if (ix == PREFMNCREFSES) return("session");
		else if (ix == PREFMNCREFSKI) return("stock item");
		else if (ix == PREFMNCREFSMP) return("sample");
		else if (ix == PREFMNCREFSTE) return("step");
		else if (ix == PREFMNCREFSTP) return("recipe");
		else if (ix == PREFMNCREFTOL) return("tool");
		else if (ix == PREFMNCREFTTY) return("tool type");
		else if (ix == PREFMNCREFUSG) return("user group");
		else if (ix == PREFMNCREFUSR) return("user");
		else return(getSref(ix));
	} else if (ixFmncVLocale == 2) {
		if (ix == VOID) return("kein");
		else if (ix == PREFMNCREFACT) return("Aktivit\\u00e4t");
		else if (ix == PREFMNCREFADR) return("Adresse");
		else if (ix == PREFMNCREFART) return("Artikel");
		else if (ix == PREFMNCREFBIL) return("Rechnung");
		else if (ix == PREFMNCREFFAB) return("Reinraum");
		else if (ix == PREFMNCREFFIL) return("Datei");
		else if (ix == PREFMNCREFFPJ) return("Reinraumprojekt");
		else if (ix == PREFMNCREFFUS) return("Reinraumnutzer");
		else if (ix == PREFMNCREFORG) return("Organisation");
		else if (ix == PREFMNCREFPCO) return("Bestellung");
		else if (ix == PREFMNCREFPRJ) return("Projekt");
		else if (ix == PREFMNCREFPRS) return("Person");
		else if (ix == PREFMNCREFRUN) return("Lauf");
		else if (ix == PREFMNCREFSEP) return("Schritt");
		else if (ix == PREFMNCREFSES) return("Sitzung");
		else if (ix == PREFMNCREFSKI) return("Lagerposten");
		else if (ix == PREFMNCREFSMP) return("Sample");
		else if (ix == PREFMNCREFSTE) return("Schritt");
		else if (ix == PREFMNCREFSTP) return("Rezept");
		else if (ix == PREFMNCREFTOL) return("Ger\\u00e4t");
		else if (ix == PREFMNCREFTTY) return("Ger\\u00e4tetyp");
		else if (ix == PREFMNCREFUSG) return("Benutzergruppe");
		else if (ix == PREFMNCREFUSR) return("Benutzer");
		else return(getTitle(ix, 1));
	} else if (ixFmncVLocale == 3) {
		if (ix == VOID) return("aucun");
		else if (ix == PREFMNCREFACT) return("activit\\u00e9");
		else if (ix == PREFMNCREFADR) return("adresse");
		else if (ix == PREFMNCREFART) return("article");
		else if (ix == PREFMNCREFBIL) return("facture");
		else if (ix == PREFMNCREFFAB) return("salle blanche");
		else if (ix == PREFMNCREFFIL) return("fichier");
		else if (ix == PREFMNCREFFPJ) return("projet salle blanche");
		else if (ix == PREFMNCREFFUS) return("utilisateur salle blanche");
		else if (ix == PREFMNCREFORG) return("organisme");
		else if (ix == PREFMNCREFPCO) return("commande");
		else if (ix == PREFMNCREFPRJ) return("projet");
		else if (ix == PREFMNCREFPRS) return("individu");
		else if (ix == PREFMNCREFRUN) return("d\\u00e9roulement");
		else if (ix == PREFMNCREFSEP) return("\\u00e9tape");
		else if (ix == PREFMNCREFSES) return("s\\u00e9ance");
		else if (ix == PREFMNCREFSKI) return("poste du stock");
		else if (ix == PREFMNCREFSMP) return("\\u00e9chantillon");
		else if (ix == PREFMNCREFSTE) return("\\u00e9tape");
		else if (ix == PREFMNCREFSTP) return("recette");
		else if (ix == PREFMNCREFTOL) return("\\u00e9quipement");
		else if (ix == PREFMNCREFTTY) return("type d'\\u00e9quipement");
		else if (ix == PREFMNCREFUSG) return("groupe d'utilisateurs");
		else if (ix == PREFMNCREFUSR) return("utilisateur");
		else return(getTitle(ix, 1));
	};

	return("");
};

