/**
  * \file VecFmncVControl.cpp
  * vector VecFmncVControl (implementation)
  * \author Alexander Wirthmueller
  * \date created: 7 Mar 2016
  * \date modified: 7 Mar 2016
  */

#include "VecFmncVControl.h"

/******************************************************************************
 namespace VecFmncVControl
 ******************************************************************************/

uint VecFmncVControl::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "pnlfmncusglist.tcosrf") return PNLFMNCUSGLIST_TCOSRF;
	else if (s == "pnlfmncusgaaccess.tcocrd") return PNLFMNCUSGAACCESS_TCOCRD;
	else if (s == "pnlfmncusgaaccess.tcouac") return PNLFMNCUSGAACCESS_TCOUAC;
	else if (s == "pnlfmncusgmnuser.tcomref") return PNLFMNCUSGMNUSER_TCOMREF;
	else if (s == "pnlfmncusgmnuser.tcoulv") return PNLFMNCUSGMNUSER_TCOULV;
	else if (s == "pnlfmncusrlist.tcoprs") return PNLFMNCUSRLIST_TCOPRS;
	else if (s == "pnlfmncusrlist.tcosrf") return PNLFMNCUSRLIST_TCOSRF;
	else if (s == "pnlfmncusrlist.tcousg") return PNLFMNCUSRLIST_TCOUSG;
	else if (s == "pnlfmncusrlist.tcoste") return PNLFMNCUSRLIST_TCOSTE;
	else if (s == "pnlfmncusrlist.tcolcl") return PNLFMNCUSRLIST_TCOLCL;
	else if (s == "pnlfmncusrlist.tcoulv") return PNLFMNCUSRLIST_TCOULV;
	else if (s == "pnlfmncusraaccess.tcocrd") return PNLFMNCUSRAACCESS_TCOCRD;
	else if (s == "pnlfmncusraaccess.tcouac") return PNLFMNCUSRAACCESS_TCOUAC;
	else if (s == "pnlfmncusr1nsession.tcoref") return PNLFMNCUSR1NSESSION_TCOREF;
	else if (s == "pnlfmncusrmnusergroup.tcomref") return PNLFMNCUSRMNUSERGROUP_TCOMREF;
	else if (s == "pnlfmncusrmnusergroup.tcoulv") return PNLFMNCUSRMNUSERGROUP_TCOULV;
	else if (s == "pnlfmncorglist.tcosrf") return PNLFMNCORGLIST_TCOSRF;
	else if (s == "pnlfmncorglist.tcotit") return PNLFMNCORGLIST_TCOTIT;
	else if (s == "pnlfmncorglist.tcodrv") return PNLFMNCORGLIST_TCODRV;
	else if (s == "pnlfmncorglist.tcoadr") return PNLFMNCORGLIST_TCOADR;
	else if (s == "pnlfmncorglist.tcosup") return PNLFMNCORGLIST_TCOSUP;
	else if (s == "pnlfmncorglist.tcotel") return PNLFMNCORGLIST_TCOTEL;
	else if (s == "pnlfmncorglist.tcoeml") return PNLFMNCORGLIST_TCOEML;
	else if (s == "pnlfmncorgkstocklcn.tcofix") return PNLFMNCORGKSTOCKLCN_TCOFIX;
	else if (s == "pnlfmncorgkstocklcn.tcosrf") return PNLFMNCORGKSTOCKLCN_TCOSRF;
	else if (s == "pnlfmncorgkstocklcn.tcoavl") return PNLFMNCORGKSTOCKLCN_TCOAVL;
	else if (s == "pnlfmncorgkstocklcn.tcoimp") return PNLFMNCORGKSTOCKLCN_TCOIMP;
	else if (s == "pnlfmncorgkstocklcn.tcotit") return PNLFMNCORGKSTOCKLCN_TCOTIT;
	else if (s == "pnlfmncorgkstocklcn.tcocmt") return PNLFMNCORGKSTOCKLCN_TCOCMT;
	else if (s == "pnlfmncorgadetail.tcotyp") return PNLFMNCORGADETAIL_TCOTYP;
	else if (s == "pnlfmncorgadetail.tcoval") return PNLFMNCORGADETAIL_TCOVAL;
	else if (s == "pnlfmncorgbio1nfabproject.tcoref") return PNLFMNCORGBIO1NFABPROJECT_TCOREF;
	else if (s == "pnlfmncorgmnf1ntool.tcoref") return PNLFMNCORGMNF1NTOOL_TCOREF;
	else if (s == "pnlfmncorgmnf1ntool.tcosprs") return PNLFMNCORGMNF1NTOOL_TCOSPRS;
	else if (s == "pnlfmncorg1narticle.tcoref") return PNLFMNCORG1NARTICLE_TCOREF;
	else if (s == "pnlfmncorgpco1npurchorder.tcoref") return PNLFMNCORGPCO1NPURCHORDER_TCOREF;
	else if (s == "pnlfmncorgspl1npurchorder.tcoref") return PNLFMNCORGSPL1NPURCHORDER_TCOREF;
	else if (s == "pnlfmncorg1nstockitem.tcoref") return PNLFMNCORG1NSTOCKITEM_TCOREF;
	else if (s == "pnlfmncorgsup1norg.tcoref") return PNLFMNCORGSUP1NORG_TCOREF;
	else if (s == "pnlfmncorghk1naddress.tcoref") return PNLFMNCORGHK1NADDRESS_TCOREF;
	else if (s == "pnlfmncorgmnperson.tcomref") return PNLFMNCORGMNPERSON_TCOMREF;
	else if (s == "pnlfmncorgmnperson.tcosta") return PNLFMNCORGMNPERSON_TCOSTA;
	else if (s == "pnlfmncorgmnperson.tcosto") return PNLFMNCORGMNPERSON_TCOSTO;
	else if (s == "pnlfmncorgmnperson.tcofct") return PNLFMNCORGMNPERSON_TCOFCT;
	else if (s == "pnlfmncorgsvcmntool.tcomref") return PNLFMNCORGSVCMNTOOL_TCOMREF;
	else if (s == "pnlfmncorgsvcmntool.tcotprs") return PNLFMNCORGSVCMNTOOL_TCOTPRS;
	else if (s == "pnlfmncorgmnarticle.tcomref") return PNLFMNCORGMNARTICLE_TCOMREF;
	else if (s == "pnlfmncorgmnarticle.tcoitn") return PNLFMNCORGMNARTICLE_TCOITN;
	else if (s == "pnlfmncprslist.tcotit") return PNLFMNCPRSLIST_TCOTIT;
	else if (s == "pnlfmncprslist.tcofnm") return PNLFMNCPRSLIST_TCOFNM;
	else if (s == "pnlfmncprslist.tcolnm") return PNLFMNCPRSLIST_TCOLNM;
	else if (s == "pnlfmncprslist.tcogrp") return PNLFMNCPRSLIST_TCOGRP;
	else if (s == "pnlfmncprslist.tcoown") return PNLFMNCPRSLIST_TCOOWN;
	else if (s == "pnlfmncprslist.tcoorg") return PNLFMNCPRSLIST_TCOORG;
	else if (s == "pnlfmncprslist.tcoadr") return PNLFMNCPRSLIST_TCOADR;
	else if (s == "pnlfmncprslist.tcosex") return PNLFMNCPRSLIST_TCOSEX;
	else if (s == "pnlfmncprslist.tcotel") return PNLFMNCPRSLIST_TCOTEL;
	else if (s == "pnlfmncprslist.tcoeml") return PNLFMNCPRSLIST_TCOEML;
	else if (s == "pnlfmncprsadetail.tcotyp") return PNLFMNCPRSADETAIL_TCOTYP;
	else if (s == "pnlfmncprsadetail.tcoval") return PNLFMNCPRSADETAIL_TCOVAL;
	else if (s == "pnlfmncprshk1naddress.tcoref") return PNLFMNCPRSHK1NADDRESS_TCOREF;
	else if (s == "pnlfmncprsmnrun.tcomref") return PNLFMNCPRSMNRUN_TCOMREF;
	else if (s == "pnlfmncprsmnorg.tcomref") return PNLFMNCPRSMNORG_TCOMREF;
	else if (s == "pnlfmncprsmnorg.tcosta") return PNLFMNCPRSMNORG_TCOSTA;
	else if (s == "pnlfmncprsmnorg.tcosto") return PNLFMNCPRSMNORG_TCOSTO;
	else if (s == "pnlfmncprsmnorg.tcofct") return PNLFMNCPRSMNORG_TCOFCT;
	else if (s == "pnlfmncadrlist.tcoad1") return PNLFMNCADRLIST_TCOAD1;
	else if (s == "pnlfmncadrlist.tcocty") return PNLFMNCADRLIST_TCOCTY;
	else if (s == "pnlfmncadrlist.tcohkt") return PNLFMNCADRLIST_TCOHKT;
	else if (s == "pnlfmncadrlist.tcohku") return PNLFMNCADRLIST_TCOHKU;
	else if (s == "pnlfmncadrlist.tcoaty") return PNLFMNCADRLIST_TCOATY;
	else if (s == "pnlfmncadrlist.tcozip") return PNLFMNCADRLIST_TCOZIP;
	else if (s == "pnlfmncadrlist.tcocry") return PNLFMNCADRLIST_TCOCRY;
	else if (s == "pnlfmncfillist.tcofnm") return PNLFMNCFILLIST_TCOFNM;
	else if (s == "pnlfmncfillist.tcoret") return PNLFMNCFILLIST_TCORET;
	else if (s == "pnlfmncfillist.tcoreu") return PNLFMNCFILLIST_TCOREU;
	else if (s == "pnlfmncfillist.tcocnt") return PNLFMNCFILLIST_TCOCNT;
	else if (s == "pnlfmncfillist.tcomim") return PNLFMNCFILLIST_TCOMIM;
	else if (s == "pnlfmncfillist.tcosiz") return PNLFMNCFILLIST_TCOSIZ;
	else if (s == "pnlfmncfilmnsample.tcomref") return PNLFMNCFILMNSAMPLE_TCOMREF;
	else if (s == "pnlfmncfilmnstep.tcomref") return PNLFMNCFILMNSTEP_TCOMREF;
	else if (s == "pnlfmncfilmnstep.tcotsmp") return PNLFMNCFILMNSTEP_TCOTSMP;
	else if (s == "pnlfmncfilmnstep.tcodir") return PNLFMNCFILMNSTEP_TCODIR;
	else if (s == "pnlfmncstplist.tcotit") return PNLFMNCSTPLIST_TCOTIT;
	else if (s == "pnlfmncstplist.tcoact") return PNLFMNCSTPLIST_TCOACT;
	else if (s == "pnlfmncstplist.tcorlt") return PNLFMNCSTPLIST_TCORLT;
	else if (s == "pnlfmncstplist.tcorlu") return PNLFMNCSTPLIST_TCORLU;
	else if (s == "pnlfmncstplist.tcostp") return PNLFMNCSTPLIST_TCOSTP;
	else if (s == "pnlfmncstplist.tcosta") return PNLFMNCSTPLIST_TCOSTA;
	else if (s == "pnlfmncstpksteppar.tcofix") return PNLFMNCSTPKSTEPPAR_TCOFIX;
	else if (s == "pnlfmncstpksteppar.tcosrf") return PNLFMNCSTPKSTEPPAR_TCOSRF;
	else if (s == "pnlfmncstpksteppar.tcoavl") return PNLFMNCSTPKSTEPPAR_TCOAVL;
	else if (s == "pnlfmncstpksteppar.tcoimp") return PNLFMNCSTPKSTEPPAR_TCOIMP;
	else if (s == "pnlfmncstpksteppar.tcotit") return PNLFMNCSTPKSTEPPAR_TCOTIT;
	else if (s == "pnlfmncstpksteppar.tcocmt") return PNLFMNCSTPKSTEPPAR_TCOCMT;
	else if (s == "pnlfmncstpapar.tcospa") return PNLFMNCSTPAPAR_TCOSPA;
	else if (s == "pnlfmncstpapar.tcoreu") return PNLFMNCSTPAPAR_TCOREU;
	else if (s == "pnlfmncstpapar.tcoval") return PNLFMNCSTPAPAR_TCOVAL;
	else if (s == "pnlfmncstpapar.tcocmt") return PNLFMNCSTPAPAR_TCOCMT;
	else if (s == "pnlfmncstpref1nfile.tcoref") return PNLFMNCSTPREF1NFILE_TCOREF;
	else if (s == "pnlfmncstptpl1nstep.tcoref") return PNLFMNCSTPTPL1NSTEP_TCOREF;
	else if (s == "pnlfmncstpmnfile.tcomref") return PNLFMNCSTPMNFILE_TCOMREF;
	else if (s == "pnlfmncstpmnfile.tcotsmp") return PNLFMNCSTPMNFILE_TCOTSMP;
	else if (s == "pnlfmncstpmnfile.tcodir") return PNLFMNCSTPMNFILE_TCODIR;
	else if (s == "pnlfmncprjlist.tcotit") return PNLFMNCPRJLIST_TCOTIT;
	else if (s == "pnlfmncprjlist.tcoste") return PNLFMNCPRJLIST_TCOSTE;
	else if (s == "pnlfmncprj1nrun.tcoref") return PNLFMNCPRJ1NRUN_TCOREF;
	else if (s == "pnlfmncrunlist.tcotit") return PNLFMNCRUNLIST_TCOTIT;
	else if (s == "pnlfmncrunlist.tcoprj") return PNLFMNCRUNLIST_TCOPRJ;
	else if (s == "pnlfmncrunlist.tcoste") return PNLFMNCRUNLIST_TCOSTE;
	else if (s == "pnlfmncrunrun1nactivity.tcoref") return PNLFMNCRUNRUN1NACTIVITY_TCOREF;
	else if (s == "pnlfmncrunref1nfile.tcoref") return PNLFMNCRUNREF1NFILE_TCOREF;
	else if (s == "pnlfmncrunmnsample.tcomref") return PNLFMNCRUNMNSAMPLE_TCOMREF;
	else if (s == "pnlfmncrunmnperson.tcomref") return PNLFMNCRUNMNPERSON_TCOMREF;
	else if (s == "pnlfmncrunmnfab.tcomref") return PNLFMNCRUNMNFAB_TCOMREF;
	else if (s == "pnlfmncactlist.tcotit") return PNLFMNCACTLIST_TCOTIT;
	else if (s == "pnlfmncactlist.tcorun") return PNLFMNCACTLIST_TCORUN;
	else if (s == "pnlfmncact1nstep.tcoref") return PNLFMNCACT1NSTEP_TCOREF;
	else if (s == "pnlfmncseplist.tcotit") return PNLFMNCSEPLIST_TCOTIT;
	else if (s == "pnlfmncseplist.tcoact") return PNLFMNCSEPLIST_TCOACT;
	else if (s == "pnlfmncseplist.tcorlt") return PNLFMNCSEPLIST_TCORLT;
	else if (s == "pnlfmncseplist.tcorlu") return PNLFMNCSEPLIST_TCORLU;
	else if (s == "pnlfmncseplist.tcostp") return PNLFMNCSEPLIST_TCOSTP;
	else if (s == "pnlfmncseplist.tcosta") return PNLFMNCSEPLIST_TCOSTA;
	else if (s == "pnlfmncsepapar.tcospa") return PNLFMNCSEPAPAR_TCOSPA;
	else if (s == "pnlfmncsepapar.tcoreu") return PNLFMNCSEPAPAR_TCOREU;
	else if (s == "pnlfmncsepapar.tcoval") return PNLFMNCSEPAPAR_TCOVAL;
	else if (s == "pnlfmncsepapar.tcocmt") return PNLFMNCSEPAPAR_TCOCMT;
	else if (s == "pnlfmncsepref1nfile.tcoref") return PNLFMNCSEPREF1NFILE_TCOREF;
	else if (s == "pnlfmncsepmnfile.tcomref") return PNLFMNCSEPMNFILE_TCOMREF;
	else if (s == "pnlfmncsepmnfile.tcotsmp") return PNLFMNCSEPMNFILE_TCOTSMP;
	else if (s == "pnlfmncsepmnfile.tcodir") return PNLFMNCSEPMNFILE_TCODIR;
	else if (s == "pnlfmncsepmnsample.tcomref") return PNLFMNCSEPMNSAMPLE_TCOMREF;
	else if (s == "pnlfmncsmplist.tcosrf") return PNLFMNCSMPLIST_TCOSRF;
	else if (s == "pnlfmncsmplist.tcosup") return PNLFMNCSMPLIST_TCOSUP;
	else if (s == "pnlfmncsmplist.tcoart") return PNLFMNCSMPLIST_TCOART;
	else if (s == "pnlfmncsmplist.tcomat") return PNLFMNCSMPLIST_TCOMAT;
	else if (s == "pnlfmncsmplist.tcoste") return PNLFMNCSMPLIST_TCOSTE;
	else if (s == "pnlfmncsmpapar.tcokey") return PNLFMNCSMPAPAR_TCOKEY;
	else if (s == "pnlfmncsmpapar.tcoval") return PNLFMNCSMPAPAR_TCOVAL;
	else if (s == "pnlfmncsmpsup1nsample.tcoref") return PNLFMNCSMPSUP1NSAMPLE_TCOREF;
	else if (s == "pnlfmncsmpref1nfile.tcoref") return PNLFMNCSMPREF1NFILE_TCOREF;
	else if (s == "pnlfmncsmpmnstep.tcomref") return PNLFMNCSMPMNSTEP_TCOMREF;
	else if (s == "pnlfmncsmpmnfile.tcomref") return PNLFMNCSMPMNFILE_TCOMREF;
	else if (s == "pnlfmncsmpmnrun.tcomref") return PNLFMNCSMPMNRUN_TCOMREF;
	else if (s == "pnlfmncfablist.tcoorg") return PNLFMNCFABLIST_TCOORG;
	else if (s == "pnlfmncfab1nfabproject.tcoref") return PNLFMNCFAB1NFABPROJECT_TCOREF;
	else if (s == "pnlfmncfab1nfabuser.tcoref") return PNLFMNCFAB1NFABUSER_TCOREF;
	else if (s == "pnlfmncfabfab1ntool.tcoref") return PNLFMNCFABFAB1NTOOL_TCOREF;
	else if (s == "pnlfmncfabfab1ntool.tcosprs") return PNLFMNCFABFAB1NTOOL_TCOSPRS;
	else if (s == "pnlfmncfabmnrun.tcomref") return PNLFMNCFABMNRUN_TCOMREF;
	else if (s == "pnlfmncfuslist.tcoprs") return PNLFMNCFUSLIST_TCOPRS;
	else if (s == "pnlfmncfuslist.tcosrf") return PNLFMNCFUSLIST_TCOSRF;
	else if (s == "pnlfmncfuslist.tcofab") return PNLFMNCFUSLIST_TCOFAB;
	else if (s == "pnlfmncfuslist.tcofpj") return PNLFMNCFUSLIST_TCOFPJ;
	else if (s == "pnlfmncfuslist.tcoste") return PNLFMNCFUSLIST_TCOSTE;
	else if (s == "pnlfmncfusmntool.tcomref") return PNLFMNCFUSMNTOOL_TCOMREF;
	else if (s == "pnlfmncfusmntool.tcotrn") return PNLFMNCFUSMNTOOL_TCOTRN;
	else if (s == "pnlfmncfusmntool.tcolvl") return PNLFMNCFUSMNTOOL_TCOLVL;
	else if (s == "pnlfmncfusmnfabproject.tcomref") return PNLFMNCFUSMNFABPROJECT_TCOMREF;
	else if (s == "pnlfmncttylist.tcosrf") return PNLFMNCTTYLIST_TCOSRF;
	else if (s == "pnlfmncttylist.tcotit") return PNLFMNCTTYLIST_TCOTIT;
	else if (s == "pnlfmncttylist.tcosup") return PNLFMNCTTYLIST_TCOSUP;
	else if (s == "pnlfmncttyksteppar.tcofix") return PNLFMNCTTYKSTEPPAR_TCOFIX;
	else if (s == "pnlfmncttyksteppar.tcosrf") return PNLFMNCTTYKSTEPPAR_TCOSRF;
	else if (s == "pnlfmncttyksteppar.tcoavl") return PNLFMNCTTYKSTEPPAR_TCOAVL;
	else if (s == "pnlfmncttyksteppar.tcoimp") return PNLFMNCTTYKSTEPPAR_TCOIMP;
	else if (s == "pnlfmncttyksteppar.tcotit") return PNLFMNCTTYKSTEPPAR_TCOTIT;
	else if (s == "pnlfmncttyksteppar.tcocmt") return PNLFMNCTTYKSTEPPAR_TCOCMT;
	else if (s == "pnlfmncttyktoolchar.tcofix") return PNLFMNCTTYKTOOLCHAR_TCOFIX;
	else if (s == "pnlfmncttyktoolchar.tcosrf") return PNLFMNCTTYKTOOLCHAR_TCOSRF;
	else if (s == "pnlfmncttyktoolchar.tcoavl") return PNLFMNCTTYKTOOLCHAR_TCOAVL;
	else if (s == "pnlfmncttyktoolchar.tcoimp") return PNLFMNCTTYKTOOLCHAR_TCOIMP;
	else if (s == "pnlfmncttyktoolchar.tcotit") return PNLFMNCTTYKTOOLCHAR_TCOTIT;
	else if (s == "pnlfmncttyktoolchar.tcocmt") return PNLFMNCTTYKTOOLCHAR_TCOCMT;
	else if (s == "pnlfmncttysup1ntooltype.tcoref") return PNLFMNCTTYSUP1NTOOLTYPE_TCOREF;
	else if (s == "pnlfmncttyrlv1nstep.tcoref") return PNLFMNCTTYRLV1NSTEP_TCOREF;
	else if (s == "pnlfmncttymntool.tcomref") return PNLFMNCTTYMNTOOL_TCOMREF;
	else if (s == "pnlfmncttymntool.tcotch") return PNLFMNCTTYMNTOOL_TCOTCH;
	else if (s == "pnlfmncttymntool.tcodef") return PNLFMNCTTYMNTOOL_TCODEF;
	else if (s == "pnlfmncttymntool.tcoopt") return PNLFMNCTTYMNTOOL_TCOOPT;
	else if (s == "pnlfmnctollist.tcotit") return PNLFMNCTOLLIST_TCOTIT;
	else if (s == "pnlfmnctollist.tcofab") return PNLFMNCTOLLIST_TCOFAB;
	else if (s == "pnlfmnctollist.tcomnf") return PNLFMNCTOLLIST_TCOMNF;
	else if (s == "pnlfmnctollist.tcoupr") return PNLFMNCTOLLIST_TCOUPR;
	else if (s == "pnlfmnctollist.tcotrn") return PNLFMNCTOLLIST_TCOTRN;
	else if (s == "pnlfmnctolksteppar.tcofix") return PNLFMNCTOLKSTEPPAR_TCOFIX;
	else if (s == "pnlfmnctolksteppar.tcosrf") return PNLFMNCTOLKSTEPPAR_TCOSRF;
	else if (s == "pnlfmnctolksteppar.tcoavl") return PNLFMNCTOLKSTEPPAR_TCOAVL;
	else if (s == "pnlfmnctolksteppar.tcoimp") return PNLFMNCTOLKSTEPPAR_TCOIMP;
	else if (s == "pnlfmnctolksteppar.tcotit") return PNLFMNCTOLKSTEPPAR_TCOTIT;
	else if (s == "pnlfmnctolksteppar.tcocmt") return PNLFMNCTOLKSTEPPAR_TCOCMT;
	else if (s == "pnlfmnctolktoolchar.tcofix") return PNLFMNCTOLKTOOLCHAR_TCOFIX;
	else if (s == "pnlfmnctolktoolchar.tcosrf") return PNLFMNCTOLKTOOLCHAR_TCOSRF;
	else if (s == "pnlfmnctolktoolchar.tcoavl") return PNLFMNCTOLKTOOLCHAR_TCOAVL;
	else if (s == "pnlfmnctolktoolchar.tcoimp") return PNLFMNCTOLKTOOLCHAR_TCOIMP;
	else if (s == "pnlfmnctolktoolchar.tcotit") return PNLFMNCTOLKTOOLCHAR_TCOTIT;
	else if (s == "pnlfmnctolktoolchar.tcocmt") return PNLFMNCTOLKTOOLCHAR_TCOCMT;
	else if (s == "pnlfmnctolaavl.tcodat") return PNLFMNCTOLAAVL_TCODAT;
	else if (s == "pnlfmnctolaavl.tcowdy") return PNLFMNCTOLAAVL_TCOWDY;
	else if (s == "pnlfmnctolaavl.tcosta") return PNLFMNCTOLAAVL_TCOSTA;
	else if (s == "pnlfmnctolaavl.tcosto") return PNLFMNCTOLAAVL_TCOSTO;
	else if (s == "pnlfmnctolaavl.tcoaty") return PNLFMNCTOLAAVL_TCOATY;
	else if (s == "pnlfmnctolachar.tcotch") return PNLFMNCTOLACHAR_TCOTCH;
	else if (s == "pnlfmnctolachar.tcoval") return PNLFMNCTOLACHAR_TCOVAL;
	else if (s == "pnlfmnctolachar.tcocmt") return PNLFMNCTOLACHAR_TCOCMT;
	else if (s == "pnlfmnctolares.tcofus") return PNLFMNCTOLARES_TCOFUS;
	else if (s == "pnlfmnctolares.tcodat") return PNLFMNCTOLARES_TCODAT;
	else if (s == "pnlfmnctolares.tcosta") return PNLFMNCTOLARES_TCOSTA;
	else if (s == "pnlfmnctolares.tcosto") return PNLFMNCTOLARES_TCOSTO;
	else if (s == "pnlfmnctolares.tcorty") return PNLFMNCTOLARES_TCORTY;
	else if (s == "pnlfmnctolares.tcocmt") return PNLFMNCTOLARES_TCOCMT;
	else if (s == "pnlfmnctolautil.tcofpj") return PNLFMNCTOLAUTIL_TCOFPJ;
	else if (s == "pnlfmnctolautil.tcofus") return PNLFMNCTOLAUTIL_TCOFUS;
	else if (s == "pnlfmnctolautil.tcodat") return PNLFMNCTOLAUTIL_TCODAT;
	else if (s == "pnlfmnctolautil.tcosta") return PNLFMNCTOLAUTIL_TCOSTA;
	else if (s == "pnlfmnctolautil.tcosto") return PNLFMNCTOLAUTIL_TCOSTO;
	else if (s == "pnlfmnctolautil.tcoupr") return PNLFMNCTOLAUTIL_TCOUPR;
	else if (s == "pnlfmnctolautil.tcocmt") return PNLFMNCTOLAUTIL_TCOCMT;
	else if (s == "pnlfmnctol1narticle.tcoref") return PNLFMNCTOL1NARTICLE_TCOREF;
	else if (s == "pnlfmnctolrlv1nstep.tcoref") return PNLFMNCTOLRLV1NSTEP_TCOREF;
	else if (s == "pnlfmnctolref1nfile.tcoref") return PNLFMNCTOLREF1NFILE_TCOREF;
	else if (s == "pnlfmnctolmntooltype.tcomref") return PNLFMNCTOLMNTOOLTYPE_TCOMREF;
	else if (s == "pnlfmnctolmntooltype.tcotch") return PNLFMNCTOLMNTOOLTYPE_TCOTCH;
	else if (s == "pnlfmnctolmntooltype.tcodef") return PNLFMNCTOLMNTOOLTYPE_TCODEF;
	else if (s == "pnlfmnctolmntooltype.tcoopt") return PNLFMNCTOLMNTOOLTYPE_TCOOPT;
	else if (s == "pnlfmnctolmnfabuser.tcomref") return PNLFMNCTOLMNFABUSER_TCOMREF;
	else if (s == "pnlfmnctolmnfabuser.tcotrn") return PNLFMNCTOLMNFABUSER_TCOTRN;
	else if (s == "pnlfmnctolmnfabuser.tcolvl") return PNLFMNCTOLMNFABUSER_TCOLVL;
	else if (s == "pnlfmnctolsvcmnorg.tcomref") return PNLFMNCTOLSVCMNORG_TCOMREF;
	else if (s == "pnlfmnctolsvcmnorg.tcotprs") return PNLFMNCTOLSVCMNORG_TCOTPRS;
	else if (s == "pnlfmncfpjlist.tcosrf") return PNLFMNCFPJLIST_TCOSRF;
	else if (s == "pnlfmncfpjlist.tcotit") return PNLFMNCFPJLIST_TCOTIT;
	else if (s == "pnlfmncfpjlist.tcofab") return PNLFMNCFPJLIST_TCOFAB;
	else if (s == "pnlfmncfpjlist.tcobio") return PNLFMNCFPJLIST_TCOBIO;
	else if (s == "pnlfmncfpjlist.tcoste") return PNLFMNCFPJLIST_TCOSTE;
	else if (s == "pnlfmncfpj1nbill.tcoref") return PNLFMNCFPJ1NBILL_TCOREF;
	else if (s == "pnlfmncfpjmnfabuser.tcomref") return PNLFMNCFPJMNFABUSER_TCOMREF;
	else if (s == "pnlfmncbillist.tcosrf") return PNLFMNCBILLIST_TCOSRF;
	else if (s == "pnlfmncbillist.tcodat") return PNLFMNCBILLIST_TCODAT;
	else if (s == "pnlfmncbillist.tcoprj") return PNLFMNCBILLIST_TCOPRJ;
	else if (s == "pnlfmncbillist.tcofil") return PNLFMNCBILLIST_TCOFIL;
	else if (s == "pnlfmncbillist.tcoste") return PNLFMNCBILLIST_TCOSTE;
	else if (s == "pnlfmncbillist.tcopra") return PNLFMNCBILLIST_TCOPRA;
	else if (s == "pnlfmncbillist.tcopro") return PNLFMNCBILLIST_TCOPRO;
	else if (s == "pnlfmncbillist.tcoamt") return PNLFMNCBILLIST_TCOAMT;
	else if (s == "pnlfmncbilapos.tcofus") return PNLFMNCBILAPOS_TCOFUS;
	else if (s == "pnlfmncbilapos.tcotol") return PNLFMNCBILAPOS_TCOTOL;
	else if (s == "pnlfmncbilapos.tcoqty") return PNLFMNCBILAPOS_TCOQTY;
	else if (s == "pnlfmncbilapos.tcoart") return PNLFMNCBILAPOS_TCOART;
	else if (s == "pnlfmncbilapos.tcoupr") return PNLFMNCBILAPOS_TCOUPR;
	else if (s == "pnlfmncbilapos.tcoprc") return PNLFMNCBILAPOS_TCOPRC;
	else if (s == "pnlfmncartlist.tcosrf") return PNLFMNCARTLIST_TCOSRF;
	else if (s == "pnlfmncartlist.tcotit") return PNLFMNCARTLIST_TCOTIT;
	else if (s == "pnlfmncartlist.tcoorg") return PNLFMNCARTLIST_TCOORG;
	else if (s == "pnlfmncartlist.tcotol") return PNLFMNCARTLIST_TCOTOL;
	else if (s == "pnlfmncartlist.tcotyp") return PNLFMNCARTLIST_TCOTYP;
	else if (s == "pnlfmncart1nsample.tcoref") return PNLFMNCART1NSAMPLE_TCOREF;
	else if (s == "pnlfmncart1nstockitem.tcoref") return PNLFMNCART1NSTOCKITEM_TCOREF;
	else if (s == "pnlfmncartref1nfile.tcoref") return PNLFMNCARTREF1NFILE_TCOREF;
	else if (s == "pnlfmncartmnorg.tcomref") return PNLFMNCARTMNORG_TCOMREF;
	else if (s == "pnlfmncartmnorg.tcoitn") return PNLFMNCARTMNORG_TCOITN;
	else if (s == "pnlfmncskilist.tcoorg") return PNLFMNCSKILIST_TCOORG;
	else if (s == "pnlfmncskilist.tcoart") return PNLFMNCSKILIST_TCOART;
	else if (s == "pnlfmncskilist.tcoqty") return PNLFMNCSKILIST_TCOQTY;
	else if (s == "pnlfmncskilist.tcolcn") return PNLFMNCSKILIST_TCOLCN;
	else if (s == "pnlfmncskilist.tcoexd") return PNLFMNCSKILIST_TCOEXD;
	else if (s == "pnlfmncpcolist.tcosrf") return PNLFMNCPCOLIST_TCOSRF;
	else if (s == "pnlfmncpcolist.tcodat") return PNLFMNCPCOLIST_TCODAT;
	else if (s == "pnlfmncpcolist.tcopco") return PNLFMNCPCOLIST_TCOPCO;
	else if (s == "pnlfmncpcolist.tcospl") return PNLFMNCPCOLIST_TCOSPL;
	else if (s == "pnlfmncpcolist.tcofil") return PNLFMNCPCOLIST_TCOFIL;
	else if (s == "pnlfmncpcolist.tcoste") return PNLFMNCPCOLIST_TCOSTE;
	else if (s == "pnlfmncpcolist.tcoamt") return PNLFMNCPCOLIST_TCOAMT;
	else if (s == "pnlfmncpcoapos.tcoqty") return PNLFMNCPCOAPOS_TCOQTY;
	else if (s == "pnlfmncpcoapos.tcoitn") return PNLFMNCPCOAPOS_TCOITN;
	else if (s == "pnlfmncpcoapos.tcoart") return PNLFMNCPCOAPOS_TCOART;
	else if (s == "pnlfmncpcoapos.tcoupr") return PNLFMNCPCOAPOS_TCOUPR;
	else if (s == "pnlfmncpcoapos.tcoprc") return PNLFMNCPCOAPOS_TCOPRC;

	return(0);
};

string VecFmncVControl::getSref(
			const uint ix
		) {
	if (ix == PNLFMNCUSGLIST_TCOSRF) return("PnlFmncUsgList.TcoSrf");
	else if (ix == PNLFMNCUSGAACCESS_TCOCRD) return("PnlFmncUsgAAccess.TcoCrd");
	else if (ix == PNLFMNCUSGAACCESS_TCOUAC) return("PnlFmncUsgAAccess.TcoUac");
	else if (ix == PNLFMNCUSGMNUSER_TCOMREF) return("PnlFmncUsgMNUser.TcoMref");
	else if (ix == PNLFMNCUSGMNUSER_TCOULV) return("PnlFmncUsgMNUser.TcoUlv");
	else if (ix == PNLFMNCUSRLIST_TCOPRS) return("PnlFmncUsrList.TcoPrs");
	else if (ix == PNLFMNCUSRLIST_TCOSRF) return("PnlFmncUsrList.TcoSrf");
	else if (ix == PNLFMNCUSRLIST_TCOUSG) return("PnlFmncUsrList.TcoUsg");
	else if (ix == PNLFMNCUSRLIST_TCOSTE) return("PnlFmncUsrList.TcoSte");
	else if (ix == PNLFMNCUSRLIST_TCOLCL) return("PnlFmncUsrList.TcoLcl");
	else if (ix == PNLFMNCUSRLIST_TCOULV) return("PnlFmncUsrList.TcoUlv");
	else if (ix == PNLFMNCUSRAACCESS_TCOCRD) return("PnlFmncUsrAAccess.TcoCrd");
	else if (ix == PNLFMNCUSRAACCESS_TCOUAC) return("PnlFmncUsrAAccess.TcoUac");
	else if (ix == PNLFMNCUSR1NSESSION_TCOREF) return("PnlFmncUsr1NSession.TcoRef");
	else if (ix == PNLFMNCUSRMNUSERGROUP_TCOMREF) return("PnlFmncUsrMNUsergroup.TcoMref");
	else if (ix == PNLFMNCUSRMNUSERGROUP_TCOULV) return("PnlFmncUsrMNUsergroup.TcoUlv");
	else if (ix == PNLFMNCORGLIST_TCOSRF) return("PnlFmncOrgList.TcoSrf");
	else if (ix == PNLFMNCORGLIST_TCOTIT) return("PnlFmncOrgList.TcoTit");
	else if (ix == PNLFMNCORGLIST_TCODRV) return("PnlFmncOrgList.TcoDrv");
	else if (ix == PNLFMNCORGLIST_TCOADR) return("PnlFmncOrgList.TcoAdr");
	else if (ix == PNLFMNCORGLIST_TCOSUP) return("PnlFmncOrgList.TcoSup");
	else if (ix == PNLFMNCORGLIST_TCOTEL) return("PnlFmncOrgList.TcoTel");
	else if (ix == PNLFMNCORGLIST_TCOEML) return("PnlFmncOrgList.TcoEml");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOFIX) return("PnlFmncOrgKStocklcn.TcoFix");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOSRF) return("PnlFmncOrgKStocklcn.TcoSrf");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOAVL) return("PnlFmncOrgKStocklcn.TcoAvl");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOIMP) return("PnlFmncOrgKStocklcn.TcoImp");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOTIT) return("PnlFmncOrgKStocklcn.TcoTit");
	else if (ix == PNLFMNCORGKSTOCKLCN_TCOCMT) return("PnlFmncOrgKStocklcn.TcoCmt");
	else if (ix == PNLFMNCORGADETAIL_TCOTYP) return("PnlFmncOrgADetail.TcoTyp");
	else if (ix == PNLFMNCORGADETAIL_TCOVAL) return("PnlFmncOrgADetail.TcoVal");
	else if (ix == PNLFMNCORGBIO1NFABPROJECT_TCOREF) return("PnlFmncOrgBio1NFabproject.TcoRef");
	else if (ix == PNLFMNCORGMNF1NTOOL_TCOREF) return("PnlFmncOrgMnf1NTool.TcoRef");
	else if (ix == PNLFMNCORGMNF1NTOOL_TCOSPRS) return("PnlFmncOrgMnf1NTool.TcoSprs");
	else if (ix == PNLFMNCORG1NARTICLE_TCOREF) return("PnlFmncOrg1NArticle.TcoRef");
	else if (ix == PNLFMNCORGPCO1NPURCHORDER_TCOREF) return("PnlFmncOrgPco1NPurchorder.TcoRef");
	else if (ix == PNLFMNCORGSPL1NPURCHORDER_TCOREF) return("PnlFmncOrgSpl1NPurchorder.TcoRef");
	else if (ix == PNLFMNCORG1NSTOCKITEM_TCOREF) return("PnlFmncOrg1NStockitem.TcoRef");
	else if (ix == PNLFMNCORGSUP1NORG_TCOREF) return("PnlFmncOrgSup1NOrg.TcoRef");
	else if (ix == PNLFMNCORGHK1NADDRESS_TCOREF) return("PnlFmncOrgHk1NAddress.TcoRef");
	else if (ix == PNLFMNCORGMNPERSON_TCOMREF) return("PnlFmncOrgMNPerson.TcoMref");
	else if (ix == PNLFMNCORGMNPERSON_TCOSTA) return("PnlFmncOrgMNPerson.TcoSta");
	else if (ix == PNLFMNCORGMNPERSON_TCOSTO) return("PnlFmncOrgMNPerson.TcoSto");
	else if (ix == PNLFMNCORGMNPERSON_TCOFCT) return("PnlFmncOrgMNPerson.TcoFct");
	else if (ix == PNLFMNCORGSVCMNTOOL_TCOMREF) return("PnlFmncOrgSvcMNTool.TcoMref");
	else if (ix == PNLFMNCORGSVCMNTOOL_TCOTPRS) return("PnlFmncOrgSvcMNTool.TcoTprs");
	else if (ix == PNLFMNCORGMNARTICLE_TCOMREF) return("PnlFmncOrgMNArticle.TcoMref");
	else if (ix == PNLFMNCORGMNARTICLE_TCOITN) return("PnlFmncOrgMNArticle.TcoItn");
	else if (ix == PNLFMNCPRSLIST_TCOTIT) return("PnlFmncPrsList.TcoTit");
	else if (ix == PNLFMNCPRSLIST_TCOFNM) return("PnlFmncPrsList.TcoFnm");
	else if (ix == PNLFMNCPRSLIST_TCOLNM) return("PnlFmncPrsList.TcoLnm");
	else if (ix == PNLFMNCPRSLIST_TCOGRP) return("PnlFmncPrsList.TcoGrp");
	else if (ix == PNLFMNCPRSLIST_TCOOWN) return("PnlFmncPrsList.TcoOwn");
	else if (ix == PNLFMNCPRSLIST_TCOORG) return("PnlFmncPrsList.TcoOrg");
	else if (ix == PNLFMNCPRSLIST_TCOADR) return("PnlFmncPrsList.TcoAdr");
	else if (ix == PNLFMNCPRSLIST_TCOSEX) return("PnlFmncPrsList.TcoSex");
	else if (ix == PNLFMNCPRSLIST_TCOTEL) return("PnlFmncPrsList.TcoTel");
	else if (ix == PNLFMNCPRSLIST_TCOEML) return("PnlFmncPrsList.TcoEml");
	else if (ix == PNLFMNCPRSADETAIL_TCOTYP) return("PnlFmncPrsADetail.TcoTyp");
	else if (ix == PNLFMNCPRSADETAIL_TCOVAL) return("PnlFmncPrsADetail.TcoVal");
	else if (ix == PNLFMNCPRSHK1NADDRESS_TCOREF) return("PnlFmncPrsHk1NAddress.TcoRef");
	else if (ix == PNLFMNCPRSMNRUN_TCOMREF) return("PnlFmncPrsMNRun.TcoMref");
	else if (ix == PNLFMNCPRSMNORG_TCOMREF) return("PnlFmncPrsMNOrg.TcoMref");
	else if (ix == PNLFMNCPRSMNORG_TCOSTA) return("PnlFmncPrsMNOrg.TcoSta");
	else if (ix == PNLFMNCPRSMNORG_TCOSTO) return("PnlFmncPrsMNOrg.TcoSto");
	else if (ix == PNLFMNCPRSMNORG_TCOFCT) return("PnlFmncPrsMNOrg.TcoFct");
	else if (ix == PNLFMNCADRLIST_TCOAD1) return("PnlFmncAdrList.TcoAd1");
	else if (ix == PNLFMNCADRLIST_TCOCTY) return("PnlFmncAdrList.TcoCty");
	else if (ix == PNLFMNCADRLIST_TCOHKT) return("PnlFmncAdrList.TcoHkt");
	else if (ix == PNLFMNCADRLIST_TCOHKU) return("PnlFmncAdrList.TcoHku");
	else if (ix == PNLFMNCADRLIST_TCOATY) return("PnlFmncAdrList.TcoAty");
	else if (ix == PNLFMNCADRLIST_TCOZIP) return("PnlFmncAdrList.TcoZip");
	else if (ix == PNLFMNCADRLIST_TCOCRY) return("PnlFmncAdrList.TcoCry");
	else if (ix == PNLFMNCFILLIST_TCOFNM) return("PnlFmncFilList.TcoFnm");
	else if (ix == PNLFMNCFILLIST_TCORET) return("PnlFmncFilList.TcoRet");
	else if (ix == PNLFMNCFILLIST_TCOREU) return("PnlFmncFilList.TcoReu");
	else if (ix == PNLFMNCFILLIST_TCOCNT) return("PnlFmncFilList.TcoCnt");
	else if (ix == PNLFMNCFILLIST_TCOMIM) return("PnlFmncFilList.TcoMim");
	else if (ix == PNLFMNCFILLIST_TCOSIZ) return("PnlFmncFilList.TcoSiz");
	else if (ix == PNLFMNCFILMNSAMPLE_TCOMREF) return("PnlFmncFilMNSample.TcoMref");
	else if (ix == PNLFMNCFILMNSTEP_TCOMREF) return("PnlFmncFilMNStep.TcoMref");
	else if (ix == PNLFMNCFILMNSTEP_TCOTSMP) return("PnlFmncFilMNStep.TcoTsmp");
	else if (ix == PNLFMNCFILMNSTEP_TCODIR) return("PnlFmncFilMNStep.TcoDir");
	else if (ix == PNLFMNCSTPLIST_TCOTIT) return("PnlFmncStpList.TcoTit");
	else if (ix == PNLFMNCSTPLIST_TCOACT) return("PnlFmncStpList.TcoAct");
	else if (ix == PNLFMNCSTPLIST_TCORLT) return("PnlFmncStpList.TcoRlt");
	else if (ix == PNLFMNCSTPLIST_TCORLU) return("PnlFmncStpList.TcoRlu");
	else if (ix == PNLFMNCSTPLIST_TCOSTP) return("PnlFmncStpList.TcoStp");
	else if (ix == PNLFMNCSTPLIST_TCOSTA) return("PnlFmncStpList.TcoSta");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOFIX) return("PnlFmncStpKSteppar.TcoFix");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOSRF) return("PnlFmncStpKSteppar.TcoSrf");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOAVL) return("PnlFmncStpKSteppar.TcoAvl");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOIMP) return("PnlFmncStpKSteppar.TcoImp");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOTIT) return("PnlFmncStpKSteppar.TcoTit");
	else if (ix == PNLFMNCSTPKSTEPPAR_TCOCMT) return("PnlFmncStpKSteppar.TcoCmt");
	else if (ix == PNLFMNCSTPAPAR_TCOSPA) return("PnlFmncStpAPar.TcoSpa");
	else if (ix == PNLFMNCSTPAPAR_TCOREU) return("PnlFmncStpAPar.TcoReu");
	else if (ix == PNLFMNCSTPAPAR_TCOVAL) return("PnlFmncStpAPar.TcoVal");
	else if (ix == PNLFMNCSTPAPAR_TCOCMT) return("PnlFmncStpAPar.TcoCmt");
	else if (ix == PNLFMNCSTPREF1NFILE_TCOREF) return("PnlFmncStpRef1NFile.TcoRef");
	else if (ix == PNLFMNCSTPTPL1NSTEP_TCOREF) return("PnlFmncStpTpl1NStep.TcoRef");
	else if (ix == PNLFMNCSTPMNFILE_TCOMREF) return("PnlFmncStpMNFile.TcoMref");
	else if (ix == PNLFMNCSTPMNFILE_TCOTSMP) return("PnlFmncStpMNFile.TcoTsmp");
	else if (ix == PNLFMNCSTPMNFILE_TCODIR) return("PnlFmncStpMNFile.TcoDir");
	else if (ix == PNLFMNCPRJLIST_TCOTIT) return("PnlFmncPrjList.TcoTit");
	else if (ix == PNLFMNCPRJLIST_TCOSTE) return("PnlFmncPrjList.TcoSte");
	else if (ix == PNLFMNCPRJ1NRUN_TCOREF) return("PnlFmncPrj1NRun.TcoRef");
	else if (ix == PNLFMNCRUNLIST_TCOTIT) return("PnlFmncRunList.TcoTit");
	else if (ix == PNLFMNCRUNLIST_TCOPRJ) return("PnlFmncRunList.TcoPrj");
	else if (ix == PNLFMNCRUNLIST_TCOSTE) return("PnlFmncRunList.TcoSte");
	else if (ix == PNLFMNCRUNRUN1NACTIVITY_TCOREF) return("PnlFmncRunRun1NActivity.TcoRef");
	else if (ix == PNLFMNCRUNREF1NFILE_TCOREF) return("PnlFmncRunRef1NFile.TcoRef");
	else if (ix == PNLFMNCRUNMNSAMPLE_TCOMREF) return("PnlFmncRunMNSample.TcoMref");
	else if (ix == PNLFMNCRUNMNPERSON_TCOMREF) return("PnlFmncRunMNPerson.TcoMref");
	else if (ix == PNLFMNCRUNMNFAB_TCOMREF) return("PnlFmncRunMNFab.TcoMref");
	else if (ix == PNLFMNCACTLIST_TCOTIT) return("PnlFmncActList.TcoTit");
	else if (ix == PNLFMNCACTLIST_TCORUN) return("PnlFmncActList.TcoRun");
	else if (ix == PNLFMNCACT1NSTEP_TCOREF) return("PnlFmncAct1NStep.TcoRef");
	else if (ix == PNLFMNCSEPLIST_TCOTIT) return("PnlFmncSepList.TcoTit");
	else if (ix == PNLFMNCSEPLIST_TCOACT) return("PnlFmncSepList.TcoAct");
	else if (ix == PNLFMNCSEPLIST_TCORLT) return("PnlFmncSepList.TcoRlt");
	else if (ix == PNLFMNCSEPLIST_TCORLU) return("PnlFmncSepList.TcoRlu");
	else if (ix == PNLFMNCSEPLIST_TCOSTP) return("PnlFmncSepList.TcoStp");
	else if (ix == PNLFMNCSEPLIST_TCOSTA) return("PnlFmncSepList.TcoSta");
	else if (ix == PNLFMNCSEPAPAR_TCOSPA) return("PnlFmncSepAPar.TcoSpa");
	else if (ix == PNLFMNCSEPAPAR_TCOREU) return("PnlFmncSepAPar.TcoReu");
	else if (ix == PNLFMNCSEPAPAR_TCOVAL) return("PnlFmncSepAPar.TcoVal");
	else if (ix == PNLFMNCSEPAPAR_TCOCMT) return("PnlFmncSepAPar.TcoCmt");
	else if (ix == PNLFMNCSEPREF1NFILE_TCOREF) return("PnlFmncSepRef1NFile.TcoRef");
	else if (ix == PNLFMNCSEPMNFILE_TCOMREF) return("PnlFmncSepMNFile.TcoMref");
	else if (ix == PNLFMNCSEPMNFILE_TCOTSMP) return("PnlFmncSepMNFile.TcoTsmp");
	else if (ix == PNLFMNCSEPMNFILE_TCODIR) return("PnlFmncSepMNFile.TcoDir");
	else if (ix == PNLFMNCSEPMNSAMPLE_TCOMREF) return("PnlFmncSepMNSample.TcoMref");
	else if (ix == PNLFMNCSMPLIST_TCOSRF) return("PnlFmncSmpList.TcoSrf");
	else if (ix == PNLFMNCSMPLIST_TCOSUP) return("PnlFmncSmpList.TcoSup");
	else if (ix == PNLFMNCSMPLIST_TCOART) return("PnlFmncSmpList.TcoArt");
	else if (ix == PNLFMNCSMPLIST_TCOMAT) return("PnlFmncSmpList.TcoMat");
	else if (ix == PNLFMNCSMPLIST_TCOSTE) return("PnlFmncSmpList.TcoSte");
	else if (ix == PNLFMNCSMPAPAR_TCOKEY) return("PnlFmncSmpAPar.TcoKey");
	else if (ix == PNLFMNCSMPAPAR_TCOVAL) return("PnlFmncSmpAPar.TcoVal");
	else if (ix == PNLFMNCSMPSUP1NSAMPLE_TCOREF) return("PnlFmncSmpSup1NSample.TcoRef");
	else if (ix == PNLFMNCSMPREF1NFILE_TCOREF) return("PnlFmncSmpRef1NFile.TcoRef");
	else if (ix == PNLFMNCSMPMNSTEP_TCOMREF) return("PnlFmncSmpMNStep.TcoMref");
	else if (ix == PNLFMNCSMPMNFILE_TCOMREF) return("PnlFmncSmpMNFile.TcoMref");
	else if (ix == PNLFMNCSMPMNRUN_TCOMREF) return("PnlFmncSmpMNRun.TcoMref");
	else if (ix == PNLFMNCFABLIST_TCOORG) return("PnlFmncFabList.TcoOrg");
	else if (ix == PNLFMNCFAB1NFABPROJECT_TCOREF) return("PnlFmncFab1NFabproject.TcoRef");
	else if (ix == PNLFMNCFAB1NFABUSER_TCOREF) return("PnlFmncFab1NFabuser.TcoRef");
	else if (ix == PNLFMNCFABFAB1NTOOL_TCOREF) return("PnlFmncFabFab1NTool.TcoRef");
	else if (ix == PNLFMNCFABFAB1NTOOL_TCOSPRS) return("PnlFmncFabFab1NTool.TcoSprs");
	else if (ix == PNLFMNCFABMNRUN_TCOMREF) return("PnlFmncFabMNRun.TcoMref");
	else if (ix == PNLFMNCFUSLIST_TCOPRS) return("PnlFmncFusList.TcoPrs");
	else if (ix == PNLFMNCFUSLIST_TCOSRF) return("PnlFmncFusList.TcoSrf");
	else if (ix == PNLFMNCFUSLIST_TCOFAB) return("PnlFmncFusList.TcoFab");
	else if (ix == PNLFMNCFUSLIST_TCOFPJ) return("PnlFmncFusList.TcoFpj");
	else if (ix == PNLFMNCFUSLIST_TCOSTE) return("PnlFmncFusList.TcoSte");
	else if (ix == PNLFMNCFUSMNTOOL_TCOMREF) return("PnlFmncFusMNTool.TcoMref");
	else if (ix == PNLFMNCFUSMNTOOL_TCOTRN) return("PnlFmncFusMNTool.TcoTrn");
	else if (ix == PNLFMNCFUSMNTOOL_TCOLVL) return("PnlFmncFusMNTool.TcoLvl");
	else if (ix == PNLFMNCFUSMNFABPROJECT_TCOMREF) return("PnlFmncFusMNFabproject.TcoMref");
	else if (ix == PNLFMNCTTYLIST_TCOSRF) return("PnlFmncTtyList.TcoSrf");
	else if (ix == PNLFMNCTTYLIST_TCOTIT) return("PnlFmncTtyList.TcoTit");
	else if (ix == PNLFMNCTTYLIST_TCOSUP) return("PnlFmncTtyList.TcoSup");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOFIX) return("PnlFmncTtyKSteppar.TcoFix");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOSRF) return("PnlFmncTtyKSteppar.TcoSrf");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOAVL) return("PnlFmncTtyKSteppar.TcoAvl");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOIMP) return("PnlFmncTtyKSteppar.TcoImp");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOTIT) return("PnlFmncTtyKSteppar.TcoTit");
	else if (ix == PNLFMNCTTYKSTEPPAR_TCOCMT) return("PnlFmncTtyKSteppar.TcoCmt");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOFIX) return("PnlFmncTtyKToolchar.TcoFix");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOSRF) return("PnlFmncTtyKToolchar.TcoSrf");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOAVL) return("PnlFmncTtyKToolchar.TcoAvl");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOIMP) return("PnlFmncTtyKToolchar.TcoImp");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOTIT) return("PnlFmncTtyKToolchar.TcoTit");
	else if (ix == PNLFMNCTTYKTOOLCHAR_TCOCMT) return("PnlFmncTtyKToolchar.TcoCmt");
	else if (ix == PNLFMNCTTYSUP1NTOOLTYPE_TCOREF) return("PnlFmncTtySup1NTooltype.TcoRef");
	else if (ix == PNLFMNCTTYRLV1NSTEP_TCOREF) return("PnlFmncTtyRlv1NStep.TcoRef");
	else if (ix == PNLFMNCTTYMNTOOL_TCOMREF) return("PnlFmncTtyMNTool.TcoMref");
	else if (ix == PNLFMNCTTYMNTOOL_TCOTCH) return("PnlFmncTtyMNTool.TcoTch");
	else if (ix == PNLFMNCTTYMNTOOL_TCODEF) return("PnlFmncTtyMNTool.TcoDef");
	else if (ix == PNLFMNCTTYMNTOOL_TCOOPT) return("PnlFmncTtyMNTool.TcoOpt");
	else if (ix == PNLFMNCTOLLIST_TCOTIT) return("PnlFmncTolList.TcoTit");
	else if (ix == PNLFMNCTOLLIST_TCOFAB) return("PnlFmncTolList.TcoFab");
	else if (ix == PNLFMNCTOLLIST_TCOMNF) return("PnlFmncTolList.TcoMnf");
	else if (ix == PNLFMNCTOLLIST_TCOUPR) return("PnlFmncTolList.TcoUpr");
	else if (ix == PNLFMNCTOLLIST_TCOTRN) return("PnlFmncTolList.TcoTrn");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOFIX) return("PnlFmncTolKSteppar.TcoFix");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOSRF) return("PnlFmncTolKSteppar.TcoSrf");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOAVL) return("PnlFmncTolKSteppar.TcoAvl");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOIMP) return("PnlFmncTolKSteppar.TcoImp");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOTIT) return("PnlFmncTolKSteppar.TcoTit");
	else if (ix == PNLFMNCTOLKSTEPPAR_TCOCMT) return("PnlFmncTolKSteppar.TcoCmt");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOFIX) return("PnlFmncTolKToolchar.TcoFix");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOSRF) return("PnlFmncTolKToolchar.TcoSrf");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOAVL) return("PnlFmncTolKToolchar.TcoAvl");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOIMP) return("PnlFmncTolKToolchar.TcoImp");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOTIT) return("PnlFmncTolKToolchar.TcoTit");
	else if (ix == PNLFMNCTOLKTOOLCHAR_TCOCMT) return("PnlFmncTolKToolchar.TcoCmt");
	else if (ix == PNLFMNCTOLAAVL_TCODAT) return("PnlFmncTolAAvl.TcoDat");
	else if (ix == PNLFMNCTOLAAVL_TCOWDY) return("PnlFmncTolAAvl.TcoWdy");
	else if (ix == PNLFMNCTOLAAVL_TCOSTA) return("PnlFmncTolAAvl.TcoSta");
	else if (ix == PNLFMNCTOLAAVL_TCOSTO) return("PnlFmncTolAAvl.TcoSto");
	else if (ix == PNLFMNCTOLAAVL_TCOATY) return("PnlFmncTolAAvl.TcoAty");
	else if (ix == PNLFMNCTOLACHAR_TCOTCH) return("PnlFmncTolAChar.TcoTch");
	else if (ix == PNLFMNCTOLACHAR_TCOVAL) return("PnlFmncTolAChar.TcoVal");
	else if (ix == PNLFMNCTOLACHAR_TCOCMT) return("PnlFmncTolAChar.TcoCmt");
	else if (ix == PNLFMNCTOLARES_TCOFUS) return("PnlFmncTolARes.TcoFus");
	else if (ix == PNLFMNCTOLARES_TCODAT) return("PnlFmncTolARes.TcoDat");
	else if (ix == PNLFMNCTOLARES_TCOSTA) return("PnlFmncTolARes.TcoSta");
	else if (ix == PNLFMNCTOLARES_TCOSTO) return("PnlFmncTolARes.TcoSto");
	else if (ix == PNLFMNCTOLARES_TCORTY) return("PnlFmncTolARes.TcoRty");
	else if (ix == PNLFMNCTOLARES_TCOCMT) return("PnlFmncTolARes.TcoCmt");
	else if (ix == PNLFMNCTOLAUTIL_TCOFPJ) return("PnlFmncTolAUtil.TcoFpj");
	else if (ix == PNLFMNCTOLAUTIL_TCOFUS) return("PnlFmncTolAUtil.TcoFus");
	else if (ix == PNLFMNCTOLAUTIL_TCODAT) return("PnlFmncTolAUtil.TcoDat");
	else if (ix == PNLFMNCTOLAUTIL_TCOSTA) return("PnlFmncTolAUtil.TcoSta");
	else if (ix == PNLFMNCTOLAUTIL_TCOSTO) return("PnlFmncTolAUtil.TcoSto");
	else if (ix == PNLFMNCTOLAUTIL_TCOUPR) return("PnlFmncTolAUtil.TcoUpr");
	else if (ix == PNLFMNCTOLAUTIL_TCOCMT) return("PnlFmncTolAUtil.TcoCmt");
	else if (ix == PNLFMNCTOL1NARTICLE_TCOREF) return("PnlFmncTol1NArticle.TcoRef");
	else if (ix == PNLFMNCTOLRLV1NSTEP_TCOREF) return("PnlFmncTolRlv1NStep.TcoRef");
	else if (ix == PNLFMNCTOLREF1NFILE_TCOREF) return("PnlFmncTolRef1NFile.TcoRef");
	else if (ix == PNLFMNCTOLMNTOOLTYPE_TCOMREF) return("PnlFmncTolMNTooltype.TcoMref");
	else if (ix == PNLFMNCTOLMNTOOLTYPE_TCOTCH) return("PnlFmncTolMNTooltype.TcoTch");
	else if (ix == PNLFMNCTOLMNTOOLTYPE_TCODEF) return("PnlFmncTolMNTooltype.TcoDef");
	else if (ix == PNLFMNCTOLMNTOOLTYPE_TCOOPT) return("PnlFmncTolMNTooltype.TcoOpt");
	else if (ix == PNLFMNCTOLMNFABUSER_TCOMREF) return("PnlFmncTolMNFabuser.TcoMref");
	else if (ix == PNLFMNCTOLMNFABUSER_TCOTRN) return("PnlFmncTolMNFabuser.TcoTrn");
	else if (ix == PNLFMNCTOLMNFABUSER_TCOLVL) return("PnlFmncTolMNFabuser.TcoLvl");
	else if (ix == PNLFMNCTOLSVCMNORG_TCOMREF) return("PnlFmncTolSvcMNOrg.TcoMref");
	else if (ix == PNLFMNCTOLSVCMNORG_TCOTPRS) return("PnlFmncTolSvcMNOrg.TcoTprs");
	else if (ix == PNLFMNCFPJLIST_TCOSRF) return("PnlFmncFpjList.TcoSrf");
	else if (ix == PNLFMNCFPJLIST_TCOTIT) return("PnlFmncFpjList.TcoTit");
	else if (ix == PNLFMNCFPJLIST_TCOFAB) return("PnlFmncFpjList.TcoFab");
	else if (ix == PNLFMNCFPJLIST_TCOBIO) return("PnlFmncFpjList.TcoBio");
	else if (ix == PNLFMNCFPJLIST_TCOSTE) return("PnlFmncFpjList.TcoSte");
	else if (ix == PNLFMNCFPJ1NBILL_TCOREF) return("PnlFmncFpj1NBill.TcoRef");
	else if (ix == PNLFMNCFPJMNFABUSER_TCOMREF) return("PnlFmncFpjMNFabuser.TcoMref");
	else if (ix == PNLFMNCBILLIST_TCOSRF) return("PnlFmncBilList.TcoSrf");
	else if (ix == PNLFMNCBILLIST_TCODAT) return("PnlFmncBilList.TcoDat");
	else if (ix == PNLFMNCBILLIST_TCOPRJ) return("PnlFmncBilList.TcoPrj");
	else if (ix == PNLFMNCBILLIST_TCOFIL) return("PnlFmncBilList.TcoFil");
	else if (ix == PNLFMNCBILLIST_TCOSTE) return("PnlFmncBilList.TcoSte");
	else if (ix == PNLFMNCBILLIST_TCOPRA) return("PnlFmncBilList.TcoPra");
	else if (ix == PNLFMNCBILLIST_TCOPRO) return("PnlFmncBilList.TcoPro");
	else if (ix == PNLFMNCBILLIST_TCOAMT) return("PnlFmncBilList.TcoAmt");
	else if (ix == PNLFMNCBILAPOS_TCOFUS) return("PnlFmncBilAPos.TcoFus");
	else if (ix == PNLFMNCBILAPOS_TCOTOL) return("PnlFmncBilAPos.TcoTol");
	else if (ix == PNLFMNCBILAPOS_TCOQTY) return("PnlFmncBilAPos.TcoQty");
	else if (ix == PNLFMNCBILAPOS_TCOART) return("PnlFmncBilAPos.TcoArt");
	else if (ix == PNLFMNCBILAPOS_TCOUPR) return("PnlFmncBilAPos.TcoUpr");
	else if (ix == PNLFMNCBILAPOS_TCOPRC) return("PnlFmncBilAPos.TcoPrc");
	else if (ix == PNLFMNCARTLIST_TCOSRF) return("PnlFmncArtList.TcoSrf");
	else if (ix == PNLFMNCARTLIST_TCOTIT) return("PnlFmncArtList.TcoTit");
	else if (ix == PNLFMNCARTLIST_TCOORG) return("PnlFmncArtList.TcoOrg");
	else if (ix == PNLFMNCARTLIST_TCOTOL) return("PnlFmncArtList.TcoTol");
	else if (ix == PNLFMNCARTLIST_TCOTYP) return("PnlFmncArtList.TcoTyp");
	else if (ix == PNLFMNCART1NSAMPLE_TCOREF) return("PnlFmncArt1NSample.TcoRef");
	else if (ix == PNLFMNCART1NSTOCKITEM_TCOREF) return("PnlFmncArt1NStockitem.TcoRef");
	else if (ix == PNLFMNCARTREF1NFILE_TCOREF) return("PnlFmncArtRef1NFile.TcoRef");
	else if (ix == PNLFMNCARTMNORG_TCOMREF) return("PnlFmncArtMNOrg.TcoMref");
	else if (ix == PNLFMNCARTMNORG_TCOITN) return("PnlFmncArtMNOrg.TcoItn");
	else if (ix == PNLFMNCSKILIST_TCOORG) return("PnlFmncSkiList.TcoOrg");
	else if (ix == PNLFMNCSKILIST_TCOART) return("PnlFmncSkiList.TcoArt");
	else if (ix == PNLFMNCSKILIST_TCOQTY) return("PnlFmncSkiList.TcoQty");
	else if (ix == PNLFMNCSKILIST_TCOLCN) return("PnlFmncSkiList.TcoLcn");
	else if (ix == PNLFMNCSKILIST_TCOEXD) return("PnlFmncSkiList.TcoExd");
	else if (ix == PNLFMNCPCOLIST_TCOSRF) return("PnlFmncPcoList.TcoSrf");
	else if (ix == PNLFMNCPCOLIST_TCODAT) return("PnlFmncPcoList.TcoDat");
	else if (ix == PNLFMNCPCOLIST_TCOPCO) return("PnlFmncPcoList.TcoPco");
	else if (ix == PNLFMNCPCOLIST_TCOSPL) return("PnlFmncPcoList.TcoSpl");
	else if (ix == PNLFMNCPCOLIST_TCOFIL) return("PnlFmncPcoList.TcoFil");
	else if (ix == PNLFMNCPCOLIST_TCOSTE) return("PnlFmncPcoList.TcoSte");
	else if (ix == PNLFMNCPCOLIST_TCOAMT) return("PnlFmncPcoList.TcoAmt");
	else if (ix == PNLFMNCPCOAPOS_TCOQTY) return("PnlFmncPcoAPos.TcoQty");
	else if (ix == PNLFMNCPCOAPOS_TCOITN) return("PnlFmncPcoAPos.TcoItn");
	else if (ix == PNLFMNCPCOAPOS_TCOART) return("PnlFmncPcoAPos.TcoArt");
	else if (ix == PNLFMNCPCOAPOS_TCOUPR) return("PnlFmncPcoAPos.TcoUpr");
	else if (ix == PNLFMNCPCOAPOS_TCOPRC) return("PnlFmncPcoAPos.TcoPrc");

	return("");
};

