/**
  * \file VecFmncVDpch.cpp
  * vector VecFmncVDpch (implementation)
  * \author Alexander Wirthmueller
  * \date created: 7 Mar 2016
  * \date modified: 7 Mar 2016
  */

#include "VecFmncVDpch.h"

/******************************************************************************
 namespace VecFmncVDpch
 ******************************************************************************/

uint VecFmncVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchappdlgfmncactnewdata") return DPCHAPPDLGFMNCACTNEWDATA;
	else if (s == "dpchappdlgfmncactnewdo") return DPCHAPPDLGFMNCACTNEWDO;
	else if (s == "dpchappdlgfmncfabexpfabdata") return DPCHAPPDLGFMNCFABEXPFABDATA;
	else if (s == "dpchappdlgfmncfabexpfabdo") return DPCHAPPDLGFMNCFABEXPFABDO;
	else if (s == "dpchappdlgfmncfabimpfabdata") return DPCHAPPDLGFMNCFABIMPFABDATA;
	else if (s == "dpchappdlgfmncfabimpfabdo") return DPCHAPPDLGFMNCFABIMPFABDO;
	else if (s == "dpchappdlgfmncfabnewdata") return DPCHAPPDLGFMNCFABNEWDATA;
	else if (s == "dpchappdlgfmncfabnewdo") return DPCHAPPDLGFMNCFABNEWDO;
	else if (s == "dpchappdlgfmncnavloainidata") return DPCHAPPDLGFMNCNAVLOAINIDATA;
	else if (s == "dpchappdlgfmncnavloainido") return DPCHAPPDLGFMNCNAVLOAINIDO;
	else if (s == "dpchappdlgfmncorgexporgdata") return DPCHAPPDLGFMNCORGEXPORGDATA;
	else if (s == "dpchappdlgfmncorgexporgdo") return DPCHAPPDLGFMNCORGEXPORGDO;
	else if (s == "dpchappdlgfmncorgimporgdata") return DPCHAPPDLGFMNCORGIMPORGDATA;
	else if (s == "dpchappdlgfmncorgimporgdo") return DPCHAPPDLGFMNCORGIMPORGDO;
	else if (s == "dpchappdlgfmncorgnewdata") return DPCHAPPDLGFMNCORGNEWDATA;
	else if (s == "dpchappdlgfmncorgnewdo") return DPCHAPPDLGFMNCORGNEWDO;
	else if (s == "dpchappdlgfmncprjexpelbdata") return DPCHAPPDLGFMNCPRJEXPELBDATA;
	else if (s == "dpchappdlgfmncprjexpelbdo") return DPCHAPPDLGFMNCPRJEXPELBDO;
	else if (s == "dpchappdlgfmncprjimpelbdata") return DPCHAPPDLGFMNCPRJIMPELBDATA;
	else if (s == "dpchappdlgfmncprjimpelbdo") return DPCHAPPDLGFMNCPRJIMPELBDO;
	else if (s == "dpchappdlgfmncprjnewdata") return DPCHAPPDLGFMNCPRJNEWDATA;
	else if (s == "dpchappdlgfmncprjnewdo") return DPCHAPPDLGFMNCPRJNEWDO;
	else if (s == "dpchappdlgfmncrungenrepdata") return DPCHAPPDLGFMNCRUNGENREPDATA;
	else if (s == "dpchappdlgfmncrungenrepdo") return DPCHAPPDLGFMNCRUNGENREPDO;
	else if (s == "dpchappdlgfmncrunnewdata") return DPCHAPPDLGFMNCRUNNEWDATA;
	else if (s == "dpchappdlgfmncrunnewdo") return DPCHAPPDLGFMNCRUNNEWDO;
	else if (s == "dpchappdlgfmncsmpgenrepdata") return DPCHAPPDLGFMNCSMPGENREPDATA;
	else if (s == "dpchappdlgfmncsmpgenrepdo") return DPCHAPPDLGFMNCSMPGENREPDO;
	else if (s == "dpchappdlgfmncsmpnewdata") return DPCHAPPDLGFMNCSMPNEWDATA;
	else if (s == "dpchappdlgfmncsmpnewdo") return DPCHAPPDLGFMNCSMPNEWDO;
	else if (s == "dpchappfmncact1nstepdata") return DPCHAPPFMNCACT1NSTEPDATA;
	else if (s == "dpchappfmncact1nstepdo") return DPCHAPPFMNCACT1NSTEPDO;
	else if (s == "dpchappfmncactdetaildata") return DPCHAPPFMNCACTDETAILDATA;
	else if (s == "dpchappfmncactdetaildo") return DPCHAPPFMNCACTDETAILDO;
	else if (s == "dpchappfmncactdo") return DPCHAPPFMNCACTDO;
	else if (s == "dpchappfmncactlistdata") return DPCHAPPFMNCACTLISTDATA;
	else if (s == "dpchappfmncactlistdo") return DPCHAPPFMNCACTLISTDO;
	else if (s == "dpchappfmncactrecdo") return DPCHAPPFMNCACTRECDO;
	else if (s == "dpchappfmncadrdetaildata") return DPCHAPPFMNCADRDETAILDATA;
	else if (s == "dpchappfmncadrdetaildo") return DPCHAPPFMNCADRDETAILDO;
	else if (s == "dpchappfmncadrdo") return DPCHAPPFMNCADRDO;
	else if (s == "dpchappfmncadrlistdata") return DPCHAPPFMNCADRLISTDATA;
	else if (s == "dpchappfmncadrlistdo") return DPCHAPPFMNCADRLISTDO;
	else if (s == "dpchappfmncadrrecdo") return DPCHAPPFMNCADRRECDO;
	else if (s == "dpchappfmncalert") return DPCHAPPFMNCALERT;
	else if (s == "dpchappfmncart1nsampledata") return DPCHAPPFMNCART1NSAMPLEDATA;
	else if (s == "dpchappfmncart1nsampledo") return DPCHAPPFMNCART1NSAMPLEDO;
	else if (s == "dpchappfmncart1nstockitemdata") return DPCHAPPFMNCART1NSTOCKITEMDATA;
	else if (s == "dpchappfmncart1nstockitemdo") return DPCHAPPFMNCART1NSTOCKITEMDO;
	else if (s == "dpchappfmncartdetaildata") return DPCHAPPFMNCARTDETAILDATA;
	else if (s == "dpchappfmncartdetaildo") return DPCHAPPFMNCARTDETAILDO;
	else if (s == "dpchappfmncartdo") return DPCHAPPFMNCARTDO;
	else if (s == "dpchappfmncartlistdata") return DPCHAPPFMNCARTLISTDATA;
	else if (s == "dpchappfmncartlistdo") return DPCHAPPFMNCARTLISTDO;
	else if (s == "dpchappfmncartmnorgdata") return DPCHAPPFMNCARTMNORGDATA;
	else if (s == "dpchappfmncartmnorgdo") return DPCHAPPFMNCARTMNORGDO;
	else if (s == "dpchappfmncartrecdo") return DPCHAPPFMNCARTRECDO;
	else if (s == "dpchappfmncartref1nfiledata") return DPCHAPPFMNCARTREF1NFILEDATA;
	else if (s == "dpchappfmncartref1nfiledo") return DPCHAPPFMNCARTREF1NFILEDO;
	else if (s == "dpchappfmncbilaposdata") return DPCHAPPFMNCBILAPOSDATA;
	else if (s == "dpchappfmncbilaposdo") return DPCHAPPFMNCBILAPOSDO;
	else if (s == "dpchappfmncbildetaildata") return DPCHAPPFMNCBILDETAILDATA;
	else if (s == "dpchappfmncbildetaildo") return DPCHAPPFMNCBILDETAILDO;
	else if (s == "dpchappfmncbildo") return DPCHAPPFMNCBILDO;
	else if (s == "dpchappfmncbillistdata") return DPCHAPPFMNCBILLISTDATA;
	else if (s == "dpchappfmncbillistdo") return DPCHAPPFMNCBILLISTDO;
	else if (s == "dpchappfmncbilrecdo") return DPCHAPPFMNCBILRECDO;
	else if (s == "dpchappfmncfab1nfabprojectdata") return DPCHAPPFMNCFAB1NFABPROJECTDATA;
	else if (s == "dpchappfmncfab1nfabprojectdo") return DPCHAPPFMNCFAB1NFABPROJECTDO;
	else if (s == "dpchappfmncfab1nfabuserdata") return DPCHAPPFMNCFAB1NFABUSERDATA;
	else if (s == "dpchappfmncfab1nfabuserdo") return DPCHAPPFMNCFAB1NFABUSERDO;
	else if (s == "dpchappfmncfabdetaildo") return DPCHAPPFMNCFABDETAILDO;
	else if (s == "dpchappfmncfabdo") return DPCHAPPFMNCFABDO;
	else if (s == "dpchappfmncfabfab1ntooldata") return DPCHAPPFMNCFABFAB1NTOOLDATA;
	else if (s == "dpchappfmncfabfab1ntooldo") return DPCHAPPFMNCFABFAB1NTOOLDO;
	else if (s == "dpchappfmncfablistdata") return DPCHAPPFMNCFABLISTDATA;
	else if (s == "dpchappfmncfablistdo") return DPCHAPPFMNCFABLISTDO;
	else if (s == "dpchappfmncfabmnrundata") return DPCHAPPFMNCFABMNRUNDATA;
	else if (s == "dpchappfmncfabmnrundo") return DPCHAPPFMNCFABMNRUNDO;
	else if (s == "dpchappfmncfabrecdo") return DPCHAPPFMNCFABRECDO;
	else if (s == "dpchappfmncfildetaildata") return DPCHAPPFMNCFILDETAILDATA;
	else if (s == "dpchappfmncfildetaildo") return DPCHAPPFMNCFILDETAILDO;
	else if (s == "dpchappfmncfildo") return DPCHAPPFMNCFILDO;
	else if (s == "dpchappfmncfillistdata") return DPCHAPPFMNCFILLISTDATA;
	else if (s == "dpchappfmncfillistdo") return DPCHAPPFMNCFILLISTDO;
	else if (s == "dpchappfmncfilmnsampledata") return DPCHAPPFMNCFILMNSAMPLEDATA;
	else if (s == "dpchappfmncfilmnsampledo") return DPCHAPPFMNCFILMNSAMPLEDO;
	else if (s == "dpchappfmncfilmnstepdata") return DPCHAPPFMNCFILMNSTEPDATA;
	else if (s == "dpchappfmncfilmnstepdo") return DPCHAPPFMNCFILMNSTEPDO;
	else if (s == "dpchappfmncfilrecdo") return DPCHAPPFMNCFILRECDO;
	else if (s == "dpchappfmncfpj1nbilldata") return DPCHAPPFMNCFPJ1NBILLDATA;
	else if (s == "dpchappfmncfpj1nbilldo") return DPCHAPPFMNCFPJ1NBILLDO;
	else if (s == "dpchappfmncfpjdetaildata") return DPCHAPPFMNCFPJDETAILDATA;
	else if (s == "dpchappfmncfpjdetaildo") return DPCHAPPFMNCFPJDETAILDO;
	else if (s == "dpchappfmncfpjdo") return DPCHAPPFMNCFPJDO;
	else if (s == "dpchappfmncfpjlistdata") return DPCHAPPFMNCFPJLISTDATA;
	else if (s == "dpchappfmncfpjlistdo") return DPCHAPPFMNCFPJLISTDO;
	else if (s == "dpchappfmncfpjmnfabuserdata") return DPCHAPPFMNCFPJMNFABUSERDATA;
	else if (s == "dpchappfmncfpjmnfabuserdo") return DPCHAPPFMNCFPJMNFABUSERDO;
	else if (s == "dpchappfmncfpjrecdo") return DPCHAPPFMNCFPJRECDO;
	else if (s == "dpchappfmncfusdetaildata") return DPCHAPPFMNCFUSDETAILDATA;
	else if (s == "dpchappfmncfusdetaildo") return DPCHAPPFMNCFUSDETAILDO;
	else if (s == "dpchappfmncfusdo") return DPCHAPPFMNCFUSDO;
	else if (s == "dpchappfmncfuslistdata") return DPCHAPPFMNCFUSLISTDATA;
	else if (s == "dpchappfmncfuslistdo") return DPCHAPPFMNCFUSLISTDO;
	else if (s == "dpchappfmncfusmnfabprojectdata") return DPCHAPPFMNCFUSMNFABPROJECTDATA;
	else if (s == "dpchappfmncfusmnfabprojectdo") return DPCHAPPFMNCFUSMNFABPROJECTDO;
	else if (s == "dpchappfmncfusmntooldata") return DPCHAPPFMNCFUSMNTOOLDATA;
	else if (s == "dpchappfmncfusmntooldo") return DPCHAPPFMNCFUSMNTOOLDO;
	else if (s == "dpchappfmncfusrecdo") return DPCHAPPFMNCFUSRECDO;
	else if (s == "dpchappfmncinit") return DPCHAPPFMNCINIT;
	else if (s == "dpchappfmncnavadmindata") return DPCHAPPFMNCNAVADMINDATA;
	else if (s == "dpchappfmncnavadmindo") return DPCHAPPFMNCNAVADMINDO;
	else if (s == "dpchappfmncnavdo") return DPCHAPPFMNCNAVDO;
	else if (s == "dpchappfmncnavfabmgmtdata") return DPCHAPPFMNCNAVFABMGMTDATA;
	else if (s == "dpchappfmncnavfabmgmtdo") return DPCHAPPFMNCNAVFABMGMTDO;
	else if (s == "dpchappfmncnavlabbookdata") return DPCHAPPFMNCNAVLABBOOKDATA;
	else if (s == "dpchappfmncnavlabbookdo") return DPCHAPPFMNCNAVLABBOOKDO;
	else if (s == "dpchappfmncnavpredo") return DPCHAPPFMNCNAVPREDO;
	else if (s == "dpchappfmncnavsupplydata") return DPCHAPPFMNCNAVSUPPLYDATA;
	else if (s == "dpchappfmncnavsupplydo") return DPCHAPPFMNCNAVSUPPLYDO;
	else if (s == "dpchappfmncorg1narticledata") return DPCHAPPFMNCORG1NARTICLEDATA;
	else if (s == "dpchappfmncorg1narticledo") return DPCHAPPFMNCORG1NARTICLEDO;
	else if (s == "dpchappfmncorg1nstockitemdata") return DPCHAPPFMNCORG1NSTOCKITEMDATA;
	else if (s == "dpchappfmncorg1nstockitemdo") return DPCHAPPFMNCORG1NSTOCKITEMDO;
	else if (s == "dpchappfmncorgadetaildata") return DPCHAPPFMNCORGADETAILDATA;
	else if (s == "dpchappfmncorgadetaildo") return DPCHAPPFMNCORGADETAILDO;
	else if (s == "dpchappfmncorgbio1nfabprojectdata") return DPCHAPPFMNCORGBIO1NFABPROJECTDATA;
	else if (s == "dpchappfmncorgbio1nfabprojectdo") return DPCHAPPFMNCORGBIO1NFABPROJECTDO;
	else if (s == "dpchappfmncorgdetaildata") return DPCHAPPFMNCORGDETAILDATA;
	else if (s == "dpchappfmncorgdetaildo") return DPCHAPPFMNCORGDETAILDO;
	else if (s == "dpchappfmncorgdo") return DPCHAPPFMNCORGDO;
	else if (s == "dpchappfmncorghk1naddressdata") return DPCHAPPFMNCORGHK1NADDRESSDATA;
	else if (s == "dpchappfmncorghk1naddressdo") return DPCHAPPFMNCORGHK1NADDRESSDO;
	else if (s == "dpchappfmncorgkstocklcndata") return DPCHAPPFMNCORGKSTOCKLCNDATA;
	else if (s == "dpchappfmncorgkstocklcndo") return DPCHAPPFMNCORGKSTOCKLCNDO;
	else if (s == "dpchappfmncorglistdata") return DPCHAPPFMNCORGLISTDATA;
	else if (s == "dpchappfmncorglistdo") return DPCHAPPFMNCORGLISTDO;
	else if (s == "dpchappfmncorgmnarticledata") return DPCHAPPFMNCORGMNARTICLEDATA;
	else if (s == "dpchappfmncorgmnarticledo") return DPCHAPPFMNCORGMNARTICLEDO;
	else if (s == "dpchappfmncorgmnf1ntooldata") return DPCHAPPFMNCORGMNF1NTOOLDATA;
	else if (s == "dpchappfmncorgmnf1ntooldo") return DPCHAPPFMNCORGMNF1NTOOLDO;
	else if (s == "dpchappfmncorgmnpersondata") return DPCHAPPFMNCORGMNPERSONDATA;
	else if (s == "dpchappfmncorgmnpersondo") return DPCHAPPFMNCORGMNPERSONDO;
	else if (s == "dpchappfmncorgpco1npurchorderdata") return DPCHAPPFMNCORGPCO1NPURCHORDERDATA;
	else if (s == "dpchappfmncorgpco1npurchorderdo") return DPCHAPPFMNCORGPCO1NPURCHORDERDO;
	else if (s == "dpchappfmncorgrecdo") return DPCHAPPFMNCORGRECDO;
	else if (s == "dpchappfmncorgspl1npurchorderdata") return DPCHAPPFMNCORGSPL1NPURCHORDERDATA;
	else if (s == "dpchappfmncorgspl1npurchorderdo") return DPCHAPPFMNCORGSPL1NPURCHORDERDO;
	else if (s == "dpchappfmncorgsup1norgdata") return DPCHAPPFMNCORGSUP1NORGDATA;
	else if (s == "dpchappfmncorgsup1norgdo") return DPCHAPPFMNCORGSUP1NORGDO;
	else if (s == "dpchappfmncorgsvcmntooldata") return DPCHAPPFMNCORGSVCMNTOOLDATA;
	else if (s == "dpchappfmncorgsvcmntooldo") return DPCHAPPFMNCORGSVCMNTOOLDO;
	else if (s == "dpchappfmncpcoaposdata") return DPCHAPPFMNCPCOAPOSDATA;
	else if (s == "dpchappfmncpcoaposdo") return DPCHAPPFMNCPCOAPOSDO;
	else if (s == "dpchappfmncpcodetaildata") return DPCHAPPFMNCPCODETAILDATA;
	else if (s == "dpchappfmncpcodetaildo") return DPCHAPPFMNCPCODETAILDO;
	else if (s == "dpchappfmncpcodo") return DPCHAPPFMNCPCODO;
	else if (s == "dpchappfmncpcolistdata") return DPCHAPPFMNCPCOLISTDATA;
	else if (s == "dpchappfmncpcolistdo") return DPCHAPPFMNCPCOLISTDO;
	else if (s == "dpchappfmncpcorecdo") return DPCHAPPFMNCPCORECDO;
	else if (s == "dpchappfmncprj1nrundata") return DPCHAPPFMNCPRJ1NRUNDATA;
	else if (s == "dpchappfmncprj1nrundo") return DPCHAPPFMNCPRJ1NRUNDO;
	else if (s == "dpchappfmncprjdetaildata") return DPCHAPPFMNCPRJDETAILDATA;
	else if (s == "dpchappfmncprjdetaildo") return DPCHAPPFMNCPRJDETAILDO;
	else if (s == "dpchappfmncprjdo") return DPCHAPPFMNCPRJDO;
	else if (s == "dpchappfmncprjlistdata") return DPCHAPPFMNCPRJLISTDATA;
	else if (s == "dpchappfmncprjlistdo") return DPCHAPPFMNCPRJLISTDO;
	else if (s == "dpchappfmncprjrecdo") return DPCHAPPFMNCPRJRECDO;
	else if (s == "dpchappfmncprsadetaildata") return DPCHAPPFMNCPRSADETAILDATA;
	else if (s == "dpchappfmncprsadetaildo") return DPCHAPPFMNCPRSADETAILDO;
	else if (s == "dpchappfmncprsdetaildata") return DPCHAPPFMNCPRSDETAILDATA;
	else if (s == "dpchappfmncprsdetaildo") return DPCHAPPFMNCPRSDETAILDO;
	else if (s == "dpchappfmncprsdo") return DPCHAPPFMNCPRSDO;
	else if (s == "dpchappfmncprshk1naddressdata") return DPCHAPPFMNCPRSHK1NADDRESSDATA;
	else if (s == "dpchappfmncprshk1naddressdo") return DPCHAPPFMNCPRSHK1NADDRESSDO;
	else if (s == "dpchappfmncprslistdata") return DPCHAPPFMNCPRSLISTDATA;
	else if (s == "dpchappfmncprslistdo") return DPCHAPPFMNCPRSLISTDO;
	else if (s == "dpchappfmncprsmnorgdata") return DPCHAPPFMNCPRSMNORGDATA;
	else if (s == "dpchappfmncprsmnorgdo") return DPCHAPPFMNCPRSMNORGDO;
	else if (s == "dpchappfmncprsmnrundata") return DPCHAPPFMNCPRSMNRUNDATA;
	else if (s == "dpchappfmncprsmnrundo") return DPCHAPPFMNCPRSMNRUNDO;
	else if (s == "dpchappfmncprsrecdo") return DPCHAPPFMNCPRSRECDO;
	else if (s == "dpchappfmncresume") return DPCHAPPFMNCRESUME;
	else if (s == "dpchappfmncrundetaildata") return DPCHAPPFMNCRUNDETAILDATA;
	else if (s == "dpchappfmncrundetaildo") return DPCHAPPFMNCRUNDETAILDO;
	else if (s == "dpchappfmncrundo") return DPCHAPPFMNCRUNDO;
	else if (s == "dpchappfmncrunlistdata") return DPCHAPPFMNCRUNLISTDATA;
	else if (s == "dpchappfmncrunlistdo") return DPCHAPPFMNCRUNLISTDO;
	else if (s == "dpchappfmncrunmnfabdata") return DPCHAPPFMNCRUNMNFABDATA;
	else if (s == "dpchappfmncrunmnfabdo") return DPCHAPPFMNCRUNMNFABDO;
	else if (s == "dpchappfmncrunmnpersondata") return DPCHAPPFMNCRUNMNPERSONDATA;
	else if (s == "dpchappfmncrunmnpersondo") return DPCHAPPFMNCRUNMNPERSONDO;
	else if (s == "dpchappfmncrunmnsampledata") return DPCHAPPFMNCRUNMNSAMPLEDATA;
	else if (s == "dpchappfmncrunmnsampledo") return DPCHAPPFMNCRUNMNSAMPLEDO;
	else if (s == "dpchappfmncrunrecdo") return DPCHAPPFMNCRUNRECDO;
	else if (s == "dpchappfmncrunref1nfiledata") return DPCHAPPFMNCRUNREF1NFILEDATA;
	else if (s == "dpchappfmncrunref1nfiledo") return DPCHAPPFMNCRUNREF1NFILEDO;
	else if (s == "dpchappfmncrunrun1nactivitydata") return DPCHAPPFMNCRUNRUN1NACTIVITYDATA;
	else if (s == "dpchappfmncrunrun1nactivitydo") return DPCHAPPFMNCRUNRUN1NACTIVITYDO;
	else if (s == "dpchappfmncsepapardata") return DPCHAPPFMNCSEPAPARDATA;
	else if (s == "dpchappfmncsepapardo") return DPCHAPPFMNCSEPAPARDO;
	else if (s == "dpchappfmncsepdetaildata") return DPCHAPPFMNCSEPDETAILDATA;
	else if (s == "dpchappfmncsepdetaildo") return DPCHAPPFMNCSEPDETAILDO;
	else if (s == "dpchappfmncsepdo") return DPCHAPPFMNCSEPDO;
	else if (s == "dpchappfmncseplistdata") return DPCHAPPFMNCSEPLISTDATA;
	else if (s == "dpchappfmncseplistdo") return DPCHAPPFMNCSEPLISTDO;
	else if (s == "dpchappfmncsepmnfiledata") return DPCHAPPFMNCSEPMNFILEDATA;
	else if (s == "dpchappfmncsepmnfiledo") return DPCHAPPFMNCSEPMNFILEDO;
	else if (s == "dpchappfmncsepmnsampledata") return DPCHAPPFMNCSEPMNSAMPLEDATA;
	else if (s == "dpchappfmncsepmnsampledo") return DPCHAPPFMNCSEPMNSAMPLEDO;
	else if (s == "dpchappfmncseprecdo") return DPCHAPPFMNCSEPRECDO;
	else if (s == "dpchappfmncsepref1nfiledata") return DPCHAPPFMNCSEPREF1NFILEDATA;
	else if (s == "dpchappfmncsepref1nfiledo") return DPCHAPPFMNCSEPREF1NFILEDO;
	else if (s == "dpchappfmncskidetaildata") return DPCHAPPFMNCSKIDETAILDATA;
	else if (s == "dpchappfmncskidetaildo") return DPCHAPPFMNCSKIDETAILDO;
	else if (s == "dpchappfmncskido") return DPCHAPPFMNCSKIDO;
	else if (s == "dpchappfmncskilistdata") return DPCHAPPFMNCSKILISTDATA;
	else if (s == "dpchappfmncskilistdo") return DPCHAPPFMNCSKILISTDO;
	else if (s == "dpchappfmncskirecdo") return DPCHAPPFMNCSKIRECDO;
	else if (s == "dpchappfmncsmpapardata") return DPCHAPPFMNCSMPAPARDATA;
	else if (s == "dpchappfmncsmpapardo") return DPCHAPPFMNCSMPAPARDO;
	else if (s == "dpchappfmncsmpdetaildata") return DPCHAPPFMNCSMPDETAILDATA;
	else if (s == "dpchappfmncsmpdetaildo") return DPCHAPPFMNCSMPDETAILDO;
	else if (s == "dpchappfmncsmpdo") return DPCHAPPFMNCSMPDO;
	else if (s == "dpchappfmncsmplistdata") return DPCHAPPFMNCSMPLISTDATA;
	else if (s == "dpchappfmncsmplistdo") return DPCHAPPFMNCSMPLISTDO;
	else if (s == "dpchappfmncsmpmnfiledata") return DPCHAPPFMNCSMPMNFILEDATA;
	else if (s == "dpchappfmncsmpmnfiledo") return DPCHAPPFMNCSMPMNFILEDO;
	else if (s == "dpchappfmncsmpmnrundata") return DPCHAPPFMNCSMPMNRUNDATA;
	else if (s == "dpchappfmncsmpmnrundo") return DPCHAPPFMNCSMPMNRUNDO;
	else if (s == "dpchappfmncsmpmnstepdata") return DPCHAPPFMNCSMPMNSTEPDATA;
	else if (s == "dpchappfmncsmpmnstepdo") return DPCHAPPFMNCSMPMNSTEPDO;
	else if (s == "dpchappfmncsmprecdo") return DPCHAPPFMNCSMPRECDO;
	else if (s == "dpchappfmncsmpref1nfiledata") return DPCHAPPFMNCSMPREF1NFILEDATA;
	else if (s == "dpchappfmncsmpref1nfiledo") return DPCHAPPFMNCSMPREF1NFILEDO;
	else if (s == "dpchappfmncsmpsup1nsampledata") return DPCHAPPFMNCSMPSUP1NSAMPLEDATA;
	else if (s == "dpchappfmncsmpsup1nsampledo") return DPCHAPPFMNCSMPSUP1NSAMPLEDO;
	else if (s == "dpchappfmncstpapardata") return DPCHAPPFMNCSTPAPARDATA;
	else if (s == "dpchappfmncstpapardo") return DPCHAPPFMNCSTPAPARDO;
	else if (s == "dpchappfmncstpdetaildata") return DPCHAPPFMNCSTPDETAILDATA;
	else if (s == "dpchappfmncstpdetaildo") return DPCHAPPFMNCSTPDETAILDO;
	else if (s == "dpchappfmncstpdo") return DPCHAPPFMNCSTPDO;
	else if (s == "dpchappfmncstpksteppardata") return DPCHAPPFMNCSTPKSTEPPARDATA;
	else if (s == "dpchappfmncstpksteppardo") return DPCHAPPFMNCSTPKSTEPPARDO;
	else if (s == "dpchappfmncstplistdata") return DPCHAPPFMNCSTPLISTDATA;
	else if (s == "dpchappfmncstplistdo") return DPCHAPPFMNCSTPLISTDO;
	else if (s == "dpchappfmncstpmnfiledata") return DPCHAPPFMNCSTPMNFILEDATA;
	else if (s == "dpchappfmncstpmnfiledo") return DPCHAPPFMNCSTPMNFILEDO;
	else if (s == "dpchappfmncstprecdo") return DPCHAPPFMNCSTPRECDO;
	else if (s == "dpchappfmncstpref1nfiledata") return DPCHAPPFMNCSTPREF1NFILEDATA;
	else if (s == "dpchappfmncstpref1nfiledo") return DPCHAPPFMNCSTPREF1NFILEDO;
	else if (s == "dpchappfmncstptpl1nstepdata") return DPCHAPPFMNCSTPTPL1NSTEPDATA;
	else if (s == "dpchappfmncstptpl1nstepdo") return DPCHAPPFMNCSTPTPL1NSTEPDO;
	else if (s == "dpchappfmnctol1narticledata") return DPCHAPPFMNCTOL1NARTICLEDATA;
	else if (s == "dpchappfmnctol1narticledo") return DPCHAPPFMNCTOL1NARTICLEDO;
	else if (s == "dpchappfmnctolaavldata") return DPCHAPPFMNCTOLAAVLDATA;
	else if (s == "dpchappfmnctolaavldo") return DPCHAPPFMNCTOLAAVLDO;
	else if (s == "dpchappfmnctolachardata") return DPCHAPPFMNCTOLACHARDATA;
	else if (s == "dpchappfmnctolachardo") return DPCHAPPFMNCTOLACHARDO;
	else if (s == "dpchappfmnctolaresdata") return DPCHAPPFMNCTOLARESDATA;
	else if (s == "dpchappfmnctolaresdo") return DPCHAPPFMNCTOLARESDO;
	else if (s == "dpchappfmnctolautildata") return DPCHAPPFMNCTOLAUTILDATA;
	else if (s == "dpchappfmnctolautildo") return DPCHAPPFMNCTOLAUTILDO;
	else if (s == "dpchappfmnctoldetaildata") return DPCHAPPFMNCTOLDETAILDATA;
	else if (s == "dpchappfmnctoldetaildo") return DPCHAPPFMNCTOLDETAILDO;
	else if (s == "dpchappfmnctoldo") return DPCHAPPFMNCTOLDO;
	else if (s == "dpchappfmnctolksteppardata") return DPCHAPPFMNCTOLKSTEPPARDATA;
	else if (s == "dpchappfmnctolksteppardo") return DPCHAPPFMNCTOLKSTEPPARDO;
	else if (s == "dpchappfmnctolktoolchardata") return DPCHAPPFMNCTOLKTOOLCHARDATA;
	else if (s == "dpchappfmnctolktoolchardo") return DPCHAPPFMNCTOLKTOOLCHARDO;
	else if (s == "dpchappfmnctollistdata") return DPCHAPPFMNCTOLLISTDATA;
	else if (s == "dpchappfmnctollistdo") return DPCHAPPFMNCTOLLISTDO;
	else if (s == "dpchappfmnctolmnfabuserdata") return DPCHAPPFMNCTOLMNFABUSERDATA;
	else if (s == "dpchappfmnctolmnfabuserdo") return DPCHAPPFMNCTOLMNFABUSERDO;
	else if (s == "dpchappfmnctolmntooltypedata") return DPCHAPPFMNCTOLMNTOOLTYPEDATA;
	else if (s == "dpchappfmnctolmntooltypedo") return DPCHAPPFMNCTOLMNTOOLTYPEDO;
	else if (s == "dpchappfmnctolrecdo") return DPCHAPPFMNCTOLRECDO;
	else if (s == "dpchappfmnctolref1nfiledata") return DPCHAPPFMNCTOLREF1NFILEDATA;
	else if (s == "dpchappfmnctolref1nfiledo") return DPCHAPPFMNCTOLREF1NFILEDO;
	else if (s == "dpchappfmnctolrlv1nstepdata") return DPCHAPPFMNCTOLRLV1NSTEPDATA;
	else if (s == "dpchappfmnctolrlv1nstepdo") return DPCHAPPFMNCTOLRLV1NSTEPDO;
	else if (s == "dpchappfmnctolsvcmnorgdata") return DPCHAPPFMNCTOLSVCMNORGDATA;
	else if (s == "dpchappfmnctolsvcmnorgdo") return DPCHAPPFMNCTOLSVCMNORGDO;
	else if (s == "dpchappfmncttydetaildata") return DPCHAPPFMNCTTYDETAILDATA;
	else if (s == "dpchappfmncttydetaildo") return DPCHAPPFMNCTTYDETAILDO;
	else if (s == "dpchappfmncttydo") return DPCHAPPFMNCTTYDO;
	else if (s == "dpchappfmncttyksteppardata") return DPCHAPPFMNCTTYKSTEPPARDATA;
	else if (s == "dpchappfmncttyksteppardo") return DPCHAPPFMNCTTYKSTEPPARDO;
	else if (s == "dpchappfmncttyktoolchardata") return DPCHAPPFMNCTTYKTOOLCHARDATA;
	else if (s == "dpchappfmncttyktoolchardo") return DPCHAPPFMNCTTYKTOOLCHARDO;
	else if (s == "dpchappfmncttylistdata") return DPCHAPPFMNCTTYLISTDATA;
	else if (s == "dpchappfmncttylistdo") return DPCHAPPFMNCTTYLISTDO;
	else if (s == "dpchappfmncttymntooldata") return DPCHAPPFMNCTTYMNTOOLDATA;
	else if (s == "dpchappfmncttymntooldo") return DPCHAPPFMNCTTYMNTOOLDO;
	else if (s == "dpchappfmncttyrecdo") return DPCHAPPFMNCTTYRECDO;
	else if (s == "dpchappfmncttyrlv1nstepdata") return DPCHAPPFMNCTTYRLV1NSTEPDATA;
	else if (s == "dpchappfmncttyrlv1nstepdo") return DPCHAPPFMNCTTYRLV1NSTEPDO;
	else if (s == "dpchappfmncttysup1ntooltypedata") return DPCHAPPFMNCTTYSUP1NTOOLTYPEDATA;
	else if (s == "dpchappfmncttysup1ntooltypedo") return DPCHAPPFMNCTTYSUP1NTOOLTYPEDO;
	else if (s == "dpchappfmncusgaaccessdata") return DPCHAPPFMNCUSGAACCESSDATA;
	else if (s == "dpchappfmncusgaaccessdo") return DPCHAPPFMNCUSGAACCESSDO;
	else if (s == "dpchappfmncusgdetaildata") return DPCHAPPFMNCUSGDETAILDATA;
	else if (s == "dpchappfmncusgdetaildo") return DPCHAPPFMNCUSGDETAILDO;
	else if (s == "dpchappfmncusgdo") return DPCHAPPFMNCUSGDO;
	else if (s == "dpchappfmncusglistdata") return DPCHAPPFMNCUSGLISTDATA;
	else if (s == "dpchappfmncusglistdo") return DPCHAPPFMNCUSGLISTDO;
	else if (s == "dpchappfmncusgmnuserdata") return DPCHAPPFMNCUSGMNUSERDATA;
	else if (s == "dpchappfmncusgmnuserdo") return DPCHAPPFMNCUSGMNUSERDO;
	else if (s == "dpchappfmncusgrecdo") return DPCHAPPFMNCUSGRECDO;
	else if (s == "dpchappfmncusr1nsessiondata") return DPCHAPPFMNCUSR1NSESSIONDATA;
	else if (s == "dpchappfmncusr1nsessiondo") return DPCHAPPFMNCUSR1NSESSIONDO;
	else if (s == "dpchappfmncusraaccessdata") return DPCHAPPFMNCUSRAACCESSDATA;
	else if (s == "dpchappfmncusraaccessdo") return DPCHAPPFMNCUSRAACCESSDO;
	else if (s == "dpchappfmncusrdetaildata") return DPCHAPPFMNCUSRDETAILDATA;
	else if (s == "dpchappfmncusrdetaildo") return DPCHAPPFMNCUSRDETAILDO;
	else if (s == "dpchappfmncusrdo") return DPCHAPPFMNCUSRDO;
	else if (s == "dpchappfmncusrlistdata") return DPCHAPPFMNCUSRLISTDATA;
	else if (s == "dpchappfmncusrlistdo") return DPCHAPPFMNCUSRLISTDO;
	else if (s == "dpchappfmncusrmnusergroupdata") return DPCHAPPFMNCUSRMNUSERGROUPDATA;
	else if (s == "dpchappfmncusrmnusergroupdo") return DPCHAPPFMNCUSRMNUSERGROUPDO;
	else if (s == "dpchappfmncusrrecdo") return DPCHAPPFMNCUSRRECDO;
	else if (s == "dpchapprootfmnclogin") return DPCHAPPROOTFMNCLOGIN;
	else if (s == "dpchengdlgfmncactnewdata") return DPCHENGDLGFMNCACTNEWDATA;
	else if (s == "dpchengdlgfmncfabexpfabdata") return DPCHENGDLGFMNCFABEXPFABDATA;
	else if (s == "dpchengdlgfmncfabimpfabdata") return DPCHENGDLGFMNCFABIMPFABDATA;
	else if (s == "dpchengdlgfmncfabnewdata") return DPCHENGDLGFMNCFABNEWDATA;
	else if (s == "dpchengdlgfmncnavloainidata") return DPCHENGDLGFMNCNAVLOAINIDATA;
	else if (s == "dpchengdlgfmncorgexporgdata") return DPCHENGDLGFMNCORGEXPORGDATA;
	else if (s == "dpchengdlgfmncorgimporgdata") return DPCHENGDLGFMNCORGIMPORGDATA;
	else if (s == "dpchengdlgfmncorgnewdata") return DPCHENGDLGFMNCORGNEWDATA;
	else if (s == "dpchengdlgfmncprjexpelbdata") return DPCHENGDLGFMNCPRJEXPELBDATA;
	else if (s == "dpchengdlgfmncprjimpelbdata") return DPCHENGDLGFMNCPRJIMPELBDATA;
	else if (s == "dpchengdlgfmncprjnewdata") return DPCHENGDLGFMNCPRJNEWDATA;
	else if (s == "dpchengdlgfmncrungenrepdata") return DPCHENGDLGFMNCRUNGENREPDATA;
	else if (s == "dpchengdlgfmncrunnewdata") return DPCHENGDLGFMNCRUNNEWDATA;
	else if (s == "dpchengdlgfmncsmpgenrepdata") return DPCHENGDLGFMNCSMPGENREPDATA;
	else if (s == "dpchengdlgfmncsmpnewdata") return DPCHENGDLGFMNCSMPNEWDATA;
	else if (s == "dpchengfmncack") return DPCHENGFMNCACK;
	else if (s == "dpchengfmncact1nstepdata") return DPCHENGFMNCACT1NSTEPDATA;
	else if (s == "dpchengfmncactdata") return DPCHENGFMNCACTDATA;
	else if (s == "dpchengfmncactdetaildata") return DPCHENGFMNCACTDETAILDATA;
	else if (s == "dpchengfmncactheadbardata") return DPCHENGFMNCACTHEADBARDATA;
	else if (s == "dpchengfmncactlistdata") return DPCHENGFMNCACTLISTDATA;
	else if (s == "dpchengfmncactrecdata") return DPCHENGFMNCACTRECDATA;
	else if (s == "dpchengfmncadrdata") return DPCHENGFMNCADRDATA;
	else if (s == "dpchengfmncadrdetaildata") return DPCHENGFMNCADRDETAILDATA;
	else if (s == "dpchengfmncadrheadbardata") return DPCHENGFMNCADRHEADBARDATA;
	else if (s == "dpchengfmncadrlistdata") return DPCHENGFMNCADRLISTDATA;
	else if (s == "dpchengfmncadrrecdata") return DPCHENGFMNCADRRECDATA;
	else if (s == "dpchengfmncalert") return DPCHENGFMNCALERT;
	else if (s == "dpchengfmncart1nsampledata") return DPCHENGFMNCART1NSAMPLEDATA;
	else if (s == "dpchengfmncart1nstockitemdata") return DPCHENGFMNCART1NSTOCKITEMDATA;
	else if (s == "dpchengfmncartdata") return DPCHENGFMNCARTDATA;
	else if (s == "dpchengfmncartdetaildata") return DPCHENGFMNCARTDETAILDATA;
	else if (s == "dpchengfmncartheadbardata") return DPCHENGFMNCARTHEADBARDATA;
	else if (s == "dpchengfmncartlistdata") return DPCHENGFMNCARTLISTDATA;
	else if (s == "dpchengfmncartmnorgdata") return DPCHENGFMNCARTMNORGDATA;
	else if (s == "dpchengfmncartrecdata") return DPCHENGFMNCARTRECDATA;
	else if (s == "dpchengfmncartref1nfiledata") return DPCHENGFMNCARTREF1NFILEDATA;
	else if (s == "dpchengfmncbilaposdata") return DPCHENGFMNCBILAPOSDATA;
	else if (s == "dpchengfmncbildata") return DPCHENGFMNCBILDATA;
	else if (s == "dpchengfmncbildetaildata") return DPCHENGFMNCBILDETAILDATA;
	else if (s == "dpchengfmncbilheadbardata") return DPCHENGFMNCBILHEADBARDATA;
	else if (s == "dpchengfmncbillistdata") return DPCHENGFMNCBILLISTDATA;
	else if (s == "dpchengfmncbilrecdata") return DPCHENGFMNCBILRECDATA;
	else if (s == "dpchengfmncconfirm") return DPCHENGFMNCCONFIRM;
	else if (s == "dpchengfmncfab1nfabprojectdata") return DPCHENGFMNCFAB1NFABPROJECTDATA;
	else if (s == "dpchengfmncfab1nfabuserdata") return DPCHENGFMNCFAB1NFABUSERDATA;
	else if (s == "dpchengfmncfabdata") return DPCHENGFMNCFABDATA;
	else if (s == "dpchengfmncfabdetaildata") return DPCHENGFMNCFABDETAILDATA;
	else if (s == "dpchengfmncfabfab1ntooldata") return DPCHENGFMNCFABFAB1NTOOLDATA;
	else if (s == "dpchengfmncfabheadbardata") return DPCHENGFMNCFABHEADBARDATA;
	else if (s == "dpchengfmncfablistdata") return DPCHENGFMNCFABLISTDATA;
	else if (s == "dpchengfmncfabmnrundata") return DPCHENGFMNCFABMNRUNDATA;
	else if (s == "dpchengfmncfabrecdata") return DPCHENGFMNCFABRECDATA;
	else if (s == "dpchengfmncfildata") return DPCHENGFMNCFILDATA;
	else if (s == "dpchengfmncfildetaildata") return DPCHENGFMNCFILDETAILDATA;
	else if (s == "dpchengfmncfilheadbardata") return DPCHENGFMNCFILHEADBARDATA;
	else if (s == "dpchengfmncfillistdata") return DPCHENGFMNCFILLISTDATA;
	else if (s == "dpchengfmncfilmnsampledata") return DPCHENGFMNCFILMNSAMPLEDATA;
	else if (s == "dpchengfmncfilmnstepdata") return DPCHENGFMNCFILMNSTEPDATA;
	else if (s == "dpchengfmncfilrecdata") return DPCHENGFMNCFILRECDATA;
	else if (s == "dpchengfmncfpj1nbilldata") return DPCHENGFMNCFPJ1NBILLDATA;
	else if (s == "dpchengfmncfpjdata") return DPCHENGFMNCFPJDATA;
	else if (s == "dpchengfmncfpjdetaildata") return DPCHENGFMNCFPJDETAILDATA;
	else if (s == "dpchengfmncfpjheadbardata") return DPCHENGFMNCFPJHEADBARDATA;
	else if (s == "dpchengfmncfpjlistdata") return DPCHENGFMNCFPJLISTDATA;
	else if (s == "dpchengfmncfpjmnfabuserdata") return DPCHENGFMNCFPJMNFABUSERDATA;
	else if (s == "dpchengfmncfpjrecdata") return DPCHENGFMNCFPJRECDATA;
	else if (s == "dpchengfmncfusdata") return DPCHENGFMNCFUSDATA;
	else if (s == "dpchengfmncfusdetaildata") return DPCHENGFMNCFUSDETAILDATA;
	else if (s == "dpchengfmncfusheadbardata") return DPCHENGFMNCFUSHEADBARDATA;
	else if (s == "dpchengfmncfuslistdata") return DPCHENGFMNCFUSLISTDATA;
	else if (s == "dpchengfmncfusmnfabprojectdata") return DPCHENGFMNCFUSMNFABPROJECTDATA;
	else if (s == "dpchengfmncfusmntooldata") return DPCHENGFMNCFUSMNTOOLDATA;
	else if (s == "dpchengfmncfusrecdata") return DPCHENGFMNCFUSRECDATA;
	else if (s == "dpchengfmncnavadmindata") return DPCHENGFMNCNAVADMINDATA;
	else if (s == "dpchengfmncnavdata") return DPCHENGFMNCNAVDATA;
	else if (s == "dpchengfmncnavfabmgmtdata") return DPCHENGFMNCNAVFABMGMTDATA;
	else if (s == "dpchengfmncnavheadbardata") return DPCHENGFMNCNAVHEADBARDATA;
	else if (s == "dpchengfmncnavlabbookdata") return DPCHENGFMNCNAVLABBOOKDATA;
	else if (s == "dpchengfmncnavpredata") return DPCHENGFMNCNAVPREDATA;
	else if (s == "dpchengfmncnavsupplydata") return DPCHENGFMNCNAVSUPPLYDATA;
	else if (s == "dpchengfmncorg1narticledata") return DPCHENGFMNCORG1NARTICLEDATA;
	else if (s == "dpchengfmncorg1nstockitemdata") return DPCHENGFMNCORG1NSTOCKITEMDATA;
	else if (s == "dpchengfmncorgadetaildata") return DPCHENGFMNCORGADETAILDATA;
	else if (s == "dpchengfmncorgbio1nfabprojectdata") return DPCHENGFMNCORGBIO1NFABPROJECTDATA;
	else if (s == "dpchengfmncorgdata") return DPCHENGFMNCORGDATA;
	else if (s == "dpchengfmncorgdetaildata") return DPCHENGFMNCORGDETAILDATA;
	else if (s == "dpchengfmncorgheadbardata") return DPCHENGFMNCORGHEADBARDATA;
	else if (s == "dpchengfmncorghk1naddressdata") return DPCHENGFMNCORGHK1NADDRESSDATA;
	else if (s == "dpchengfmncorgkstocklcndata") return DPCHENGFMNCORGKSTOCKLCNDATA;
	else if (s == "dpchengfmncorglistdata") return DPCHENGFMNCORGLISTDATA;
	else if (s == "dpchengfmncorgmnarticledata") return DPCHENGFMNCORGMNARTICLEDATA;
	else if (s == "dpchengfmncorgmnf1ntooldata") return DPCHENGFMNCORGMNF1NTOOLDATA;
	else if (s == "dpchengfmncorgmnpersondata") return DPCHENGFMNCORGMNPERSONDATA;
	else if (s == "dpchengfmncorgpco1npurchorderdata") return DPCHENGFMNCORGPCO1NPURCHORDERDATA;
	else if (s == "dpchengfmncorgrecdata") return DPCHENGFMNCORGRECDATA;
	else if (s == "dpchengfmncorgspl1npurchorderdata") return DPCHENGFMNCORGSPL1NPURCHORDERDATA;
	else if (s == "dpchengfmncorgsup1norgdata") return DPCHENGFMNCORGSUP1NORGDATA;
	else if (s == "dpchengfmncorgsvcmntooldata") return DPCHENGFMNCORGSVCMNTOOLDATA;
	else if (s == "dpchengfmncpcoaposdata") return DPCHENGFMNCPCOAPOSDATA;
	else if (s == "dpchengfmncpcodata") return DPCHENGFMNCPCODATA;
	else if (s == "dpchengfmncpcodetaildata") return DPCHENGFMNCPCODETAILDATA;
	else if (s == "dpchengfmncpcoheadbardata") return DPCHENGFMNCPCOHEADBARDATA;
	else if (s == "dpchengfmncpcolistdata") return DPCHENGFMNCPCOLISTDATA;
	else if (s == "dpchengfmncpcorecdata") return DPCHENGFMNCPCORECDATA;
	else if (s == "dpchengfmncprj1nrundata") return DPCHENGFMNCPRJ1NRUNDATA;
	else if (s == "dpchengfmncprjdata") return DPCHENGFMNCPRJDATA;
	else if (s == "dpchengfmncprjdetaildata") return DPCHENGFMNCPRJDETAILDATA;
	else if (s == "dpchengfmncprjheadbardata") return DPCHENGFMNCPRJHEADBARDATA;
	else if (s == "dpchengfmncprjlistdata") return DPCHENGFMNCPRJLISTDATA;
	else if (s == "dpchengfmncprjrecdata") return DPCHENGFMNCPRJRECDATA;
	else if (s == "dpchengfmncprsadetaildata") return DPCHENGFMNCPRSADETAILDATA;
	else if (s == "dpchengfmncprsdata") return DPCHENGFMNCPRSDATA;
	else if (s == "dpchengfmncprsdetaildata") return DPCHENGFMNCPRSDETAILDATA;
	else if (s == "dpchengfmncprsheadbardata") return DPCHENGFMNCPRSHEADBARDATA;
	else if (s == "dpchengfmncprshk1naddressdata") return DPCHENGFMNCPRSHK1NADDRESSDATA;
	else if (s == "dpchengfmncprslistdata") return DPCHENGFMNCPRSLISTDATA;
	else if (s == "dpchengfmncprsmnorgdata") return DPCHENGFMNCPRSMNORGDATA;
	else if (s == "dpchengfmncprsmnrundata") return DPCHENGFMNCPRSMNRUNDATA;
	else if (s == "dpchengfmncprsrecdata") return DPCHENGFMNCPRSRECDATA;
	else if (s == "dpchengfmncrundata") return DPCHENGFMNCRUNDATA;
	else if (s == "dpchengfmncrundetaildata") return DPCHENGFMNCRUNDETAILDATA;
	else if (s == "dpchengfmncrunheadbardata") return DPCHENGFMNCRUNHEADBARDATA;
	else if (s == "dpchengfmncrunlistdata") return DPCHENGFMNCRUNLISTDATA;
	else if (s == "dpchengfmncrunmnfabdata") return DPCHENGFMNCRUNMNFABDATA;
	else if (s == "dpchengfmncrunmnpersondata") return DPCHENGFMNCRUNMNPERSONDATA;
	else if (s == "dpchengfmncrunmnsampledata") return DPCHENGFMNCRUNMNSAMPLEDATA;
	else if (s == "dpchengfmncrunrecdata") return DPCHENGFMNCRUNRECDATA;
	else if (s == "dpchengfmncrunref1nfiledata") return DPCHENGFMNCRUNREF1NFILEDATA;
	else if (s == "dpchengfmncrunrun1nactivitydata") return DPCHENGFMNCRUNRUN1NACTIVITYDATA;
	else if (s == "dpchengfmncsepapardata") return DPCHENGFMNCSEPAPARDATA;
	else if (s == "dpchengfmncsepdata") return DPCHENGFMNCSEPDATA;
	else if (s == "dpchengfmncsepdetaildata") return DPCHENGFMNCSEPDETAILDATA;
	else if (s == "dpchengfmncsepheadbardata") return DPCHENGFMNCSEPHEADBARDATA;
	else if (s == "dpchengfmncseplistdata") return DPCHENGFMNCSEPLISTDATA;
	else if (s == "dpchengfmncsepmnfiledata") return DPCHENGFMNCSEPMNFILEDATA;
	else if (s == "dpchengfmncsepmnsampledata") return DPCHENGFMNCSEPMNSAMPLEDATA;
	else if (s == "dpchengfmncseprecdata") return DPCHENGFMNCSEPRECDATA;
	else if (s == "dpchengfmncsepref1nfiledata") return DPCHENGFMNCSEPREF1NFILEDATA;
	else if (s == "dpchengfmncskidata") return DPCHENGFMNCSKIDATA;
	else if (s == "dpchengfmncskidetaildata") return DPCHENGFMNCSKIDETAILDATA;
	else if (s == "dpchengfmncskiheadbardata") return DPCHENGFMNCSKIHEADBARDATA;
	else if (s == "dpchengfmncskilistdata") return DPCHENGFMNCSKILISTDATA;
	else if (s == "dpchengfmncskirecdata") return DPCHENGFMNCSKIRECDATA;
	else if (s == "dpchengfmncsmpapardata") return DPCHENGFMNCSMPAPARDATA;
	else if (s == "dpchengfmncsmpdata") return DPCHENGFMNCSMPDATA;
	else if (s == "dpchengfmncsmpdetaildata") return DPCHENGFMNCSMPDETAILDATA;
	else if (s == "dpchengfmncsmpheadbardata") return DPCHENGFMNCSMPHEADBARDATA;
	else if (s == "dpchengfmncsmplistdata") return DPCHENGFMNCSMPLISTDATA;
	else if (s == "dpchengfmncsmpmnfiledata") return DPCHENGFMNCSMPMNFILEDATA;
	else if (s == "dpchengfmncsmpmnrundata") return DPCHENGFMNCSMPMNRUNDATA;
	else if (s == "dpchengfmncsmpmnstepdata") return DPCHENGFMNCSMPMNSTEPDATA;
	else if (s == "dpchengfmncsmprecdata") return DPCHENGFMNCSMPRECDATA;
	else if (s == "dpchengfmncsmpref1nfiledata") return DPCHENGFMNCSMPREF1NFILEDATA;
	else if (s == "dpchengfmncsmpsup1nsampledata") return DPCHENGFMNCSMPSUP1NSAMPLEDATA;
	else if (s == "dpchengfmncstpapardata") return DPCHENGFMNCSTPAPARDATA;
	else if (s == "dpchengfmncstpdata") return DPCHENGFMNCSTPDATA;
	else if (s == "dpchengfmncstpdetaildata") return DPCHENGFMNCSTPDETAILDATA;
	else if (s == "dpchengfmncstpheadbardata") return DPCHENGFMNCSTPHEADBARDATA;
	else if (s == "dpchengfmncstpksteppardata") return DPCHENGFMNCSTPKSTEPPARDATA;
	else if (s == "dpchengfmncstplistdata") return DPCHENGFMNCSTPLISTDATA;
	else if (s == "dpchengfmncstpmnfiledata") return DPCHENGFMNCSTPMNFILEDATA;
	else if (s == "dpchengfmncstprecdata") return DPCHENGFMNCSTPRECDATA;
	else if (s == "dpchengfmncstpref1nfiledata") return DPCHENGFMNCSTPREF1NFILEDATA;
	else if (s == "dpchengfmncstptpl1nstepdata") return DPCHENGFMNCSTPTPL1NSTEPDATA;
	else if (s == "dpchengfmncsuspend") return DPCHENGFMNCSUSPEND;
	else if (s == "dpchengfmnctol1narticledata") return DPCHENGFMNCTOL1NARTICLEDATA;
	else if (s == "dpchengfmnctolaavldata") return DPCHENGFMNCTOLAAVLDATA;
	else if (s == "dpchengfmnctolachardata") return DPCHENGFMNCTOLACHARDATA;
	else if (s == "dpchengfmnctolaresdata") return DPCHENGFMNCTOLARESDATA;
	else if (s == "dpchengfmnctolautildata") return DPCHENGFMNCTOLAUTILDATA;
	else if (s == "dpchengfmnctoldata") return DPCHENGFMNCTOLDATA;
	else if (s == "dpchengfmnctoldetaildata") return DPCHENGFMNCTOLDETAILDATA;
	else if (s == "dpchengfmnctolheadbardata") return DPCHENGFMNCTOLHEADBARDATA;
	else if (s == "dpchengfmnctolksteppardata") return DPCHENGFMNCTOLKSTEPPARDATA;
	else if (s == "dpchengfmnctolktoolchardata") return DPCHENGFMNCTOLKTOOLCHARDATA;
	else if (s == "dpchengfmnctollistdata") return DPCHENGFMNCTOLLISTDATA;
	else if (s == "dpchengfmnctolmnfabuserdata") return DPCHENGFMNCTOLMNFABUSERDATA;
	else if (s == "dpchengfmnctolmntooltypedata") return DPCHENGFMNCTOLMNTOOLTYPEDATA;
	else if (s == "dpchengfmnctolrecdata") return DPCHENGFMNCTOLRECDATA;
	else if (s == "dpchengfmnctolref1nfiledata") return DPCHENGFMNCTOLREF1NFILEDATA;
	else if (s == "dpchengfmnctolrlv1nstepdata") return DPCHENGFMNCTOLRLV1NSTEPDATA;
	else if (s == "dpchengfmnctolsvcmnorgdata") return DPCHENGFMNCTOLSVCMNORGDATA;
	else if (s == "dpchengfmncttydata") return DPCHENGFMNCTTYDATA;
	else if (s == "dpchengfmncttydetaildata") return DPCHENGFMNCTTYDETAILDATA;
	else if (s == "dpchengfmncttyheadbardata") return DPCHENGFMNCTTYHEADBARDATA;
	else if (s == "dpchengfmncttyksteppardata") return DPCHENGFMNCTTYKSTEPPARDATA;
	else if (s == "dpchengfmncttyktoolchardata") return DPCHENGFMNCTTYKTOOLCHARDATA;
	else if (s == "dpchengfmncttylistdata") return DPCHENGFMNCTTYLISTDATA;
	else if (s == "dpchengfmncttymntooldata") return DPCHENGFMNCTTYMNTOOLDATA;
	else if (s == "dpchengfmncttyrecdata") return DPCHENGFMNCTTYRECDATA;
	else if (s == "dpchengfmncttyrlv1nstepdata") return DPCHENGFMNCTTYRLV1NSTEPDATA;
	else if (s == "dpchengfmncttysup1ntooltypedata") return DPCHENGFMNCTTYSUP1NTOOLTYPEDATA;
	else if (s == "dpchengfmncusgaaccessdata") return DPCHENGFMNCUSGAACCESSDATA;
	else if (s == "dpchengfmncusgdata") return DPCHENGFMNCUSGDATA;
	else if (s == "dpchengfmncusgdetaildata") return DPCHENGFMNCUSGDETAILDATA;
	else if (s == "dpchengfmncusgheadbardata") return DPCHENGFMNCUSGHEADBARDATA;
	else if (s == "dpchengfmncusglistdata") return DPCHENGFMNCUSGLISTDATA;
	else if (s == "dpchengfmncusgmnuserdata") return DPCHENGFMNCUSGMNUSERDATA;
	else if (s == "dpchengfmncusgrecdata") return DPCHENGFMNCUSGRECDATA;
	else if (s == "dpchengfmncusr1nsessiondata") return DPCHENGFMNCUSR1NSESSIONDATA;
	else if (s == "dpchengfmncusraaccessdata") return DPCHENGFMNCUSRAACCESSDATA;
	else if (s == "dpchengfmncusrdata") return DPCHENGFMNCUSRDATA;
	else if (s == "dpchengfmncusrdetaildata") return DPCHENGFMNCUSRDETAILDATA;
	else if (s == "dpchengfmncusrheadbardata") return DPCHENGFMNCUSRHEADBARDATA;
	else if (s == "dpchengfmncusrlistdata") return DPCHENGFMNCUSRLISTDATA;
	else if (s == "dpchengfmncusrmnusergroupdata") return DPCHENGFMNCUSRMNUSERGROUPDATA;
	else if (s == "dpchengfmncusrrecdata") return DPCHENGFMNCUSRRECDATA;
	else if (s == "dpchengsessfmncdata") return DPCHENGSESSFMNCDATA;
	else if (s == "dpchfmncdack") return DPCHFMNCDACK;
	else if (s == "dpchfmncdquit") return DPCHFMNCDQUIT;
	else if (s == "dpchfmncdreg") return DPCHFMNCDREG;
	else if (s == "dpchfmncopdreg") return DPCHFMNCOPDREG;
	else if (s == "dpchfmncopdunreg") return DPCHFMNCOPDUNREG;
	else if (s == "dpchinvfmnc") return DPCHINVFMNC;
	else if (s == "dpchretfmnc") return DPCHRETFMNC;

	return(0);
};

string VecFmncVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHAPPDLGFMNCACTNEWDATA) return("DpchAppDlgFmncActNewData");
	else if (ix == DPCHAPPDLGFMNCACTNEWDO) return("DpchAppDlgFmncActNewDo");
	else if (ix == DPCHAPPDLGFMNCFABEXPFABDATA) return("DpchAppDlgFmncFabExpfabData");
	else if (ix == DPCHAPPDLGFMNCFABEXPFABDO) return("DpchAppDlgFmncFabExpfabDo");
	else if (ix == DPCHAPPDLGFMNCFABIMPFABDATA) return("DpchAppDlgFmncFabImpfabData");
	else if (ix == DPCHAPPDLGFMNCFABIMPFABDO) return("DpchAppDlgFmncFabImpfabDo");
	else if (ix == DPCHAPPDLGFMNCFABNEWDATA) return("DpchAppDlgFmncFabNewData");
	else if (ix == DPCHAPPDLGFMNCFABNEWDO) return("DpchAppDlgFmncFabNewDo");
	else if (ix == DPCHAPPDLGFMNCNAVLOAINIDATA) return("DpchAppDlgFmncNavLoainiData");
	else if (ix == DPCHAPPDLGFMNCNAVLOAINIDO) return("DpchAppDlgFmncNavLoainiDo");
	else if (ix == DPCHAPPDLGFMNCORGEXPORGDATA) return("DpchAppDlgFmncOrgExporgData");
	else if (ix == DPCHAPPDLGFMNCORGEXPORGDO) return("DpchAppDlgFmncOrgExporgDo");
	else if (ix == DPCHAPPDLGFMNCORGIMPORGDATA) return("DpchAppDlgFmncOrgImporgData");
	else if (ix == DPCHAPPDLGFMNCORGIMPORGDO) return("DpchAppDlgFmncOrgImporgDo");
	else if (ix == DPCHAPPDLGFMNCORGNEWDATA) return("DpchAppDlgFmncOrgNewData");
	else if (ix == DPCHAPPDLGFMNCORGNEWDO) return("DpchAppDlgFmncOrgNewDo");
	else if (ix == DPCHAPPDLGFMNCPRJEXPELBDATA) return("DpchAppDlgFmncPrjExpelbData");
	else if (ix == DPCHAPPDLGFMNCPRJEXPELBDO) return("DpchAppDlgFmncPrjExpelbDo");
	else if (ix == DPCHAPPDLGFMNCPRJIMPELBDATA) return("DpchAppDlgFmncPrjImpelbData");
	else if (ix == DPCHAPPDLGFMNCPRJIMPELBDO) return("DpchAppDlgFmncPrjImpelbDo");
	else if (ix == DPCHAPPDLGFMNCPRJNEWDATA) return("DpchAppDlgFmncPrjNewData");
	else if (ix == DPCHAPPDLGFMNCPRJNEWDO) return("DpchAppDlgFmncPrjNewDo");
	else if (ix == DPCHAPPDLGFMNCRUNGENREPDATA) return("DpchAppDlgFmncRunGenrepData");
	else if (ix == DPCHAPPDLGFMNCRUNGENREPDO) return("DpchAppDlgFmncRunGenrepDo");
	else if (ix == DPCHAPPDLGFMNCRUNNEWDATA) return("DpchAppDlgFmncRunNewData");
	else if (ix == DPCHAPPDLGFMNCRUNNEWDO) return("DpchAppDlgFmncRunNewDo");
	else if (ix == DPCHAPPDLGFMNCSMPGENREPDATA) return("DpchAppDlgFmncSmpGenrepData");
	else if (ix == DPCHAPPDLGFMNCSMPGENREPDO) return("DpchAppDlgFmncSmpGenrepDo");
	else if (ix == DPCHAPPDLGFMNCSMPNEWDATA) return("DpchAppDlgFmncSmpNewData");
	else if (ix == DPCHAPPDLGFMNCSMPNEWDO) return("DpchAppDlgFmncSmpNewDo");
	else if (ix == DPCHAPPFMNCACT1NSTEPDATA) return("DpchAppFmncAct1NStepData");
	else if (ix == DPCHAPPFMNCACT1NSTEPDO) return("DpchAppFmncAct1NStepDo");
	else if (ix == DPCHAPPFMNCACTDETAILDATA) return("DpchAppFmncActDetailData");
	else if (ix == DPCHAPPFMNCACTDETAILDO) return("DpchAppFmncActDetailDo");
	else if (ix == DPCHAPPFMNCACTDO) return("DpchAppFmncActDo");
	else if (ix == DPCHAPPFMNCACTLISTDATA) return("DpchAppFmncActListData");
	else if (ix == DPCHAPPFMNCACTLISTDO) return("DpchAppFmncActListDo");
	else if (ix == DPCHAPPFMNCACTRECDO) return("DpchAppFmncActRecDo");
	else if (ix == DPCHAPPFMNCADRDETAILDATA) return("DpchAppFmncAdrDetailData");
	else if (ix == DPCHAPPFMNCADRDETAILDO) return("DpchAppFmncAdrDetailDo");
	else if (ix == DPCHAPPFMNCADRDO) return("DpchAppFmncAdrDo");
	else if (ix == DPCHAPPFMNCADRLISTDATA) return("DpchAppFmncAdrListData");
	else if (ix == DPCHAPPFMNCADRLISTDO) return("DpchAppFmncAdrListDo");
	else if (ix == DPCHAPPFMNCADRRECDO) return("DpchAppFmncAdrRecDo");
	else if (ix == DPCHAPPFMNCALERT) return("DpchAppFmncAlert");
	else if (ix == DPCHAPPFMNCART1NSAMPLEDATA) return("DpchAppFmncArt1NSampleData");
	else if (ix == DPCHAPPFMNCART1NSAMPLEDO) return("DpchAppFmncArt1NSampleDo");
	else if (ix == DPCHAPPFMNCART1NSTOCKITEMDATA) return("DpchAppFmncArt1NStockitemData");
	else if (ix == DPCHAPPFMNCART1NSTOCKITEMDO) return("DpchAppFmncArt1NStockitemDo");
	else if (ix == DPCHAPPFMNCARTDETAILDATA) return("DpchAppFmncArtDetailData");
	else if (ix == DPCHAPPFMNCARTDETAILDO) return("DpchAppFmncArtDetailDo");
	else if (ix == DPCHAPPFMNCARTDO) return("DpchAppFmncArtDo");
	else if (ix == DPCHAPPFMNCARTLISTDATA) return("DpchAppFmncArtListData");
	else if (ix == DPCHAPPFMNCARTLISTDO) return("DpchAppFmncArtListDo");
	else if (ix == DPCHAPPFMNCARTMNORGDATA) return("DpchAppFmncArtMNOrgData");
	else if (ix == DPCHAPPFMNCARTMNORGDO) return("DpchAppFmncArtMNOrgDo");
	else if (ix == DPCHAPPFMNCARTRECDO) return("DpchAppFmncArtRecDo");
	else if (ix == DPCHAPPFMNCARTREF1NFILEDATA) return("DpchAppFmncArtRef1NFileData");
	else if (ix == DPCHAPPFMNCARTREF1NFILEDO) return("DpchAppFmncArtRef1NFileDo");
	else if (ix == DPCHAPPFMNCBILAPOSDATA) return("DpchAppFmncBilAPosData");
	else if (ix == DPCHAPPFMNCBILAPOSDO) return("DpchAppFmncBilAPosDo");
	else if (ix == DPCHAPPFMNCBILDETAILDATA) return("DpchAppFmncBilDetailData");
	else if (ix == DPCHAPPFMNCBILDETAILDO) return("DpchAppFmncBilDetailDo");
	else if (ix == DPCHAPPFMNCBILDO) return("DpchAppFmncBilDo");
	else if (ix == DPCHAPPFMNCBILLISTDATA) return("DpchAppFmncBilListData");
	else if (ix == DPCHAPPFMNCBILLISTDO) return("DpchAppFmncBilListDo");
	else if (ix == DPCHAPPFMNCBILRECDO) return("DpchAppFmncBilRecDo");
	else if (ix == DPCHAPPFMNCFAB1NFABPROJECTDATA) return("DpchAppFmncFab1NFabprojectData");
	else if (ix == DPCHAPPFMNCFAB1NFABPROJECTDO) return("DpchAppFmncFab1NFabprojectDo");
	else if (ix == DPCHAPPFMNCFAB1NFABUSERDATA) return("DpchAppFmncFab1NFabuserData");
	else if (ix == DPCHAPPFMNCFAB1NFABUSERDO) return("DpchAppFmncFab1NFabuserDo");
	else if (ix == DPCHAPPFMNCFABDETAILDO) return("DpchAppFmncFabDetailDo");
	else if (ix == DPCHAPPFMNCFABDO) return("DpchAppFmncFabDo");
	else if (ix == DPCHAPPFMNCFABFAB1NTOOLDATA) return("DpchAppFmncFabFab1NToolData");
	else if (ix == DPCHAPPFMNCFABFAB1NTOOLDO) return("DpchAppFmncFabFab1NToolDo");
	else if (ix == DPCHAPPFMNCFABLISTDATA) return("DpchAppFmncFabListData");
	else if (ix == DPCHAPPFMNCFABLISTDO) return("DpchAppFmncFabListDo");
	else if (ix == DPCHAPPFMNCFABMNRUNDATA) return("DpchAppFmncFabMNRunData");
	else if (ix == DPCHAPPFMNCFABMNRUNDO) return("DpchAppFmncFabMNRunDo");
	else if (ix == DPCHAPPFMNCFABRECDO) return("DpchAppFmncFabRecDo");
	else if (ix == DPCHAPPFMNCFILDETAILDATA) return("DpchAppFmncFilDetailData");
	else if (ix == DPCHAPPFMNCFILDETAILDO) return("DpchAppFmncFilDetailDo");
	else if (ix == DPCHAPPFMNCFILDO) return("DpchAppFmncFilDo");
	else if (ix == DPCHAPPFMNCFILLISTDATA) return("DpchAppFmncFilListData");
	else if (ix == DPCHAPPFMNCFILLISTDO) return("DpchAppFmncFilListDo");
	else if (ix == DPCHAPPFMNCFILMNSAMPLEDATA) return("DpchAppFmncFilMNSampleData");
	else if (ix == DPCHAPPFMNCFILMNSAMPLEDO) return("DpchAppFmncFilMNSampleDo");
	else if (ix == DPCHAPPFMNCFILMNSTEPDATA) return("DpchAppFmncFilMNStepData");
	else if (ix == DPCHAPPFMNCFILMNSTEPDO) return("DpchAppFmncFilMNStepDo");
	else if (ix == DPCHAPPFMNCFILRECDO) return("DpchAppFmncFilRecDo");
	else if (ix == DPCHAPPFMNCFPJ1NBILLDATA) return("DpchAppFmncFpj1NBillData");
	else if (ix == DPCHAPPFMNCFPJ1NBILLDO) return("DpchAppFmncFpj1NBillDo");
	else if (ix == DPCHAPPFMNCFPJDETAILDATA) return("DpchAppFmncFpjDetailData");
	else if (ix == DPCHAPPFMNCFPJDETAILDO) return("DpchAppFmncFpjDetailDo");
	else if (ix == DPCHAPPFMNCFPJDO) return("DpchAppFmncFpjDo");
	else if (ix == DPCHAPPFMNCFPJLISTDATA) return("DpchAppFmncFpjListData");
	else if (ix == DPCHAPPFMNCFPJLISTDO) return("DpchAppFmncFpjListDo");
	else if (ix == DPCHAPPFMNCFPJMNFABUSERDATA) return("DpchAppFmncFpjMNFabuserData");
	else if (ix == DPCHAPPFMNCFPJMNFABUSERDO) return("DpchAppFmncFpjMNFabuserDo");
	else if (ix == DPCHAPPFMNCFPJRECDO) return("DpchAppFmncFpjRecDo");
	else if (ix == DPCHAPPFMNCFUSDETAILDATA) return("DpchAppFmncFusDetailData");
	else if (ix == DPCHAPPFMNCFUSDETAILDO) return("DpchAppFmncFusDetailDo");
	else if (ix == DPCHAPPFMNCFUSDO) return("DpchAppFmncFusDo");
	else if (ix == DPCHAPPFMNCFUSLISTDATA) return("DpchAppFmncFusListData");
	else if (ix == DPCHAPPFMNCFUSLISTDO) return("DpchAppFmncFusListDo");
	else if (ix == DPCHAPPFMNCFUSMNFABPROJECTDATA) return("DpchAppFmncFusMNFabprojectData");
	else if (ix == DPCHAPPFMNCFUSMNFABPROJECTDO) return("DpchAppFmncFusMNFabprojectDo");
	else if (ix == DPCHAPPFMNCFUSMNTOOLDATA) return("DpchAppFmncFusMNToolData");
	else if (ix == DPCHAPPFMNCFUSMNTOOLDO) return("DpchAppFmncFusMNToolDo");
	else if (ix == DPCHAPPFMNCFUSRECDO) return("DpchAppFmncFusRecDo");
	else if (ix == DPCHAPPFMNCINIT) return("DpchAppFmncInit");
	else if (ix == DPCHAPPFMNCNAVADMINDATA) return("DpchAppFmncNavAdminData");
	else if (ix == DPCHAPPFMNCNAVADMINDO) return("DpchAppFmncNavAdminDo");
	else if (ix == DPCHAPPFMNCNAVDO) return("DpchAppFmncNavDo");
	else if (ix == DPCHAPPFMNCNAVFABMGMTDATA) return("DpchAppFmncNavFabmgmtData");
	else if (ix == DPCHAPPFMNCNAVFABMGMTDO) return("DpchAppFmncNavFabmgmtDo");
	else if (ix == DPCHAPPFMNCNAVLABBOOKDATA) return("DpchAppFmncNavLabbookData");
	else if (ix == DPCHAPPFMNCNAVLABBOOKDO) return("DpchAppFmncNavLabbookDo");
	else if (ix == DPCHAPPFMNCNAVPREDO) return("DpchAppFmncNavPreDo");
	else if (ix == DPCHAPPFMNCNAVSUPPLYDATA) return("DpchAppFmncNavSupplyData");
	else if (ix == DPCHAPPFMNCNAVSUPPLYDO) return("DpchAppFmncNavSupplyDo");
	else if (ix == DPCHAPPFMNCORG1NARTICLEDATA) return("DpchAppFmncOrg1NArticleData");
	else if (ix == DPCHAPPFMNCORG1NARTICLEDO) return("DpchAppFmncOrg1NArticleDo");
	else if (ix == DPCHAPPFMNCORG1NSTOCKITEMDATA) return("DpchAppFmncOrg1NStockitemData");
	else if (ix == DPCHAPPFMNCORG1NSTOCKITEMDO) return("DpchAppFmncOrg1NStockitemDo");
	else if (ix == DPCHAPPFMNCORGADETAILDATA) return("DpchAppFmncOrgADetailData");
	else if (ix == DPCHAPPFMNCORGADETAILDO) return("DpchAppFmncOrgADetailDo");
	else if (ix == DPCHAPPFMNCORGBIO1NFABPROJECTDATA) return("DpchAppFmncOrgBio1NFabprojectData");
	else if (ix == DPCHAPPFMNCORGBIO1NFABPROJECTDO) return("DpchAppFmncOrgBio1NFabprojectDo");
	else if (ix == DPCHAPPFMNCORGDETAILDATA) return("DpchAppFmncOrgDetailData");
	else if (ix == DPCHAPPFMNCORGDETAILDO) return("DpchAppFmncOrgDetailDo");
	else if (ix == DPCHAPPFMNCORGDO) return("DpchAppFmncOrgDo");
	else if (ix == DPCHAPPFMNCORGHK1NADDRESSDATA) return("DpchAppFmncOrgHk1NAddressData");
	else if (ix == DPCHAPPFMNCORGHK1NADDRESSDO) return("DpchAppFmncOrgHk1NAddressDo");
	else if (ix == DPCHAPPFMNCORGKSTOCKLCNDATA) return("DpchAppFmncOrgKStocklcnData");
	else if (ix == DPCHAPPFMNCORGKSTOCKLCNDO) return("DpchAppFmncOrgKStocklcnDo");
	else if (ix == DPCHAPPFMNCORGLISTDATA) return("DpchAppFmncOrgListData");
	else if (ix == DPCHAPPFMNCORGLISTDO) return("DpchAppFmncOrgListDo");
	else if (ix == DPCHAPPFMNCORGMNARTICLEDATA) return("DpchAppFmncOrgMNArticleData");
	else if (ix == DPCHAPPFMNCORGMNARTICLEDO) return("DpchAppFmncOrgMNArticleDo");
	else if (ix == DPCHAPPFMNCORGMNF1NTOOLDATA) return("DpchAppFmncOrgMnf1NToolData");
	else if (ix == DPCHAPPFMNCORGMNF1NTOOLDO) return("DpchAppFmncOrgMnf1NToolDo");
	else if (ix == DPCHAPPFMNCORGMNPERSONDATA) return("DpchAppFmncOrgMNPersonData");
	else if (ix == DPCHAPPFMNCORGMNPERSONDO) return("DpchAppFmncOrgMNPersonDo");
	else if (ix == DPCHAPPFMNCORGPCO1NPURCHORDERDATA) return("DpchAppFmncOrgPco1NPurchorderData");
	else if (ix == DPCHAPPFMNCORGPCO1NPURCHORDERDO) return("DpchAppFmncOrgPco1NPurchorderDo");
	else if (ix == DPCHAPPFMNCORGRECDO) return("DpchAppFmncOrgRecDo");
	else if (ix == DPCHAPPFMNCORGSPL1NPURCHORDERDATA) return("DpchAppFmncOrgSpl1NPurchorderData");
	else if (ix == DPCHAPPFMNCORGSPL1NPURCHORDERDO) return("DpchAppFmncOrgSpl1NPurchorderDo");
	else if (ix == DPCHAPPFMNCORGSUP1NORGDATA) return("DpchAppFmncOrgSup1NOrgData");
	else if (ix == DPCHAPPFMNCORGSUP1NORGDO) return("DpchAppFmncOrgSup1NOrgDo");
	else if (ix == DPCHAPPFMNCORGSVCMNTOOLDATA) return("DpchAppFmncOrgSvcMNToolData");
	else if (ix == DPCHAPPFMNCORGSVCMNTOOLDO) return("DpchAppFmncOrgSvcMNToolDo");
	else if (ix == DPCHAPPFMNCPCOAPOSDATA) return("DpchAppFmncPcoAPosData");
	else if (ix == DPCHAPPFMNCPCOAPOSDO) return("DpchAppFmncPcoAPosDo");
	else if (ix == DPCHAPPFMNCPCODETAILDATA) return("DpchAppFmncPcoDetailData");
	else if (ix == DPCHAPPFMNCPCODETAILDO) return("DpchAppFmncPcoDetailDo");
	else if (ix == DPCHAPPFMNCPCODO) return("DpchAppFmncPcoDo");
	else if (ix == DPCHAPPFMNCPCOLISTDATA) return("DpchAppFmncPcoListData");
	else if (ix == DPCHAPPFMNCPCOLISTDO) return("DpchAppFmncPcoListDo");
	else if (ix == DPCHAPPFMNCPCORECDO) return("DpchAppFmncPcoRecDo");
	else if (ix == DPCHAPPFMNCPRJ1NRUNDATA) return("DpchAppFmncPrj1NRunData");
	else if (ix == DPCHAPPFMNCPRJ1NRUNDO) return("DpchAppFmncPrj1NRunDo");
	else if (ix == DPCHAPPFMNCPRJDETAILDATA) return("DpchAppFmncPrjDetailData");
	else if (ix == DPCHAPPFMNCPRJDETAILDO) return("DpchAppFmncPrjDetailDo");
	else if (ix == DPCHAPPFMNCPRJDO) return("DpchAppFmncPrjDo");
	else if (ix == DPCHAPPFMNCPRJLISTDATA) return("DpchAppFmncPrjListData");
	else if (ix == DPCHAPPFMNCPRJLISTDO) return("DpchAppFmncPrjListDo");
	else if (ix == DPCHAPPFMNCPRJRECDO) return("DpchAppFmncPrjRecDo");
	else if (ix == DPCHAPPFMNCPRSADETAILDATA) return("DpchAppFmncPrsADetailData");
	else if (ix == DPCHAPPFMNCPRSADETAILDO) return("DpchAppFmncPrsADetailDo");
	else if (ix == DPCHAPPFMNCPRSDETAILDATA) return("DpchAppFmncPrsDetailData");
	else if (ix == DPCHAPPFMNCPRSDETAILDO) return("DpchAppFmncPrsDetailDo");
	else if (ix == DPCHAPPFMNCPRSDO) return("DpchAppFmncPrsDo");
	else if (ix == DPCHAPPFMNCPRSHK1NADDRESSDATA) return("DpchAppFmncPrsHk1NAddressData");
	else if (ix == DPCHAPPFMNCPRSHK1NADDRESSDO) return("DpchAppFmncPrsHk1NAddressDo");
	else if (ix == DPCHAPPFMNCPRSLISTDATA) return("DpchAppFmncPrsListData");
	else if (ix == DPCHAPPFMNCPRSLISTDO) return("DpchAppFmncPrsListDo");
	else if (ix == DPCHAPPFMNCPRSMNORGDATA) return("DpchAppFmncPrsMNOrgData");
	else if (ix == DPCHAPPFMNCPRSMNORGDO) return("DpchAppFmncPrsMNOrgDo");
	else if (ix == DPCHAPPFMNCPRSMNRUNDATA) return("DpchAppFmncPrsMNRunData");
	else if (ix == DPCHAPPFMNCPRSMNRUNDO) return("DpchAppFmncPrsMNRunDo");
	else if (ix == DPCHAPPFMNCPRSRECDO) return("DpchAppFmncPrsRecDo");
	else if (ix == DPCHAPPFMNCRESUME) return("DpchAppFmncResume");
	else if (ix == DPCHAPPFMNCRUNDETAILDATA) return("DpchAppFmncRunDetailData");
	else if (ix == DPCHAPPFMNCRUNDETAILDO) return("DpchAppFmncRunDetailDo");
	else if (ix == DPCHAPPFMNCRUNDO) return("DpchAppFmncRunDo");
	else if (ix == DPCHAPPFMNCRUNLISTDATA) return("DpchAppFmncRunListData");
	else if (ix == DPCHAPPFMNCRUNLISTDO) return("DpchAppFmncRunListDo");
	else if (ix == DPCHAPPFMNCRUNMNFABDATA) return("DpchAppFmncRunMNFabData");
	else if (ix == DPCHAPPFMNCRUNMNFABDO) return("DpchAppFmncRunMNFabDo");
	else if (ix == DPCHAPPFMNCRUNMNPERSONDATA) return("DpchAppFmncRunMNPersonData");
	else if (ix == DPCHAPPFMNCRUNMNPERSONDO) return("DpchAppFmncRunMNPersonDo");
	else if (ix == DPCHAPPFMNCRUNMNSAMPLEDATA) return("DpchAppFmncRunMNSampleData");
	else if (ix == DPCHAPPFMNCRUNMNSAMPLEDO) return("DpchAppFmncRunMNSampleDo");
	else if (ix == DPCHAPPFMNCRUNRECDO) return("DpchAppFmncRunRecDo");
	else if (ix == DPCHAPPFMNCRUNREF1NFILEDATA) return("DpchAppFmncRunRef1NFileData");
	else if (ix == DPCHAPPFMNCRUNREF1NFILEDO) return("DpchAppFmncRunRef1NFileDo");
	else if (ix == DPCHAPPFMNCRUNRUN1NACTIVITYDATA) return("DpchAppFmncRunRun1NActivityData");
	else if (ix == DPCHAPPFMNCRUNRUN1NACTIVITYDO) return("DpchAppFmncRunRun1NActivityDo");
	else if (ix == DPCHAPPFMNCSEPAPARDATA) return("DpchAppFmncSepAParData");
	else if (ix == DPCHAPPFMNCSEPAPARDO) return("DpchAppFmncSepAParDo");
	else if (ix == DPCHAPPFMNCSEPDETAILDATA) return("DpchAppFmncSepDetailData");
	else if (ix == DPCHAPPFMNCSEPDETAILDO) return("DpchAppFmncSepDetailDo");
	else if (ix == DPCHAPPFMNCSEPDO) return("DpchAppFmncSepDo");
	else if (ix == DPCHAPPFMNCSEPLISTDATA) return("DpchAppFmncSepListData");
	else if (ix == DPCHAPPFMNCSEPLISTDO) return("DpchAppFmncSepListDo");
	else if (ix == DPCHAPPFMNCSEPMNFILEDATA) return("DpchAppFmncSepMNFileData");
	else if (ix == DPCHAPPFMNCSEPMNFILEDO) return("DpchAppFmncSepMNFileDo");
	else if (ix == DPCHAPPFMNCSEPMNSAMPLEDATA) return("DpchAppFmncSepMNSampleData");
	else if (ix == DPCHAPPFMNCSEPMNSAMPLEDO) return("DpchAppFmncSepMNSampleDo");
	else if (ix == DPCHAPPFMNCSEPRECDO) return("DpchAppFmncSepRecDo");
	else if (ix == DPCHAPPFMNCSEPREF1NFILEDATA) return("DpchAppFmncSepRef1NFileData");
	else if (ix == DPCHAPPFMNCSEPREF1NFILEDO) return("DpchAppFmncSepRef1NFileDo");
	else if (ix == DPCHAPPFMNCSKIDETAILDATA) return("DpchAppFmncSkiDetailData");
	else if (ix == DPCHAPPFMNCSKIDETAILDO) return("DpchAppFmncSkiDetailDo");
	else if (ix == DPCHAPPFMNCSKIDO) return("DpchAppFmncSkiDo");
	else if (ix == DPCHAPPFMNCSKILISTDATA) return("DpchAppFmncSkiListData");
	else if (ix == DPCHAPPFMNCSKILISTDO) return("DpchAppFmncSkiListDo");
	else if (ix == DPCHAPPFMNCSKIRECDO) return("DpchAppFmncSkiRecDo");
	else if (ix == DPCHAPPFMNCSMPAPARDATA) return("DpchAppFmncSmpAParData");
	else if (ix == DPCHAPPFMNCSMPAPARDO) return("DpchAppFmncSmpAParDo");
	else if (ix == DPCHAPPFMNCSMPDETAILDATA) return("DpchAppFmncSmpDetailData");
	else if (ix == DPCHAPPFMNCSMPDETAILDO) return("DpchAppFmncSmpDetailDo");
	else if (ix == DPCHAPPFMNCSMPDO) return("DpchAppFmncSmpDo");
	else if (ix == DPCHAPPFMNCSMPLISTDATA) return("DpchAppFmncSmpListData");
	else if (ix == DPCHAPPFMNCSMPLISTDO) return("DpchAppFmncSmpListDo");
	else if (ix == DPCHAPPFMNCSMPMNFILEDATA) return("DpchAppFmncSmpMNFileData");
	else if (ix == DPCHAPPFMNCSMPMNFILEDO) return("DpchAppFmncSmpMNFileDo");
	else if (ix == DPCHAPPFMNCSMPMNRUNDATA) return("DpchAppFmncSmpMNRunData");
	else if (ix == DPCHAPPFMNCSMPMNRUNDO) return("DpchAppFmncSmpMNRunDo");
	else if (ix == DPCHAPPFMNCSMPMNSTEPDATA) return("DpchAppFmncSmpMNStepData");
	else if (ix == DPCHAPPFMNCSMPMNSTEPDO) return("DpchAppFmncSmpMNStepDo");
	else if (ix == DPCHAPPFMNCSMPRECDO) return("DpchAppFmncSmpRecDo");
	else if (ix == DPCHAPPFMNCSMPREF1NFILEDATA) return("DpchAppFmncSmpRef1NFileData");
	else if (ix == DPCHAPPFMNCSMPREF1NFILEDO) return("DpchAppFmncSmpRef1NFileDo");
	else if (ix == DPCHAPPFMNCSMPSUP1NSAMPLEDATA) return("DpchAppFmncSmpSup1NSampleData");
	else if (ix == DPCHAPPFMNCSMPSUP1NSAMPLEDO) return("DpchAppFmncSmpSup1NSampleDo");
	else if (ix == DPCHAPPFMNCSTPAPARDATA) return("DpchAppFmncStpAParData");
	else if (ix == DPCHAPPFMNCSTPAPARDO) return("DpchAppFmncStpAParDo");
	else if (ix == DPCHAPPFMNCSTPDETAILDATA) return("DpchAppFmncStpDetailData");
	else if (ix == DPCHAPPFMNCSTPDETAILDO) return("DpchAppFmncStpDetailDo");
	else if (ix == DPCHAPPFMNCSTPDO) return("DpchAppFmncStpDo");
	else if (ix == DPCHAPPFMNCSTPKSTEPPARDATA) return("DpchAppFmncStpKStepparData");
	else if (ix == DPCHAPPFMNCSTPKSTEPPARDO) return("DpchAppFmncStpKStepparDo");
	else if (ix == DPCHAPPFMNCSTPLISTDATA) return("DpchAppFmncStpListData");
	else if (ix == DPCHAPPFMNCSTPLISTDO) return("DpchAppFmncStpListDo");
	else if (ix == DPCHAPPFMNCSTPMNFILEDATA) return("DpchAppFmncStpMNFileData");
	else if (ix == DPCHAPPFMNCSTPMNFILEDO) return("DpchAppFmncStpMNFileDo");
	else if (ix == DPCHAPPFMNCSTPRECDO) return("DpchAppFmncStpRecDo");
	else if (ix == DPCHAPPFMNCSTPREF1NFILEDATA) return("DpchAppFmncStpRef1NFileData");
	else if (ix == DPCHAPPFMNCSTPREF1NFILEDO) return("DpchAppFmncStpRef1NFileDo");
	else if (ix == DPCHAPPFMNCSTPTPL1NSTEPDATA) return("DpchAppFmncStpTpl1NStepData");
	else if (ix == DPCHAPPFMNCSTPTPL1NSTEPDO) return("DpchAppFmncStpTpl1NStepDo");
	else if (ix == DPCHAPPFMNCTOL1NARTICLEDATA) return("DpchAppFmncTol1NArticleData");
	else if (ix == DPCHAPPFMNCTOL1NARTICLEDO) return("DpchAppFmncTol1NArticleDo");
	else if (ix == DPCHAPPFMNCTOLAAVLDATA) return("DpchAppFmncTolAAvlData");
	else if (ix == DPCHAPPFMNCTOLAAVLDO) return("DpchAppFmncTolAAvlDo");
	else if (ix == DPCHAPPFMNCTOLACHARDATA) return("DpchAppFmncTolACharData");
	else if (ix == DPCHAPPFMNCTOLACHARDO) return("DpchAppFmncTolACharDo");
	else if (ix == DPCHAPPFMNCTOLARESDATA) return("DpchAppFmncTolAResData");
	else if (ix == DPCHAPPFMNCTOLARESDO) return("DpchAppFmncTolAResDo");
	else if (ix == DPCHAPPFMNCTOLAUTILDATA) return("DpchAppFmncTolAUtilData");
	else if (ix == DPCHAPPFMNCTOLAUTILDO) return("DpchAppFmncTolAUtilDo");
	else if (ix == DPCHAPPFMNCTOLDETAILDATA) return("DpchAppFmncTolDetailData");
	else if (ix == DPCHAPPFMNCTOLDETAILDO) return("DpchAppFmncTolDetailDo");
	else if (ix == DPCHAPPFMNCTOLDO) return("DpchAppFmncTolDo");
	else if (ix == DPCHAPPFMNCTOLKSTEPPARDATA) return("DpchAppFmncTolKStepparData");
	else if (ix == DPCHAPPFMNCTOLKSTEPPARDO) return("DpchAppFmncTolKStepparDo");
	else if (ix == DPCHAPPFMNCTOLKTOOLCHARDATA) return("DpchAppFmncTolKToolcharData");
	else if (ix == DPCHAPPFMNCTOLKTOOLCHARDO) return("DpchAppFmncTolKToolcharDo");
	else if (ix == DPCHAPPFMNCTOLLISTDATA) return("DpchAppFmncTolListData");
	else if (ix == DPCHAPPFMNCTOLLISTDO) return("DpchAppFmncTolListDo");
	else if (ix == DPCHAPPFMNCTOLMNFABUSERDATA) return("DpchAppFmncTolMNFabuserData");
	else if (ix == DPCHAPPFMNCTOLMNFABUSERDO) return("DpchAppFmncTolMNFabuserDo");
	else if (ix == DPCHAPPFMNCTOLMNTOOLTYPEDATA) return("DpchAppFmncTolMNTooltypeData");
	else if (ix == DPCHAPPFMNCTOLMNTOOLTYPEDO) return("DpchAppFmncTolMNTooltypeDo");
	else if (ix == DPCHAPPFMNCTOLRECDO) return("DpchAppFmncTolRecDo");
	else if (ix == DPCHAPPFMNCTOLREF1NFILEDATA) return("DpchAppFmncTolRef1NFileData");
	else if (ix == DPCHAPPFMNCTOLREF1NFILEDO) return("DpchAppFmncTolRef1NFileDo");
	else if (ix == DPCHAPPFMNCTOLRLV1NSTEPDATA) return("DpchAppFmncTolRlv1NStepData");
	else if (ix == DPCHAPPFMNCTOLRLV1NSTEPDO) return("DpchAppFmncTolRlv1NStepDo");
	else if (ix == DPCHAPPFMNCTOLSVCMNORGDATA) return("DpchAppFmncTolSvcMNOrgData");
	else if (ix == DPCHAPPFMNCTOLSVCMNORGDO) return("DpchAppFmncTolSvcMNOrgDo");
	else if (ix == DPCHAPPFMNCTTYDETAILDATA) return("DpchAppFmncTtyDetailData");
	else if (ix == DPCHAPPFMNCTTYDETAILDO) return("DpchAppFmncTtyDetailDo");
	else if (ix == DPCHAPPFMNCTTYDO) return("DpchAppFmncTtyDo");
	else if (ix == DPCHAPPFMNCTTYKSTEPPARDATA) return("DpchAppFmncTtyKStepparData");
	else if (ix == DPCHAPPFMNCTTYKSTEPPARDO) return("DpchAppFmncTtyKStepparDo");
	else if (ix == DPCHAPPFMNCTTYKTOOLCHARDATA) return("DpchAppFmncTtyKToolcharData");
	else if (ix == DPCHAPPFMNCTTYKTOOLCHARDO) return("DpchAppFmncTtyKToolcharDo");
	else if (ix == DPCHAPPFMNCTTYLISTDATA) return("DpchAppFmncTtyListData");
	else if (ix == DPCHAPPFMNCTTYLISTDO) return("DpchAppFmncTtyListDo");
	else if (ix == DPCHAPPFMNCTTYMNTOOLDATA) return("DpchAppFmncTtyMNToolData");
	else if (ix == DPCHAPPFMNCTTYMNTOOLDO) return("DpchAppFmncTtyMNToolDo");
	else if (ix == DPCHAPPFMNCTTYRECDO) return("DpchAppFmncTtyRecDo");
	else if (ix == DPCHAPPFMNCTTYRLV1NSTEPDATA) return("DpchAppFmncTtyRlv1NStepData");
	else if (ix == DPCHAPPFMNCTTYRLV1NSTEPDO) return("DpchAppFmncTtyRlv1NStepDo");
	else if (ix == DPCHAPPFMNCTTYSUP1NTOOLTYPEDATA) return("DpchAppFmncTtySup1NTooltypeData");
	else if (ix == DPCHAPPFMNCTTYSUP1NTOOLTYPEDO) return("DpchAppFmncTtySup1NTooltypeDo");
	else if (ix == DPCHAPPFMNCUSGAACCESSDATA) return("DpchAppFmncUsgAAccessData");
	else if (ix == DPCHAPPFMNCUSGAACCESSDO) return("DpchAppFmncUsgAAccessDo");
	else if (ix == DPCHAPPFMNCUSGDETAILDATA) return("DpchAppFmncUsgDetailData");
	else if (ix == DPCHAPPFMNCUSGDETAILDO) return("DpchAppFmncUsgDetailDo");
	else if (ix == DPCHAPPFMNCUSGDO) return("DpchAppFmncUsgDo");
	else if (ix == DPCHAPPFMNCUSGLISTDATA) return("DpchAppFmncUsgListData");
	else if (ix == DPCHAPPFMNCUSGLISTDO) return("DpchAppFmncUsgListDo");
	else if (ix == DPCHAPPFMNCUSGMNUSERDATA) return("DpchAppFmncUsgMNUserData");
	else if (ix == DPCHAPPFMNCUSGMNUSERDO) return("DpchAppFmncUsgMNUserDo");
	else if (ix == DPCHAPPFMNCUSGRECDO) return("DpchAppFmncUsgRecDo");
	else if (ix == DPCHAPPFMNCUSR1NSESSIONDATA) return("DpchAppFmncUsr1NSessionData");
	else if (ix == DPCHAPPFMNCUSR1NSESSIONDO) return("DpchAppFmncUsr1NSessionDo");
	else if (ix == DPCHAPPFMNCUSRAACCESSDATA) return("DpchAppFmncUsrAAccessData");
	else if (ix == DPCHAPPFMNCUSRAACCESSDO) return("DpchAppFmncUsrAAccessDo");
	else if (ix == DPCHAPPFMNCUSRDETAILDATA) return("DpchAppFmncUsrDetailData");
	else if (ix == DPCHAPPFMNCUSRDETAILDO) return("DpchAppFmncUsrDetailDo");
	else if (ix == DPCHAPPFMNCUSRDO) return("DpchAppFmncUsrDo");
	else if (ix == DPCHAPPFMNCUSRLISTDATA) return("DpchAppFmncUsrListData");
	else if (ix == DPCHAPPFMNCUSRLISTDO) return("DpchAppFmncUsrListDo");
	else if (ix == DPCHAPPFMNCUSRMNUSERGROUPDATA) return("DpchAppFmncUsrMNUsergroupData");
	else if (ix == DPCHAPPFMNCUSRMNUSERGROUPDO) return("DpchAppFmncUsrMNUsergroupDo");
	else if (ix == DPCHAPPFMNCUSRRECDO) return("DpchAppFmncUsrRecDo");
	else if (ix == DPCHAPPROOTFMNCLOGIN) return("DpchAppRootFmncLogin");
	else if (ix == DPCHENGDLGFMNCACTNEWDATA) return("DpchEngDlgFmncActNewData");
	else if (ix == DPCHENGDLGFMNCFABEXPFABDATA) return("DpchEngDlgFmncFabExpfabData");
	else if (ix == DPCHENGDLGFMNCFABIMPFABDATA) return("DpchEngDlgFmncFabImpfabData");
	else if (ix == DPCHENGDLGFMNCFABNEWDATA) return("DpchEngDlgFmncFabNewData");
	else if (ix == DPCHENGDLGFMNCNAVLOAINIDATA) return("DpchEngDlgFmncNavLoainiData");
	else if (ix == DPCHENGDLGFMNCORGEXPORGDATA) return("DpchEngDlgFmncOrgExporgData");
	else if (ix == DPCHENGDLGFMNCORGIMPORGDATA) return("DpchEngDlgFmncOrgImporgData");
	else if (ix == DPCHENGDLGFMNCORGNEWDATA) return("DpchEngDlgFmncOrgNewData");
	else if (ix == DPCHENGDLGFMNCPRJEXPELBDATA) return("DpchEngDlgFmncPrjExpelbData");
	else if (ix == DPCHENGDLGFMNCPRJIMPELBDATA) return("DpchEngDlgFmncPrjImpelbData");
	else if (ix == DPCHENGDLGFMNCPRJNEWDATA) return("DpchEngDlgFmncPrjNewData");
	else if (ix == DPCHENGDLGFMNCRUNGENREPDATA) return("DpchEngDlgFmncRunGenrepData");
	else if (ix == DPCHENGDLGFMNCRUNNEWDATA) return("DpchEngDlgFmncRunNewData");
	else if (ix == DPCHENGDLGFMNCSMPGENREPDATA) return("DpchEngDlgFmncSmpGenrepData");
	else if (ix == DPCHENGDLGFMNCSMPNEWDATA) return("DpchEngDlgFmncSmpNewData");
	else if (ix == DPCHENGFMNCACK) return("DpchEngFmncAck");
	else if (ix == DPCHENGFMNCACT1NSTEPDATA) return("DpchEngFmncAct1NStepData");
	else if (ix == DPCHENGFMNCACTDATA) return("DpchEngFmncActData");
	else if (ix == DPCHENGFMNCACTDETAILDATA) return("DpchEngFmncActDetailData");
	else if (ix == DPCHENGFMNCACTHEADBARDATA) return("DpchEngFmncActHeadbarData");
	else if (ix == DPCHENGFMNCACTLISTDATA) return("DpchEngFmncActListData");
	else if (ix == DPCHENGFMNCACTRECDATA) return("DpchEngFmncActRecData");
	else if (ix == DPCHENGFMNCADRDATA) return("DpchEngFmncAdrData");
	else if (ix == DPCHENGFMNCADRDETAILDATA) return("DpchEngFmncAdrDetailData");
	else if (ix == DPCHENGFMNCADRHEADBARDATA) return("DpchEngFmncAdrHeadbarData");
	else if (ix == DPCHENGFMNCADRLISTDATA) return("DpchEngFmncAdrListData");
	else if (ix == DPCHENGFMNCADRRECDATA) return("DpchEngFmncAdrRecData");
	else if (ix == DPCHENGFMNCALERT) return("DpchEngFmncAlert");
	else if (ix == DPCHENGFMNCART1NSAMPLEDATA) return("DpchEngFmncArt1NSampleData");
	else if (ix == DPCHENGFMNCART1NSTOCKITEMDATA) return("DpchEngFmncArt1NStockitemData");
	else if (ix == DPCHENGFMNCARTDATA) return("DpchEngFmncArtData");
	else if (ix == DPCHENGFMNCARTDETAILDATA) return("DpchEngFmncArtDetailData");
	else if (ix == DPCHENGFMNCARTHEADBARDATA) return("DpchEngFmncArtHeadbarData");
	else if (ix == DPCHENGFMNCARTLISTDATA) return("DpchEngFmncArtListData");
	else if (ix == DPCHENGFMNCARTMNORGDATA) return("DpchEngFmncArtMNOrgData");
	else if (ix == DPCHENGFMNCARTRECDATA) return("DpchEngFmncArtRecData");
	else if (ix == DPCHENGFMNCARTREF1NFILEDATA) return("DpchEngFmncArtRef1NFileData");
	else if (ix == DPCHENGFMNCBILAPOSDATA) return("DpchEngFmncBilAPosData");
	else if (ix == DPCHENGFMNCBILDATA) return("DpchEngFmncBilData");
	else if (ix == DPCHENGFMNCBILDETAILDATA) return("DpchEngFmncBilDetailData");
	else if (ix == DPCHENGFMNCBILHEADBARDATA) return("DpchEngFmncBilHeadbarData");
	else if (ix == DPCHENGFMNCBILLISTDATA) return("DpchEngFmncBilListData");
	else if (ix == DPCHENGFMNCBILRECDATA) return("DpchEngFmncBilRecData");
	else if (ix == DPCHENGFMNCCONFIRM) return("DpchEngFmncConfirm");
	else if (ix == DPCHENGFMNCFAB1NFABPROJECTDATA) return("DpchEngFmncFab1NFabprojectData");
	else if (ix == DPCHENGFMNCFAB1NFABUSERDATA) return("DpchEngFmncFab1NFabuserData");
	else if (ix == DPCHENGFMNCFABDATA) return("DpchEngFmncFabData");
	else if (ix == DPCHENGFMNCFABDETAILDATA) return("DpchEngFmncFabDetailData");
	else if (ix == DPCHENGFMNCFABFAB1NTOOLDATA) return("DpchEngFmncFabFab1NToolData");
	else if (ix == DPCHENGFMNCFABHEADBARDATA) return("DpchEngFmncFabHeadbarData");
	else if (ix == DPCHENGFMNCFABLISTDATA) return("DpchEngFmncFabListData");
	else if (ix == DPCHENGFMNCFABMNRUNDATA) return("DpchEngFmncFabMNRunData");
	else if (ix == DPCHENGFMNCFABRECDATA) return("DpchEngFmncFabRecData");
	else if (ix == DPCHENGFMNCFILDATA) return("DpchEngFmncFilData");
	else if (ix == DPCHENGFMNCFILDETAILDATA) return("DpchEngFmncFilDetailData");
	else if (ix == DPCHENGFMNCFILHEADBARDATA) return("DpchEngFmncFilHeadbarData");
	else if (ix == DPCHENGFMNCFILLISTDATA) return("DpchEngFmncFilListData");
	else if (ix == DPCHENGFMNCFILMNSAMPLEDATA) return("DpchEngFmncFilMNSampleData");
	else if (ix == DPCHENGFMNCFILMNSTEPDATA) return("DpchEngFmncFilMNStepData");
	else if (ix == DPCHENGFMNCFILRECDATA) return("DpchEngFmncFilRecData");
	else if (ix == DPCHENGFMNCFPJ1NBILLDATA) return("DpchEngFmncFpj1NBillData");
	else if (ix == DPCHENGFMNCFPJDATA) return("DpchEngFmncFpjData");
	else if (ix == DPCHENGFMNCFPJDETAILDATA) return("DpchEngFmncFpjDetailData");
	else if (ix == DPCHENGFMNCFPJHEADBARDATA) return("DpchEngFmncFpjHeadbarData");
	else if (ix == DPCHENGFMNCFPJLISTDATA) return("DpchEngFmncFpjListData");
	else if (ix == DPCHENGFMNCFPJMNFABUSERDATA) return("DpchEngFmncFpjMNFabuserData");
	else if (ix == DPCHENGFMNCFPJRECDATA) return("DpchEngFmncFpjRecData");
	else if (ix == DPCHENGFMNCFUSDATA) return("DpchEngFmncFusData");
	else if (ix == DPCHENGFMNCFUSDETAILDATA) return("DpchEngFmncFusDetailData");
	else if (ix == DPCHENGFMNCFUSHEADBARDATA) return("DpchEngFmncFusHeadbarData");
	else if (ix == DPCHENGFMNCFUSLISTDATA) return("DpchEngFmncFusListData");
	else if (ix == DPCHENGFMNCFUSMNFABPROJECTDATA) return("DpchEngFmncFusMNFabprojectData");
	else if (ix == DPCHENGFMNCFUSMNTOOLDATA) return("DpchEngFmncFusMNToolData");
	else if (ix == DPCHENGFMNCFUSRECDATA) return("DpchEngFmncFusRecData");
	else if (ix == DPCHENGFMNCNAVADMINDATA) return("DpchEngFmncNavAdminData");
	else if (ix == DPCHENGFMNCNAVDATA) return("DpchEngFmncNavData");
	else if (ix == DPCHENGFMNCNAVFABMGMTDATA) return("DpchEngFmncNavFabmgmtData");
	else if (ix == DPCHENGFMNCNAVHEADBARDATA) return("DpchEngFmncNavHeadbarData");
	else if (ix == DPCHENGFMNCNAVLABBOOKDATA) return("DpchEngFmncNavLabbookData");
	else if (ix == DPCHENGFMNCNAVPREDATA) return("DpchEngFmncNavPreData");
	else if (ix == DPCHENGFMNCNAVSUPPLYDATA) return("DpchEngFmncNavSupplyData");
	else if (ix == DPCHENGFMNCORG1NARTICLEDATA) return("DpchEngFmncOrg1NArticleData");
	else if (ix == DPCHENGFMNCORG1NSTOCKITEMDATA) return("DpchEngFmncOrg1NStockitemData");
	else if (ix == DPCHENGFMNCORGADETAILDATA) return("DpchEngFmncOrgADetailData");
	else if (ix == DPCHENGFMNCORGBIO1NFABPROJECTDATA) return("DpchEngFmncOrgBio1NFabprojectData");
	else if (ix == DPCHENGFMNCORGDATA) return("DpchEngFmncOrgData");
	else if (ix == DPCHENGFMNCORGDETAILDATA) return("DpchEngFmncOrgDetailData");
	else if (ix == DPCHENGFMNCORGHEADBARDATA) return("DpchEngFmncOrgHeadbarData");
	else if (ix == DPCHENGFMNCORGHK1NADDRESSDATA) return("DpchEngFmncOrgHk1NAddressData");
	else if (ix == DPCHENGFMNCORGKSTOCKLCNDATA) return("DpchEngFmncOrgKStocklcnData");
	else if (ix == DPCHENGFMNCORGLISTDATA) return("DpchEngFmncOrgListData");
	else if (ix == DPCHENGFMNCORGMNARTICLEDATA) return("DpchEngFmncOrgMNArticleData");
	else if (ix == DPCHENGFMNCORGMNF1NTOOLDATA) return("DpchEngFmncOrgMnf1NToolData");
	else if (ix == DPCHENGFMNCORGMNPERSONDATA) return("DpchEngFmncOrgMNPersonData");
	else if (ix == DPCHENGFMNCORGPCO1NPURCHORDERDATA) return("DpchEngFmncOrgPco1NPurchorderData");
	else if (ix == DPCHENGFMNCORGRECDATA) return("DpchEngFmncOrgRecData");
	else if (ix == DPCHENGFMNCORGSPL1NPURCHORDERDATA) return("DpchEngFmncOrgSpl1NPurchorderData");
	else if (ix == DPCHENGFMNCORGSUP1NORGDATA) return("DpchEngFmncOrgSup1NOrgData");
	else if (ix == DPCHENGFMNCORGSVCMNTOOLDATA) return("DpchEngFmncOrgSvcMNToolData");
	else if (ix == DPCHENGFMNCPCOAPOSDATA) return("DpchEngFmncPcoAPosData");
	else if (ix == DPCHENGFMNCPCODATA) return("DpchEngFmncPcoData");
	else if (ix == DPCHENGFMNCPCODETAILDATA) return("DpchEngFmncPcoDetailData");
	else if (ix == DPCHENGFMNCPCOHEADBARDATA) return("DpchEngFmncPcoHeadbarData");
	else if (ix == DPCHENGFMNCPCOLISTDATA) return("DpchEngFmncPcoListData");
	else if (ix == DPCHENGFMNCPCORECDATA) return("DpchEngFmncPcoRecData");
	else if (ix == DPCHENGFMNCPRJ1NRUNDATA) return("DpchEngFmncPrj1NRunData");
	else if (ix == DPCHENGFMNCPRJDATA) return("DpchEngFmncPrjData");
	else if (ix == DPCHENGFMNCPRJDETAILDATA) return("DpchEngFmncPrjDetailData");
	else if (ix == DPCHENGFMNCPRJHEADBARDATA) return("DpchEngFmncPrjHeadbarData");
	else if (ix == DPCHENGFMNCPRJLISTDATA) return("DpchEngFmncPrjListData");
	else if (ix == DPCHENGFMNCPRJRECDATA) return("DpchEngFmncPrjRecData");
	else if (ix == DPCHENGFMNCPRSADETAILDATA) return("DpchEngFmncPrsADetailData");
	else if (ix == DPCHENGFMNCPRSDATA) return("DpchEngFmncPrsData");
	else if (ix == DPCHENGFMNCPRSDETAILDATA) return("DpchEngFmncPrsDetailData");
	else if (ix == DPCHENGFMNCPRSHEADBARDATA) return("DpchEngFmncPrsHeadbarData");
	else if (ix == DPCHENGFMNCPRSHK1NADDRESSDATA) return("DpchEngFmncPrsHk1NAddressData");
	else if (ix == DPCHENGFMNCPRSLISTDATA) return("DpchEngFmncPrsListData");
	else if (ix == DPCHENGFMNCPRSMNORGDATA) return("DpchEngFmncPrsMNOrgData");
	else if (ix == DPCHENGFMNCPRSMNRUNDATA) return("DpchEngFmncPrsMNRunData");
	else if (ix == DPCHENGFMNCPRSRECDATA) return("DpchEngFmncPrsRecData");
	else if (ix == DPCHENGFMNCRUNDATA) return("DpchEngFmncRunData");
	else if (ix == DPCHENGFMNCRUNDETAILDATA) return("DpchEngFmncRunDetailData");
	else if (ix == DPCHENGFMNCRUNHEADBARDATA) return("DpchEngFmncRunHeadbarData");
	else if (ix == DPCHENGFMNCRUNLISTDATA) return("DpchEngFmncRunListData");
	else if (ix == DPCHENGFMNCRUNMNFABDATA) return("DpchEngFmncRunMNFabData");
	else if (ix == DPCHENGFMNCRUNMNPERSONDATA) return("DpchEngFmncRunMNPersonData");
	else if (ix == DPCHENGFMNCRUNMNSAMPLEDATA) return("DpchEngFmncRunMNSampleData");
	else if (ix == DPCHENGFMNCRUNRECDATA) return("DpchEngFmncRunRecData");
	else if (ix == DPCHENGFMNCRUNREF1NFILEDATA) return("DpchEngFmncRunRef1NFileData");
	else if (ix == DPCHENGFMNCRUNRUN1NACTIVITYDATA) return("DpchEngFmncRunRun1NActivityData");
	else if (ix == DPCHENGFMNCSEPAPARDATA) return("DpchEngFmncSepAParData");
	else if (ix == DPCHENGFMNCSEPDATA) return("DpchEngFmncSepData");
	else if (ix == DPCHENGFMNCSEPDETAILDATA) return("DpchEngFmncSepDetailData");
	else if (ix == DPCHENGFMNCSEPHEADBARDATA) return("DpchEngFmncSepHeadbarData");
	else if (ix == DPCHENGFMNCSEPLISTDATA) return("DpchEngFmncSepListData");
	else if (ix == DPCHENGFMNCSEPMNFILEDATA) return("DpchEngFmncSepMNFileData");
	else if (ix == DPCHENGFMNCSEPMNSAMPLEDATA) return("DpchEngFmncSepMNSampleData");
	else if (ix == DPCHENGFMNCSEPRECDATA) return("DpchEngFmncSepRecData");
	else if (ix == DPCHENGFMNCSEPREF1NFILEDATA) return("DpchEngFmncSepRef1NFileData");
	else if (ix == DPCHENGFMNCSKIDATA) return("DpchEngFmncSkiData");
	else if (ix == DPCHENGFMNCSKIDETAILDATA) return("DpchEngFmncSkiDetailData");
	else if (ix == DPCHENGFMNCSKIHEADBARDATA) return("DpchEngFmncSkiHeadbarData");
	else if (ix == DPCHENGFMNCSKILISTDATA) return("DpchEngFmncSkiListData");
	else if (ix == DPCHENGFMNCSKIRECDATA) return("DpchEngFmncSkiRecData");
	else if (ix == DPCHENGFMNCSMPAPARDATA) return("DpchEngFmncSmpAParData");
	else if (ix == DPCHENGFMNCSMPDATA) return("DpchEngFmncSmpData");
	else if (ix == DPCHENGFMNCSMPDETAILDATA) return("DpchEngFmncSmpDetailData");
	else if (ix == DPCHENGFMNCSMPHEADBARDATA) return("DpchEngFmncSmpHeadbarData");
	else if (ix == DPCHENGFMNCSMPLISTDATA) return("DpchEngFmncSmpListData");
	else if (ix == DPCHENGFMNCSMPMNFILEDATA) return("DpchEngFmncSmpMNFileData");
	else if (ix == DPCHENGFMNCSMPMNRUNDATA) return("DpchEngFmncSmpMNRunData");
	else if (ix == DPCHENGFMNCSMPMNSTEPDATA) return("DpchEngFmncSmpMNStepData");
	else if (ix == DPCHENGFMNCSMPRECDATA) return("DpchEngFmncSmpRecData");
	else if (ix == DPCHENGFMNCSMPREF1NFILEDATA) return("DpchEngFmncSmpRef1NFileData");
	else if (ix == DPCHENGFMNCSMPSUP1NSAMPLEDATA) return("DpchEngFmncSmpSup1NSampleData");
	else if (ix == DPCHENGFMNCSTPAPARDATA) return("DpchEngFmncStpAParData");
	else if (ix == DPCHENGFMNCSTPDATA) return("DpchEngFmncStpData");
	else if (ix == DPCHENGFMNCSTPDETAILDATA) return("DpchEngFmncStpDetailData");
	else if (ix == DPCHENGFMNCSTPHEADBARDATA) return("DpchEngFmncStpHeadbarData");
	else if (ix == DPCHENGFMNCSTPKSTEPPARDATA) return("DpchEngFmncStpKStepparData");
	else if (ix == DPCHENGFMNCSTPLISTDATA) return("DpchEngFmncStpListData");
	else if (ix == DPCHENGFMNCSTPMNFILEDATA) return("DpchEngFmncStpMNFileData");
	else if (ix == DPCHENGFMNCSTPRECDATA) return("DpchEngFmncStpRecData");
	else if (ix == DPCHENGFMNCSTPREF1NFILEDATA) return("DpchEngFmncStpRef1NFileData");
	else if (ix == DPCHENGFMNCSTPTPL1NSTEPDATA) return("DpchEngFmncStpTpl1NStepData");
	else if (ix == DPCHENGFMNCSUSPEND) return("DpchEngFmncSuspend");
	else if (ix == DPCHENGFMNCTOL1NARTICLEDATA) return("DpchEngFmncTol1NArticleData");
	else if (ix == DPCHENGFMNCTOLAAVLDATA) return("DpchEngFmncTolAAvlData");
	else if (ix == DPCHENGFMNCTOLACHARDATA) return("DpchEngFmncTolACharData");
	else if (ix == DPCHENGFMNCTOLARESDATA) return("DpchEngFmncTolAResData");
	else if (ix == DPCHENGFMNCTOLAUTILDATA) return("DpchEngFmncTolAUtilData");
	else if (ix == DPCHENGFMNCTOLDATA) return("DpchEngFmncTolData");
	else if (ix == DPCHENGFMNCTOLDETAILDATA) return("DpchEngFmncTolDetailData");
	else if (ix == DPCHENGFMNCTOLHEADBARDATA) return("DpchEngFmncTolHeadbarData");
	else if (ix == DPCHENGFMNCTOLKSTEPPARDATA) return("DpchEngFmncTolKStepparData");
	else if (ix == DPCHENGFMNCTOLKTOOLCHARDATA) return("DpchEngFmncTolKToolcharData");
	else if (ix == DPCHENGFMNCTOLLISTDATA) return("DpchEngFmncTolListData");
	else if (ix == DPCHENGFMNCTOLMNFABUSERDATA) return("DpchEngFmncTolMNFabuserData");
	else if (ix == DPCHENGFMNCTOLMNTOOLTYPEDATA) return("DpchEngFmncTolMNTooltypeData");
	else if (ix == DPCHENGFMNCTOLRECDATA) return("DpchEngFmncTolRecData");
	else if (ix == DPCHENGFMNCTOLREF1NFILEDATA) return("DpchEngFmncTolRef1NFileData");
	else if (ix == DPCHENGFMNCTOLRLV1NSTEPDATA) return("DpchEngFmncTolRlv1NStepData");
	else if (ix == DPCHENGFMNCTOLSVCMNORGDATA) return("DpchEngFmncTolSvcMNOrgData");
	else if (ix == DPCHENGFMNCTTYDATA) return("DpchEngFmncTtyData");
	else if (ix == DPCHENGFMNCTTYDETAILDATA) return("DpchEngFmncTtyDetailData");
	else if (ix == DPCHENGFMNCTTYHEADBARDATA) return("DpchEngFmncTtyHeadbarData");
	else if (ix == DPCHENGFMNCTTYKSTEPPARDATA) return("DpchEngFmncTtyKStepparData");
	else if (ix == DPCHENGFMNCTTYKTOOLCHARDATA) return("DpchEngFmncTtyKToolcharData");
	else if (ix == DPCHENGFMNCTTYLISTDATA) return("DpchEngFmncTtyListData");
	else if (ix == DPCHENGFMNCTTYMNTOOLDATA) return("DpchEngFmncTtyMNToolData");
	else if (ix == DPCHENGFMNCTTYRECDATA) return("DpchEngFmncTtyRecData");
	else if (ix == DPCHENGFMNCTTYRLV1NSTEPDATA) return("DpchEngFmncTtyRlv1NStepData");
	else if (ix == DPCHENGFMNCTTYSUP1NTOOLTYPEDATA) return("DpchEngFmncTtySup1NTooltypeData");
	else if (ix == DPCHENGFMNCUSGAACCESSDATA) return("DpchEngFmncUsgAAccessData");
	else if (ix == DPCHENGFMNCUSGDATA) return("DpchEngFmncUsgData");
	else if (ix == DPCHENGFMNCUSGDETAILDATA) return("DpchEngFmncUsgDetailData");
	else if (ix == DPCHENGFMNCUSGHEADBARDATA) return("DpchEngFmncUsgHeadbarData");
	else if (ix == DPCHENGFMNCUSGLISTDATA) return("DpchEngFmncUsgListData");
	else if (ix == DPCHENGFMNCUSGMNUSERDATA) return("DpchEngFmncUsgMNUserData");
	else if (ix == DPCHENGFMNCUSGRECDATA) return("DpchEngFmncUsgRecData");
	else if (ix == DPCHENGFMNCUSR1NSESSIONDATA) return("DpchEngFmncUsr1NSessionData");
	else if (ix == DPCHENGFMNCUSRAACCESSDATA) return("DpchEngFmncUsrAAccessData");
	else if (ix == DPCHENGFMNCUSRDATA) return("DpchEngFmncUsrData");
	else if (ix == DPCHENGFMNCUSRDETAILDATA) return("DpchEngFmncUsrDetailData");
	else if (ix == DPCHENGFMNCUSRHEADBARDATA) return("DpchEngFmncUsrHeadbarData");
	else if (ix == DPCHENGFMNCUSRLISTDATA) return("DpchEngFmncUsrListData");
	else if (ix == DPCHENGFMNCUSRMNUSERGROUPDATA) return("DpchEngFmncUsrMNUsergroupData");
	else if (ix == DPCHENGFMNCUSRRECDATA) return("DpchEngFmncUsrRecData");
	else if (ix == DPCHENGSESSFMNCDATA) return("DpchEngSessFmncData");
	else if (ix == DPCHFMNCDACK) return("DpchFmncdAck");
	else if (ix == DPCHFMNCDQUIT) return("DpchFmncdQuit");
	else if (ix == DPCHFMNCDREG) return("DpchFmncdReg");
	else if (ix == DPCHFMNCOPDREG) return("DpchFmncopdReg");
	else if (ix == DPCHFMNCOPDUNREG) return("DpchFmncopdUnreg");
	else if (ix == DPCHINVFMNC) return("DpchInvFmnc");
	else if (ix == DPCHRETFMNC) return("DpchRetFmnc");

	return("");
};


