/**
  * \file VecFmncVDpch.h
  * vector VecFmncVDpch (implementation)
  * \author Alexander Wirthmueller
  * \date created: 7 Mar 2016
  * \date modified: 7 Mar 2016
  */

#include "VecFmncVDpch.h"

/******************************************************************************
 namespace VecFmncVDpch
 ******************************************************************************/

uint VecFmncVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s.compare("dpchengdlgfmncactnewdata") == 0) return DPCHENGDLGFMNCACTNEWDATA;
	else if (s.compare("dpchengdlgfmncfabexpfabdata") == 0) return DPCHENGDLGFMNCFABEXPFABDATA;
	else if (s.compare("dpchengdlgfmncfabimpfabdata") == 0) return DPCHENGDLGFMNCFABIMPFABDATA;
	else if (s.compare("dpchengdlgfmncfabnewdata") == 0) return DPCHENGDLGFMNCFABNEWDATA;
	else if (s.compare("dpchengdlgfmncnavloainidata") == 0) return DPCHENGDLGFMNCNAVLOAINIDATA;
	else if (s.compare("dpchengdlgfmncorgexporgdata") == 0) return DPCHENGDLGFMNCORGEXPORGDATA;
	else if (s.compare("dpchengdlgfmncorgimporgdata") == 0) return DPCHENGDLGFMNCORGIMPORGDATA;
	else if (s.compare("dpchengdlgfmncorgnewdata") == 0) return DPCHENGDLGFMNCORGNEWDATA;
	else if (s.compare("dpchengdlgfmncprjexpelbdata") == 0) return DPCHENGDLGFMNCPRJEXPELBDATA;
	else if (s.compare("dpchengdlgfmncprjimpelbdata") == 0) return DPCHENGDLGFMNCPRJIMPELBDATA;
	else if (s.compare("dpchengdlgfmncprjnewdata") == 0) return DPCHENGDLGFMNCPRJNEWDATA;
	else if (s.compare("dpchengdlgfmncrungenrepdata") == 0) return DPCHENGDLGFMNCRUNGENREPDATA;
	else if (s.compare("dpchengdlgfmncrunnewdata") == 0) return DPCHENGDLGFMNCRUNNEWDATA;
	else if (s.compare("dpchengdlgfmncsmpgenrepdata") == 0) return DPCHENGDLGFMNCSMPGENREPDATA;
	else if (s.compare("dpchengdlgfmncsmpnewdata") == 0) return DPCHENGDLGFMNCSMPNEWDATA;
	else if (s.compare("dpchengfmncack") == 0) return DPCHENGFMNCACK;
	else if (s.compare("dpchengfmncact1nstepdata") == 0) return DPCHENGFMNCACT1NSTEPDATA;
	else if (s.compare("dpchengfmncactdata") == 0) return DPCHENGFMNCACTDATA;
	else if (s.compare("dpchengfmncactdetaildata") == 0) return DPCHENGFMNCACTDETAILDATA;
	else if (s.compare("dpchengfmncactheadbardata") == 0) return DPCHENGFMNCACTHEADBARDATA;
	else if (s.compare("dpchengfmncactlistdata") == 0) return DPCHENGFMNCACTLISTDATA;
	else if (s.compare("dpchengfmncactrecdata") == 0) return DPCHENGFMNCACTRECDATA;
	else if (s.compare("dpchengfmncadrdata") == 0) return DPCHENGFMNCADRDATA;
	else if (s.compare("dpchengfmncadrdetaildata") == 0) return DPCHENGFMNCADRDETAILDATA;
	else if (s.compare("dpchengfmncadrheadbardata") == 0) return DPCHENGFMNCADRHEADBARDATA;
	else if (s.compare("dpchengfmncadrlistdata") == 0) return DPCHENGFMNCADRLISTDATA;
	else if (s.compare("dpchengfmncadrrecdata") == 0) return DPCHENGFMNCADRRECDATA;
	else if (s.compare("dpchengfmncalert") == 0) return DPCHENGFMNCALERT;
	else if (s.compare("dpchengfmncart1nsampledata") == 0) return DPCHENGFMNCART1NSAMPLEDATA;
	else if (s.compare("dpchengfmncart1nstockitemdata") == 0) return DPCHENGFMNCART1NSTOCKITEMDATA;
	else if (s.compare("dpchengfmncartdata") == 0) return DPCHENGFMNCARTDATA;
	else if (s.compare("dpchengfmncartdetaildata") == 0) return DPCHENGFMNCARTDETAILDATA;
	else if (s.compare("dpchengfmncartheadbardata") == 0) return DPCHENGFMNCARTHEADBARDATA;
	else if (s.compare("dpchengfmncartlistdata") == 0) return DPCHENGFMNCARTLISTDATA;
	else if (s.compare("dpchengfmncartmnorgdata") == 0) return DPCHENGFMNCARTMNORGDATA;
	else if (s.compare("dpchengfmncartrecdata") == 0) return DPCHENGFMNCARTRECDATA;
	else if (s.compare("dpchengfmncartref1nfiledata") == 0) return DPCHENGFMNCARTREF1NFILEDATA;
	else if (s.compare("dpchengfmncbilaposdata") == 0) return DPCHENGFMNCBILAPOSDATA;
	else if (s.compare("dpchengfmncbildata") == 0) return DPCHENGFMNCBILDATA;
	else if (s.compare("dpchengfmncbildetaildata") == 0) return DPCHENGFMNCBILDETAILDATA;
	else if (s.compare("dpchengfmncbilheadbardata") == 0) return DPCHENGFMNCBILHEADBARDATA;
	else if (s.compare("dpchengfmncbillistdata") == 0) return DPCHENGFMNCBILLISTDATA;
	else if (s.compare("dpchengfmncbilrecdata") == 0) return DPCHENGFMNCBILRECDATA;
	else if (s.compare("dpchengfmncconfirm") == 0) return DPCHENGFMNCCONFIRM;
	else if (s.compare("dpchengfmncfab1nfabprojectdata") == 0) return DPCHENGFMNCFAB1NFABPROJECTDATA;
	else if (s.compare("dpchengfmncfab1nfabuserdata") == 0) return DPCHENGFMNCFAB1NFABUSERDATA;
	else if (s.compare("dpchengfmncfabdata") == 0) return DPCHENGFMNCFABDATA;
	else if (s.compare("dpchengfmncfabdetaildata") == 0) return DPCHENGFMNCFABDETAILDATA;
	else if (s.compare("dpchengfmncfabfab1ntooldata") == 0) return DPCHENGFMNCFABFAB1NTOOLDATA;
	else if (s.compare("dpchengfmncfabheadbardata") == 0) return DPCHENGFMNCFABHEADBARDATA;
	else if (s.compare("dpchengfmncfablistdata") == 0) return DPCHENGFMNCFABLISTDATA;
	else if (s.compare("dpchengfmncfabmnrundata") == 0) return DPCHENGFMNCFABMNRUNDATA;
	else if (s.compare("dpchengfmncfabrecdata") == 0) return DPCHENGFMNCFABRECDATA;
	else if (s.compare("dpchengfmncfildata") == 0) return DPCHENGFMNCFILDATA;
	else if (s.compare("dpchengfmncfildetaildata") == 0) return DPCHENGFMNCFILDETAILDATA;
	else if (s.compare("dpchengfmncfilheadbardata") == 0) return DPCHENGFMNCFILHEADBARDATA;
	else if (s.compare("dpchengfmncfillistdata") == 0) return DPCHENGFMNCFILLISTDATA;
	else if (s.compare("dpchengfmncfilmnsampledata") == 0) return DPCHENGFMNCFILMNSAMPLEDATA;
	else if (s.compare("dpchengfmncfilmnstepdata") == 0) return DPCHENGFMNCFILMNSTEPDATA;
	else if (s.compare("dpchengfmncfilrecdata") == 0) return DPCHENGFMNCFILRECDATA;
	else if (s.compare("dpchengfmncfpj1nbilldata") == 0) return DPCHENGFMNCFPJ1NBILLDATA;
	else if (s.compare("dpchengfmncfpjdata") == 0) return DPCHENGFMNCFPJDATA;
	else if (s.compare("dpchengfmncfpjdetaildata") == 0) return DPCHENGFMNCFPJDETAILDATA;
	else if (s.compare("dpchengfmncfpjheadbardata") == 0) return DPCHENGFMNCFPJHEADBARDATA;
	else if (s.compare("dpchengfmncfpjlistdata") == 0) return DPCHENGFMNCFPJLISTDATA;
	else if (s.compare("dpchengfmncfpjmnfabuserdata") == 0) return DPCHENGFMNCFPJMNFABUSERDATA;
	else if (s.compare("dpchengfmncfpjrecdata") == 0) return DPCHENGFMNCFPJRECDATA;
	else if (s.compare("dpchengfmncfusdata") == 0) return DPCHENGFMNCFUSDATA;
	else if (s.compare("dpchengfmncfusdetaildata") == 0) return DPCHENGFMNCFUSDETAILDATA;
	else if (s.compare("dpchengfmncfusheadbardata") == 0) return DPCHENGFMNCFUSHEADBARDATA;
	else if (s.compare("dpchengfmncfuslistdata") == 0) return DPCHENGFMNCFUSLISTDATA;
	else if (s.compare("dpchengfmncfusmnfabprojectdata") == 0) return DPCHENGFMNCFUSMNFABPROJECTDATA;
	else if (s.compare("dpchengfmncfusmntooldata") == 0) return DPCHENGFMNCFUSMNTOOLDATA;
	else if (s.compare("dpchengfmncfusrecdata") == 0) return DPCHENGFMNCFUSRECDATA;
	else if (s.compare("dpchengfmncnavadmindata") == 0) return DPCHENGFMNCNAVADMINDATA;
	else if (s.compare("dpchengfmncnavdata") == 0) return DPCHENGFMNCNAVDATA;
	else if (s.compare("dpchengfmncnavfabmgmtdata") == 0) return DPCHENGFMNCNAVFABMGMTDATA;
	else if (s.compare("dpchengfmncnavheadbardata") == 0) return DPCHENGFMNCNAVHEADBARDATA;
	else if (s.compare("dpchengfmncnavlabbookdata") == 0) return DPCHENGFMNCNAVLABBOOKDATA;
	else if (s.compare("dpchengfmncnavpredata") == 0) return DPCHENGFMNCNAVPREDATA;
	else if (s.compare("dpchengfmncnavsupplydata") == 0) return DPCHENGFMNCNAVSUPPLYDATA;
	else if (s.compare("dpchengfmncorg1narticledata") == 0) return DPCHENGFMNCORG1NARTICLEDATA;
	else if (s.compare("dpchengfmncorg1nstockitemdata") == 0) return DPCHENGFMNCORG1NSTOCKITEMDATA;
	else if (s.compare("dpchengfmncorgadetaildata") == 0) return DPCHENGFMNCORGADETAILDATA;
	else if (s.compare("dpchengfmncorgbio1nfabprojectdata") == 0) return DPCHENGFMNCORGBIO1NFABPROJECTDATA;
	else if (s.compare("dpchengfmncorgdata") == 0) return DPCHENGFMNCORGDATA;
	else if (s.compare("dpchengfmncorgdetaildata") == 0) return DPCHENGFMNCORGDETAILDATA;
	else if (s.compare("dpchengfmncorgheadbardata") == 0) return DPCHENGFMNCORGHEADBARDATA;
	else if (s.compare("dpchengfmncorghk1naddressdata") == 0) return DPCHENGFMNCORGHK1NADDRESSDATA;
	else if (s.compare("dpchengfmncorgkstocklcndata") == 0) return DPCHENGFMNCORGKSTOCKLCNDATA;
	else if (s.compare("dpchengfmncorglistdata") == 0) return DPCHENGFMNCORGLISTDATA;
	else if (s.compare("dpchengfmncorgmnarticledata") == 0) return DPCHENGFMNCORGMNARTICLEDATA;
	else if (s.compare("dpchengfmncorgmnf1ntooldata") == 0) return DPCHENGFMNCORGMNF1NTOOLDATA;
	else if (s.compare("dpchengfmncorgmnpersondata") == 0) return DPCHENGFMNCORGMNPERSONDATA;
	else if (s.compare("dpchengfmncorgpco1npurchorderdata") == 0) return DPCHENGFMNCORGPCO1NPURCHORDERDATA;
	else if (s.compare("dpchengfmncorgrecdata") == 0) return DPCHENGFMNCORGRECDATA;
	else if (s.compare("dpchengfmncorgspl1npurchorderdata") == 0) return DPCHENGFMNCORGSPL1NPURCHORDERDATA;
	else if (s.compare("dpchengfmncorgsup1norgdata") == 0) return DPCHENGFMNCORGSUP1NORGDATA;
	else if (s.compare("dpchengfmncorgsvcmntooldata") == 0) return DPCHENGFMNCORGSVCMNTOOLDATA;
	else if (s.compare("dpchengfmncpcoaposdata") == 0) return DPCHENGFMNCPCOAPOSDATA;
	else if (s.compare("dpchengfmncpcodata") == 0) return DPCHENGFMNCPCODATA;
	else if (s.compare("dpchengfmncpcodetaildata") == 0) return DPCHENGFMNCPCODETAILDATA;
	else if (s.compare("dpchengfmncpcoheadbardata") == 0) return DPCHENGFMNCPCOHEADBARDATA;
	else if (s.compare("dpchengfmncpcolistdata") == 0) return DPCHENGFMNCPCOLISTDATA;
	else if (s.compare("dpchengfmncpcorecdata") == 0) return DPCHENGFMNCPCORECDATA;
	else if (s.compare("dpchengfmncprj1nrundata") == 0) return DPCHENGFMNCPRJ1NRUNDATA;
	else if (s.compare("dpchengfmncprjdata") == 0) return DPCHENGFMNCPRJDATA;
	else if (s.compare("dpchengfmncprjdetaildata") == 0) return DPCHENGFMNCPRJDETAILDATA;
	else if (s.compare("dpchengfmncprjheadbardata") == 0) return DPCHENGFMNCPRJHEADBARDATA;
	else if (s.compare("dpchengfmncprjlistdata") == 0) return DPCHENGFMNCPRJLISTDATA;
	else if (s.compare("dpchengfmncprjrecdata") == 0) return DPCHENGFMNCPRJRECDATA;
	else if (s.compare("dpchengfmncprsadetaildata") == 0) return DPCHENGFMNCPRSADETAILDATA;
	else if (s.compare("dpchengfmncprsdata") == 0) return DPCHENGFMNCPRSDATA;
	else if (s.compare("dpchengfmncprsdetaildata") == 0) return DPCHENGFMNCPRSDETAILDATA;
	else if (s.compare("dpchengfmncprsheadbardata") == 0) return DPCHENGFMNCPRSHEADBARDATA;
	else if (s.compare("dpchengfmncprshk1naddressdata") == 0) return DPCHENGFMNCPRSHK1NADDRESSDATA;
	else if (s.compare("dpchengfmncprslistdata") == 0) return DPCHENGFMNCPRSLISTDATA;
	else if (s.compare("dpchengfmncprsmnorgdata") == 0) return DPCHENGFMNCPRSMNORGDATA;
	else if (s.compare("dpchengfmncprsmnrundata") == 0) return DPCHENGFMNCPRSMNRUNDATA;
	else if (s.compare("dpchengfmncprsrecdata") == 0) return DPCHENGFMNCPRSRECDATA;
	else if (s.compare("dpchengfmncrundata") == 0) return DPCHENGFMNCRUNDATA;
	else if (s.compare("dpchengfmncrundetaildata") == 0) return DPCHENGFMNCRUNDETAILDATA;
	else if (s.compare("dpchengfmncrunheadbardata") == 0) return DPCHENGFMNCRUNHEADBARDATA;
	else if (s.compare("dpchengfmncrunlistdata") == 0) return DPCHENGFMNCRUNLISTDATA;
	else if (s.compare("dpchengfmncrunmnfabdata") == 0) return DPCHENGFMNCRUNMNFABDATA;
	else if (s.compare("dpchengfmncrunmnpersondata") == 0) return DPCHENGFMNCRUNMNPERSONDATA;
	else if (s.compare("dpchengfmncrunmnsampledata") == 0) return DPCHENGFMNCRUNMNSAMPLEDATA;
	else if (s.compare("dpchengfmncrunrecdata") == 0) return DPCHENGFMNCRUNRECDATA;
	else if (s.compare("dpchengfmncrunref1nfiledata") == 0) return DPCHENGFMNCRUNREF1NFILEDATA;
	else if (s.compare("dpchengfmncrunrun1nactivitydata") == 0) return DPCHENGFMNCRUNRUN1NACTIVITYDATA;
	else if (s.compare("dpchengfmncsepapardata") == 0) return DPCHENGFMNCSEPAPARDATA;
	else if (s.compare("dpchengfmncsepdata") == 0) return DPCHENGFMNCSEPDATA;
	else if (s.compare("dpchengfmncsepdetaildata") == 0) return DPCHENGFMNCSEPDETAILDATA;
	else if (s.compare("dpchengfmncsepheadbardata") == 0) return DPCHENGFMNCSEPHEADBARDATA;
	else if (s.compare("dpchengfmncseplistdata") == 0) return DPCHENGFMNCSEPLISTDATA;
	else if (s.compare("dpchengfmncsepmnfiledata") == 0) return DPCHENGFMNCSEPMNFILEDATA;
	else if (s.compare("dpchengfmncsepmnsampledata") == 0) return DPCHENGFMNCSEPMNSAMPLEDATA;
	else if (s.compare("dpchengfmncseprecdata") == 0) return DPCHENGFMNCSEPRECDATA;
	else if (s.compare("dpchengfmncsepref1nfiledata") == 0) return DPCHENGFMNCSEPREF1NFILEDATA;
	else if (s.compare("dpchengfmncskidata") == 0) return DPCHENGFMNCSKIDATA;
	else if (s.compare("dpchengfmncskidetaildata") == 0) return DPCHENGFMNCSKIDETAILDATA;
	else if (s.compare("dpchengfmncskiheadbardata") == 0) return DPCHENGFMNCSKIHEADBARDATA;
	else if (s.compare("dpchengfmncskilistdata") == 0) return DPCHENGFMNCSKILISTDATA;
	else if (s.compare("dpchengfmncskirecdata") == 0) return DPCHENGFMNCSKIRECDATA;
	else if (s.compare("dpchengfmncsmpapardata") == 0) return DPCHENGFMNCSMPAPARDATA;
	else if (s.compare("dpchengfmncsmpdata") == 0) return DPCHENGFMNCSMPDATA;
	else if (s.compare("dpchengfmncsmpdetaildata") == 0) return DPCHENGFMNCSMPDETAILDATA;
	else if (s.compare("dpchengfmncsmpheadbardata") == 0) return DPCHENGFMNCSMPHEADBARDATA;
	else if (s.compare("dpchengfmncsmplistdata") == 0) return DPCHENGFMNCSMPLISTDATA;
	else if (s.compare("dpchengfmncsmpmnfiledata") == 0) return DPCHENGFMNCSMPMNFILEDATA;
	else if (s.compare("dpchengfmncsmpmnrundata") == 0) return DPCHENGFMNCSMPMNRUNDATA;
	else if (s.compare("dpchengfmncsmpmnstepdata") == 0) return DPCHENGFMNCSMPMNSTEPDATA;
	else if (s.compare("dpchengfmncsmprecdata") == 0) return DPCHENGFMNCSMPRECDATA;
	else if (s.compare("dpchengfmncsmpref1nfiledata") == 0) return DPCHENGFMNCSMPREF1NFILEDATA;
	else if (s.compare("dpchengfmncsmpsup1nsampledata") == 0) return DPCHENGFMNCSMPSUP1NSAMPLEDATA;
	else if (s.compare("dpchengfmncstpapardata") == 0) return DPCHENGFMNCSTPAPARDATA;
	else if (s.compare("dpchengfmncstpdata") == 0) return DPCHENGFMNCSTPDATA;
	else if (s.compare("dpchengfmncstpdetaildata") == 0) return DPCHENGFMNCSTPDETAILDATA;
	else if (s.compare("dpchengfmncstpheadbardata") == 0) return DPCHENGFMNCSTPHEADBARDATA;
	else if (s.compare("dpchengfmncstpksteppardata") == 0) return DPCHENGFMNCSTPKSTEPPARDATA;
	else if (s.compare("dpchengfmncstplistdata") == 0) return DPCHENGFMNCSTPLISTDATA;
	else if (s.compare("dpchengfmncstpmnfiledata") == 0) return DPCHENGFMNCSTPMNFILEDATA;
	else if (s.compare("dpchengfmncstprecdata") == 0) return DPCHENGFMNCSTPRECDATA;
	else if (s.compare("dpchengfmncstpref1nfiledata") == 0) return DPCHENGFMNCSTPREF1NFILEDATA;
	else if (s.compare("dpchengfmncstptpl1nstepdata") == 0) return DPCHENGFMNCSTPTPL1NSTEPDATA;
	else if (s.compare("dpchengfmncsuspend") == 0) return DPCHENGFMNCSUSPEND;
	else if (s.compare("dpchengfmnctol1narticledata") == 0) return DPCHENGFMNCTOL1NARTICLEDATA;
	else if (s.compare("dpchengfmnctolaavldata") == 0) return DPCHENGFMNCTOLAAVLDATA;
	else if (s.compare("dpchengfmnctolachardata") == 0) return DPCHENGFMNCTOLACHARDATA;
	else if (s.compare("dpchengfmnctolaresdata") == 0) return DPCHENGFMNCTOLARESDATA;
	else if (s.compare("dpchengfmnctolautildata") == 0) return DPCHENGFMNCTOLAUTILDATA;
	else if (s.compare("dpchengfmnctoldata") == 0) return DPCHENGFMNCTOLDATA;
	else if (s.compare("dpchengfmnctoldetaildata") == 0) return DPCHENGFMNCTOLDETAILDATA;
	else if (s.compare("dpchengfmnctolheadbardata") == 0) return DPCHENGFMNCTOLHEADBARDATA;
	else if (s.compare("dpchengfmnctolksteppardata") == 0) return DPCHENGFMNCTOLKSTEPPARDATA;
	else if (s.compare("dpchengfmnctolktoolchardata") == 0) return DPCHENGFMNCTOLKTOOLCHARDATA;
	else if (s.compare("dpchengfmnctollistdata") == 0) return DPCHENGFMNCTOLLISTDATA;
	else if (s.compare("dpchengfmnctolmnfabuserdata") == 0) return DPCHENGFMNCTOLMNFABUSERDATA;
	else if (s.compare("dpchengfmnctolmntooltypedata") == 0) return DPCHENGFMNCTOLMNTOOLTYPEDATA;
	else if (s.compare("dpchengfmnctolrecdata") == 0) return DPCHENGFMNCTOLRECDATA;
	else if (s.compare("dpchengfmnctolref1nfiledata") == 0) return DPCHENGFMNCTOLREF1NFILEDATA;
	else if (s.compare("dpchengfmnctolrlv1nstepdata") == 0) return DPCHENGFMNCTOLRLV1NSTEPDATA;
	else if (s.compare("dpchengfmnctolsvcmnorgdata") == 0) return DPCHENGFMNCTOLSVCMNORGDATA;
	else if (s.compare("dpchengfmncttydata") == 0) return DPCHENGFMNCTTYDATA;
	else if (s.compare("dpchengfmncttydetaildata") == 0) return DPCHENGFMNCTTYDETAILDATA;
	else if (s.compare("dpchengfmncttyheadbardata") == 0) return DPCHENGFMNCTTYHEADBARDATA;
	else if (s.compare("dpchengfmncttyksteppardata") == 0) return DPCHENGFMNCTTYKSTEPPARDATA;
	else if (s.compare("dpchengfmncttyktoolchardata") == 0) return DPCHENGFMNCTTYKTOOLCHARDATA;
	else if (s.compare("dpchengfmncttylistdata") == 0) return DPCHENGFMNCTTYLISTDATA;
	else if (s.compare("dpchengfmncttymntooldata") == 0) return DPCHENGFMNCTTYMNTOOLDATA;
	else if (s.compare("dpchengfmncttyrecdata") == 0) return DPCHENGFMNCTTYRECDATA;
	else if (s.compare("dpchengfmncttyrlv1nstepdata") == 0) return DPCHENGFMNCTTYRLV1NSTEPDATA;
	else if (s.compare("dpchengfmncttysup1ntooltypedata") == 0) return DPCHENGFMNCTTYSUP1NTOOLTYPEDATA;
	else if (s.compare("dpchengfmncusgaaccessdata") == 0) return DPCHENGFMNCUSGAACCESSDATA;
	else if (s.compare("dpchengfmncusgdata") == 0) return DPCHENGFMNCUSGDATA;
	else if (s.compare("dpchengfmncusgdetaildata") == 0) return DPCHENGFMNCUSGDETAILDATA;
	else if (s.compare("dpchengfmncusgheadbardata") == 0) return DPCHENGFMNCUSGHEADBARDATA;
	else if (s.compare("dpchengfmncusglistdata") == 0) return DPCHENGFMNCUSGLISTDATA;
	else if (s.compare("dpchengfmncusgmnuserdata") == 0) return DPCHENGFMNCUSGMNUSERDATA;
	else if (s.compare("dpchengfmncusgrecdata") == 0) return DPCHENGFMNCUSGRECDATA;
	else if (s.compare("dpchengfmncusr1nsessiondata") == 0) return DPCHENGFMNCUSR1NSESSIONDATA;
	else if (s.compare("dpchengfmncusraaccessdata") == 0) return DPCHENGFMNCUSRAACCESSDATA;
	else if (s.compare("dpchengfmncusrdata") == 0) return DPCHENGFMNCUSRDATA;
	else if (s.compare("dpchengfmncusrdetaildata") == 0) return DPCHENGFMNCUSRDETAILDATA;
	else if (s.compare("dpchengfmncusrheadbardata") == 0) return DPCHENGFMNCUSRHEADBARDATA;
	else if (s.compare("dpchengfmncusrlistdata") == 0) return DPCHENGFMNCUSRLISTDATA;
	else if (s.compare("dpchengfmncusrmnusergroupdata") == 0) return DPCHENGFMNCUSRMNUSERGROUPDATA;
	else if (s.compare("dpchengfmncusrrecdata") == 0) return DPCHENGFMNCUSRRECDATA;
	else if (s.compare("dpchengsessfmncdata") == 0) return DPCHENGSESSFMNCDATA;
	else if (s.compare("dpchappdlgfmncactnewdata") == 0) return DPCHAPPDLGFMNCACTNEWDATA;
	else if (s.compare("dpchappdlgfmncactnewdo") == 0) return DPCHAPPDLGFMNCACTNEWDO;
	else if (s.compare("dpchappdlgfmncfabexpfabdata") == 0) return DPCHAPPDLGFMNCFABEXPFABDATA;
	else if (s.compare("dpchappdlgfmncfabexpfabdo") == 0) return DPCHAPPDLGFMNCFABEXPFABDO;
	else if (s.compare("dpchappdlgfmncfabimpfabdata") == 0) return DPCHAPPDLGFMNCFABIMPFABDATA;
	else if (s.compare("dpchappdlgfmncfabimpfabdo") == 0) return DPCHAPPDLGFMNCFABIMPFABDO;
	else if (s.compare("dpchappdlgfmncfabnewdata") == 0) return DPCHAPPDLGFMNCFABNEWDATA;
	else if (s.compare("dpchappdlgfmncfabnewdo") == 0) return DPCHAPPDLGFMNCFABNEWDO;
	else if (s.compare("dpchappdlgfmncnavloainidata") == 0) return DPCHAPPDLGFMNCNAVLOAINIDATA;
	else if (s.compare("dpchappdlgfmncnavloainido") == 0) return DPCHAPPDLGFMNCNAVLOAINIDO;
	else if (s.compare("dpchappdlgfmncorgexporgdata") == 0) return DPCHAPPDLGFMNCORGEXPORGDATA;
	else if (s.compare("dpchappdlgfmncorgexporgdo") == 0) return DPCHAPPDLGFMNCORGEXPORGDO;
	else if (s.compare("dpchappdlgfmncorgimporgdata") == 0) return DPCHAPPDLGFMNCORGIMPORGDATA;
	else if (s.compare("dpchappdlgfmncorgimporgdo") == 0) return DPCHAPPDLGFMNCORGIMPORGDO;
	else if (s.compare("dpchappdlgfmncorgnewdata") == 0) return DPCHAPPDLGFMNCORGNEWDATA;
	else if (s.compare("dpchappdlgfmncorgnewdo") == 0) return DPCHAPPDLGFMNCORGNEWDO;
	else if (s.compare("dpchappdlgfmncprjexpelbdata") == 0) return DPCHAPPDLGFMNCPRJEXPELBDATA;
	else if (s.compare("dpchappdlgfmncprjexpelbdo") == 0) return DPCHAPPDLGFMNCPRJEXPELBDO;
	else if (s.compare("dpchappdlgfmncprjimpelbdata") == 0) return DPCHAPPDLGFMNCPRJIMPELBDATA;
	else if (s.compare("dpchappdlgfmncprjimpelbdo") == 0) return DPCHAPPDLGFMNCPRJIMPELBDO;
	else if (s.compare("dpchappdlgfmncprjnewdata") == 0) return DPCHAPPDLGFMNCPRJNEWDATA;
	else if (s.compare("dpchappdlgfmncprjnewdo") == 0) return DPCHAPPDLGFMNCPRJNEWDO;
	else if (s.compare("dpchappdlgfmncrungenrepdata") == 0) return DPCHAPPDLGFMNCRUNGENREPDATA;
	else if (s.compare("dpchappdlgfmncrungenrepdo") == 0) return DPCHAPPDLGFMNCRUNGENREPDO;
	else if (s.compare("dpchappdlgfmncrunnewdata") == 0) return DPCHAPPDLGFMNCRUNNEWDATA;
	else if (s.compare("dpchappdlgfmncrunnewdo") == 0) return DPCHAPPDLGFMNCRUNNEWDO;
	else if (s.compare("dpchappdlgfmncsmpgenrepdata") == 0) return DPCHAPPDLGFMNCSMPGENREPDATA;
	else if (s.compare("dpchappdlgfmncsmpgenrepdo") == 0) return DPCHAPPDLGFMNCSMPGENREPDO;
	else if (s.compare("dpchappdlgfmncsmpnewdata") == 0) return DPCHAPPDLGFMNCSMPNEWDATA;
	else if (s.compare("dpchappdlgfmncsmpnewdo") == 0) return DPCHAPPDLGFMNCSMPNEWDO;
	else if (s.compare("dpchappfmncact1nstepdata") == 0) return DPCHAPPFMNCACT1NSTEPDATA;
	else if (s.compare("dpchappfmncact1nstepdo") == 0) return DPCHAPPFMNCACT1NSTEPDO;
	else if (s.compare("dpchappfmncactdetaildata") == 0) return DPCHAPPFMNCACTDETAILDATA;
	else if (s.compare("dpchappfmncactdetaildo") == 0) return DPCHAPPFMNCACTDETAILDO;
	else if (s.compare("dpchappfmncactdo") == 0) return DPCHAPPFMNCACTDO;
	else if (s.compare("dpchappfmncactlistdata") == 0) return DPCHAPPFMNCACTLISTDATA;
	else if (s.compare("dpchappfmncactlistdo") == 0) return DPCHAPPFMNCACTLISTDO;
	else if (s.compare("dpchappfmncactrecdo") == 0) return DPCHAPPFMNCACTRECDO;
	else if (s.compare("dpchappfmncadrdetaildata") == 0) return DPCHAPPFMNCADRDETAILDATA;
	else if (s.compare("dpchappfmncadrdetaildo") == 0) return DPCHAPPFMNCADRDETAILDO;
	else if (s.compare("dpchappfmncadrdo") == 0) return DPCHAPPFMNCADRDO;
	else if (s.compare("dpchappfmncadrlistdata") == 0) return DPCHAPPFMNCADRLISTDATA;
	else if (s.compare("dpchappfmncadrlistdo") == 0) return DPCHAPPFMNCADRLISTDO;
	else if (s.compare("dpchappfmncadrrecdo") == 0) return DPCHAPPFMNCADRRECDO;
	else if (s.compare("dpchappfmncalert") == 0) return DPCHAPPFMNCALERT;
	else if (s.compare("dpchappfmncart1nsampledata") == 0) return DPCHAPPFMNCART1NSAMPLEDATA;
	else if (s.compare("dpchappfmncart1nsampledo") == 0) return DPCHAPPFMNCART1NSAMPLEDO;
	else if (s.compare("dpchappfmncart1nstockitemdata") == 0) return DPCHAPPFMNCART1NSTOCKITEMDATA;
	else if (s.compare("dpchappfmncart1nstockitemdo") == 0) return DPCHAPPFMNCART1NSTOCKITEMDO;
	else if (s.compare("dpchappfmncartdetaildata") == 0) return DPCHAPPFMNCARTDETAILDATA;
	else if (s.compare("dpchappfmncartdetaildo") == 0) return DPCHAPPFMNCARTDETAILDO;
	else if (s.compare("dpchappfmncartdo") == 0) return DPCHAPPFMNCARTDO;
	else if (s.compare("dpchappfmncartlistdata") == 0) return DPCHAPPFMNCARTLISTDATA;
	else if (s.compare("dpchappfmncartlistdo") == 0) return DPCHAPPFMNCARTLISTDO;
	else if (s.compare("dpchappfmncartmnorgdata") == 0) return DPCHAPPFMNCARTMNORGDATA;
	else if (s.compare("dpchappfmncartmnorgdo") == 0) return DPCHAPPFMNCARTMNORGDO;
	else if (s.compare("dpchappfmncartrecdo") == 0) return DPCHAPPFMNCARTRECDO;
	else if (s.compare("dpchappfmncartref1nfiledata") == 0) return DPCHAPPFMNCARTREF1NFILEDATA;
	else if (s.compare("dpchappfmncartref1nfiledo") == 0) return DPCHAPPFMNCARTREF1NFILEDO;
	else if (s.compare("dpchappfmncbilaposdata") == 0) return DPCHAPPFMNCBILAPOSDATA;
	else if (s.compare("dpchappfmncbilaposdo") == 0) return DPCHAPPFMNCBILAPOSDO;
	else if (s.compare("dpchappfmncbildetaildata") == 0) return DPCHAPPFMNCBILDETAILDATA;
	else if (s.compare("dpchappfmncbildetaildo") == 0) return DPCHAPPFMNCBILDETAILDO;
	else if (s.compare("dpchappfmncbildo") == 0) return DPCHAPPFMNCBILDO;
	else if (s.compare("dpchappfmncbillistdata") == 0) return DPCHAPPFMNCBILLISTDATA;
	else if (s.compare("dpchappfmncbillistdo") == 0) return DPCHAPPFMNCBILLISTDO;
	else if (s.compare("dpchappfmncbilrecdo") == 0) return DPCHAPPFMNCBILRECDO;
	else if (s.compare("dpchappfmncfab1nfabprojectdata") == 0) return DPCHAPPFMNCFAB1NFABPROJECTDATA;
	else if (s.compare("dpchappfmncfab1nfabprojectdo") == 0) return DPCHAPPFMNCFAB1NFABPROJECTDO;
	else if (s.compare("dpchappfmncfab1nfabuserdata") == 0) return DPCHAPPFMNCFAB1NFABUSERDATA;
	else if (s.compare("dpchappfmncfab1nfabuserdo") == 0) return DPCHAPPFMNCFAB1NFABUSERDO;
	else if (s.compare("dpchappfmncfabdetaildo") == 0) return DPCHAPPFMNCFABDETAILDO;
	else if (s.compare("dpchappfmncfabdo") == 0) return DPCHAPPFMNCFABDO;
	else if (s.compare("dpchappfmncfabfab1ntooldata") == 0) return DPCHAPPFMNCFABFAB1NTOOLDATA;
	else if (s.compare("dpchappfmncfabfab1ntooldo") == 0) return DPCHAPPFMNCFABFAB1NTOOLDO;
	else if (s.compare("dpchappfmncfablistdata") == 0) return DPCHAPPFMNCFABLISTDATA;
	else if (s.compare("dpchappfmncfablistdo") == 0) return DPCHAPPFMNCFABLISTDO;
	else if (s.compare("dpchappfmncfabmnrundata") == 0) return DPCHAPPFMNCFABMNRUNDATA;
	else if (s.compare("dpchappfmncfabmnrundo") == 0) return DPCHAPPFMNCFABMNRUNDO;
	else if (s.compare("dpchappfmncfabrecdo") == 0) return DPCHAPPFMNCFABRECDO;
	else if (s.compare("dpchappfmncfildetaildata") == 0) return DPCHAPPFMNCFILDETAILDATA;
	else if (s.compare("dpchappfmncfildetaildo") == 0) return DPCHAPPFMNCFILDETAILDO;
	else if (s.compare("dpchappfmncfildo") == 0) return DPCHAPPFMNCFILDO;
	else if (s.compare("dpchappfmncfillistdata") == 0) return DPCHAPPFMNCFILLISTDATA;
	else if (s.compare("dpchappfmncfillistdo") == 0) return DPCHAPPFMNCFILLISTDO;
	else if (s.compare("dpchappfmncfilmnsampledata") == 0) return DPCHAPPFMNCFILMNSAMPLEDATA;
	else if (s.compare("dpchappfmncfilmnsampledo") == 0) return DPCHAPPFMNCFILMNSAMPLEDO;
	else if (s.compare("dpchappfmncfilmnstepdata") == 0) return DPCHAPPFMNCFILMNSTEPDATA;
	else if (s.compare("dpchappfmncfilmnstepdo") == 0) return DPCHAPPFMNCFILMNSTEPDO;
	else if (s.compare("dpchappfmncfilrecdo") == 0) return DPCHAPPFMNCFILRECDO;
	else if (s.compare("dpchappfmncfpj1nbilldata") == 0) return DPCHAPPFMNCFPJ1NBILLDATA;
	else if (s.compare("dpchappfmncfpj1nbilldo") == 0) return DPCHAPPFMNCFPJ1NBILLDO;
	else if (s.compare("dpchappfmncfpjdetaildata") == 0) return DPCHAPPFMNCFPJDETAILDATA;
	else if (s.compare("dpchappfmncfpjdetaildo") == 0) return DPCHAPPFMNCFPJDETAILDO;
	else if (s.compare("dpchappfmncfpjdo") == 0) return DPCHAPPFMNCFPJDO;
	else if (s.compare("dpchappfmncfpjlistdata") == 0) return DPCHAPPFMNCFPJLISTDATA;
	else if (s.compare("dpchappfmncfpjlistdo") == 0) return DPCHAPPFMNCFPJLISTDO;
	else if (s.compare("dpchappfmncfpjmnfabuserdata") == 0) return DPCHAPPFMNCFPJMNFABUSERDATA;
	else if (s.compare("dpchappfmncfpjmnfabuserdo") == 0) return DPCHAPPFMNCFPJMNFABUSERDO;
	else if (s.compare("dpchappfmncfpjrecdo") == 0) return DPCHAPPFMNCFPJRECDO;
	else if (s.compare("dpchappfmncfusdetaildata") == 0) return DPCHAPPFMNCFUSDETAILDATA;
	else if (s.compare("dpchappfmncfusdetaildo") == 0) return DPCHAPPFMNCFUSDETAILDO;
	else if (s.compare("dpchappfmncfusdo") == 0) return DPCHAPPFMNCFUSDO;
	else if (s.compare("dpchappfmncfuslistdata") == 0) return DPCHAPPFMNCFUSLISTDATA;
	else if (s.compare("dpchappfmncfuslistdo") == 0) return DPCHAPPFMNCFUSLISTDO;
	else if (s.compare("dpchappfmncfusmnfabprojectdata") == 0) return DPCHAPPFMNCFUSMNFABPROJECTDATA;
	else if (s.compare("dpchappfmncfusmnfabprojectdo") == 0) return DPCHAPPFMNCFUSMNFABPROJECTDO;
	else if (s.compare("dpchappfmncfusmntooldata") == 0) return DPCHAPPFMNCFUSMNTOOLDATA;
	else if (s.compare("dpchappfmncfusmntooldo") == 0) return DPCHAPPFMNCFUSMNTOOLDO;
	else if (s.compare("dpchappfmncfusrecdo") == 0) return DPCHAPPFMNCFUSRECDO;
	else if (s.compare("dpchappfmncinit") == 0) return DPCHAPPFMNCINIT;
	else if (s.compare("dpchappfmncnavadmindata") == 0) return DPCHAPPFMNCNAVADMINDATA;
	else if (s.compare("dpchappfmncnavadmindo") == 0) return DPCHAPPFMNCNAVADMINDO;
	else if (s.compare("dpchappfmncnavdo") == 0) return DPCHAPPFMNCNAVDO;
	else if (s.compare("dpchappfmncnavfabmgmtdata") == 0) return DPCHAPPFMNCNAVFABMGMTDATA;
	else if (s.compare("dpchappfmncnavfabmgmtdo") == 0) return DPCHAPPFMNCNAVFABMGMTDO;
	else if (s.compare("dpchappfmncnavlabbookdata") == 0) return DPCHAPPFMNCNAVLABBOOKDATA;
	else if (s.compare("dpchappfmncnavlabbookdo") == 0) return DPCHAPPFMNCNAVLABBOOKDO;
	else if (s.compare("dpchappfmncnavpredo") == 0) return DPCHAPPFMNCNAVPREDO;
	else if (s.compare("dpchappfmncnavsupplydata") == 0) return DPCHAPPFMNCNAVSUPPLYDATA;
	else if (s.compare("dpchappfmncnavsupplydo") == 0) return DPCHAPPFMNCNAVSUPPLYDO;
	else if (s.compare("dpchappfmncorg1narticledata") == 0) return DPCHAPPFMNCORG1NARTICLEDATA;
	else if (s.compare("dpchappfmncorg1narticledo") == 0) return DPCHAPPFMNCORG1NARTICLEDO;
	else if (s.compare("dpchappfmncorg1nstockitemdata") == 0) return DPCHAPPFMNCORG1NSTOCKITEMDATA;
	else if (s.compare("dpchappfmncorg1nstockitemdo") == 0) return DPCHAPPFMNCORG1NSTOCKITEMDO;
	else if (s.compare("dpchappfmncorgadetaildata") == 0) return DPCHAPPFMNCORGADETAILDATA;
	else if (s.compare("dpchappfmncorgadetaildo") == 0) return DPCHAPPFMNCORGADETAILDO;
	else if (s.compare("dpchappfmncorgbio1nfabprojectdata") == 0) return DPCHAPPFMNCORGBIO1NFABPROJECTDATA;
	else if (s.compare("dpchappfmncorgbio1nfabprojectdo") == 0) return DPCHAPPFMNCORGBIO1NFABPROJECTDO;
	else if (s.compare("dpchappfmncorgdetaildata") == 0) return DPCHAPPFMNCORGDETAILDATA;
	else if (s.compare("dpchappfmncorgdetaildo") == 0) return DPCHAPPFMNCORGDETAILDO;
	else if (s.compare("dpchappfmncorgdo") == 0) return DPCHAPPFMNCORGDO;
	else if (s.compare("dpchappfmncorghk1naddressdata") == 0) return DPCHAPPFMNCORGHK1NADDRESSDATA;
	else if (s.compare("dpchappfmncorghk1naddressdo") == 0) return DPCHAPPFMNCORGHK1NADDRESSDO;
	else if (s.compare("dpchappfmncorgkstocklcndata") == 0) return DPCHAPPFMNCORGKSTOCKLCNDATA;
	else if (s.compare("dpchappfmncorgkstocklcndo") == 0) return DPCHAPPFMNCORGKSTOCKLCNDO;
	else if (s.compare("dpchappfmncorglistdata") == 0) return DPCHAPPFMNCORGLISTDATA;
	else if (s.compare("dpchappfmncorglistdo") == 0) return DPCHAPPFMNCORGLISTDO;
	else if (s.compare("dpchappfmncorgmnarticledata") == 0) return DPCHAPPFMNCORGMNARTICLEDATA;
	else if (s.compare("dpchappfmncorgmnarticledo") == 0) return DPCHAPPFMNCORGMNARTICLEDO;
	else if (s.compare("dpchappfmncorgmnf1ntooldata") == 0) return DPCHAPPFMNCORGMNF1NTOOLDATA;
	else if (s.compare("dpchappfmncorgmnf1ntooldo") == 0) return DPCHAPPFMNCORGMNF1NTOOLDO;
	else if (s.compare("dpchappfmncorgmnpersondata") == 0) return DPCHAPPFMNCORGMNPERSONDATA;
	else if (s.compare("dpchappfmncorgmnpersondo") == 0) return DPCHAPPFMNCORGMNPERSONDO;
	else if (s.compare("dpchappfmncorgpco1npurchorderdata") == 0) return DPCHAPPFMNCORGPCO1NPURCHORDERDATA;
	else if (s.compare("dpchappfmncorgpco1npurchorderdo") == 0) return DPCHAPPFMNCORGPCO1NPURCHORDERDO;
	else if (s.compare("dpchappfmncorgrecdo") == 0) return DPCHAPPFMNCORGRECDO;
	else if (s.compare("dpchappfmncorgspl1npurchorderdata") == 0) return DPCHAPPFMNCORGSPL1NPURCHORDERDATA;
	else if (s.compare("dpchappfmncorgspl1npurchorderdo") == 0) return DPCHAPPFMNCORGSPL1NPURCHORDERDO;
	else if (s.compare("dpchappfmncorgsup1norgdata") == 0) return DPCHAPPFMNCORGSUP1NORGDATA;
	else if (s.compare("dpchappfmncorgsup1norgdo") == 0) return DPCHAPPFMNCORGSUP1NORGDO;
	else if (s.compare("dpchappfmncorgsvcmntooldata") == 0) return DPCHAPPFMNCORGSVCMNTOOLDATA;
	else if (s.compare("dpchappfmncorgsvcmntooldo") == 0) return DPCHAPPFMNCORGSVCMNTOOLDO;
	else if (s.compare("dpchappfmncpcoaposdata") == 0) return DPCHAPPFMNCPCOAPOSDATA;
	else if (s.compare("dpchappfmncpcoaposdo") == 0) return DPCHAPPFMNCPCOAPOSDO;
	else if (s.compare("dpchappfmncpcodetaildata") == 0) return DPCHAPPFMNCPCODETAILDATA;
	else if (s.compare("dpchappfmncpcodetaildo") == 0) return DPCHAPPFMNCPCODETAILDO;
	else if (s.compare("dpchappfmncpcodo") == 0) return DPCHAPPFMNCPCODO;
	else if (s.compare("dpchappfmncpcolistdata") == 0) return DPCHAPPFMNCPCOLISTDATA;
	else if (s.compare("dpchappfmncpcolistdo") == 0) return DPCHAPPFMNCPCOLISTDO;
	else if (s.compare("dpchappfmncpcorecdo") == 0) return DPCHAPPFMNCPCORECDO;
	else if (s.compare("dpchappfmncprj1nrundata") == 0) return DPCHAPPFMNCPRJ1NRUNDATA;
	else if (s.compare("dpchappfmncprj1nrundo") == 0) return DPCHAPPFMNCPRJ1NRUNDO;
	else if (s.compare("dpchappfmncprjdetaildata") == 0) return DPCHAPPFMNCPRJDETAILDATA;
	else if (s.compare("dpchappfmncprjdetaildo") == 0) return DPCHAPPFMNCPRJDETAILDO;
	else if (s.compare("dpchappfmncprjdo") == 0) return DPCHAPPFMNCPRJDO;
	else if (s.compare("dpchappfmncprjlistdata") == 0) return DPCHAPPFMNCPRJLISTDATA;
	else if (s.compare("dpchappfmncprjlistdo") == 0) return DPCHAPPFMNCPRJLISTDO;
	else if (s.compare("dpchappfmncprjrecdo") == 0) return DPCHAPPFMNCPRJRECDO;
	else if (s.compare("dpchappfmncprsadetaildata") == 0) return DPCHAPPFMNCPRSADETAILDATA;
	else if (s.compare("dpchappfmncprsadetaildo") == 0) return DPCHAPPFMNCPRSADETAILDO;
	else if (s.compare("dpchappfmncprsdetaildata") == 0) return DPCHAPPFMNCPRSDETAILDATA;
	else if (s.compare("dpchappfmncprsdetaildo") == 0) return DPCHAPPFMNCPRSDETAILDO;
	else if (s.compare("dpchappfmncprsdo") == 0) return DPCHAPPFMNCPRSDO;
	else if (s.compare("dpchappfmncprshk1naddressdata") == 0) return DPCHAPPFMNCPRSHK1NADDRESSDATA;
	else if (s.compare("dpchappfmncprshk1naddressdo") == 0) return DPCHAPPFMNCPRSHK1NADDRESSDO;
	else if (s.compare("dpchappfmncprslistdata") == 0) return DPCHAPPFMNCPRSLISTDATA;
	else if (s.compare("dpchappfmncprslistdo") == 0) return DPCHAPPFMNCPRSLISTDO;
	else if (s.compare("dpchappfmncprsmnorgdata") == 0) return DPCHAPPFMNCPRSMNORGDATA;
	else if (s.compare("dpchappfmncprsmnorgdo") == 0) return DPCHAPPFMNCPRSMNORGDO;
	else if (s.compare("dpchappfmncprsmnrundata") == 0) return DPCHAPPFMNCPRSMNRUNDATA;
	else if (s.compare("dpchappfmncprsmnrundo") == 0) return DPCHAPPFMNCPRSMNRUNDO;
	else if (s.compare("dpchappfmncprsrecdo") == 0) return DPCHAPPFMNCPRSRECDO;
	else if (s.compare("dpchappfmncresume") == 0) return DPCHAPPFMNCRESUME;
	else if (s.compare("dpchappfmncrundetaildata") == 0) return DPCHAPPFMNCRUNDETAILDATA;
	else if (s.compare("dpchappfmncrundetaildo") == 0) return DPCHAPPFMNCRUNDETAILDO;
	else if (s.compare("dpchappfmncrundo") == 0) return DPCHAPPFMNCRUNDO;
	else if (s.compare("dpchappfmncrunlistdata") == 0) return DPCHAPPFMNCRUNLISTDATA;
	else if (s.compare("dpchappfmncrunlistdo") == 0) return DPCHAPPFMNCRUNLISTDO;
	else if (s.compare("dpchappfmncrunmnfabdata") == 0) return DPCHAPPFMNCRUNMNFABDATA;
	else if (s.compare("dpchappfmncrunmnfabdo") == 0) return DPCHAPPFMNCRUNMNFABDO;
	else if (s.compare("dpchappfmncrunmnpersondata") == 0) return DPCHAPPFMNCRUNMNPERSONDATA;
	else if (s.compare("dpchappfmncrunmnpersondo") == 0) return DPCHAPPFMNCRUNMNPERSONDO;
	else if (s.compare("dpchappfmncrunmnsampledata") == 0) return DPCHAPPFMNCRUNMNSAMPLEDATA;
	else if (s.compare("dpchappfmncrunmnsampledo") == 0) return DPCHAPPFMNCRUNMNSAMPLEDO;
	else if (s.compare("dpchappfmncrunrecdo") == 0) return DPCHAPPFMNCRUNRECDO;
	else if (s.compare("dpchappfmncrunref1nfiledata") == 0) return DPCHAPPFMNCRUNREF1NFILEDATA;
	else if (s.compare("dpchappfmncrunref1nfiledo") == 0) return DPCHAPPFMNCRUNREF1NFILEDO;
	else if (s.compare("dpchappfmncrunrun1nactivitydata") == 0) return DPCHAPPFMNCRUNRUN1NACTIVITYDATA;
	else if (s.compare("dpchappfmncrunrun1nactivitydo") == 0) return DPCHAPPFMNCRUNRUN1NACTIVITYDO;
	else if (s.compare("dpchappfmncsepapardata") == 0) return DPCHAPPFMNCSEPAPARDATA;
	else if (s.compare("dpchappfmncsepapardo") == 0) return DPCHAPPFMNCSEPAPARDO;
	else if (s.compare("dpchappfmncsepdetaildata") == 0) return DPCHAPPFMNCSEPDETAILDATA;
	else if (s.compare("dpchappfmncsepdetaildo") == 0) return DPCHAPPFMNCSEPDETAILDO;
	else if (s.compare("dpchappfmncsepdo") == 0) return DPCHAPPFMNCSEPDO;
	else if (s.compare("dpchappfmncseplistdata") == 0) return DPCHAPPFMNCSEPLISTDATA;
	else if (s.compare("dpchappfmncseplistdo") == 0) return DPCHAPPFMNCSEPLISTDO;
	else if (s.compare("dpchappfmncsepmnfiledata") == 0) return DPCHAPPFMNCSEPMNFILEDATA;
	else if (s.compare("dpchappfmncsepmnfiledo") == 0) return DPCHAPPFMNCSEPMNFILEDO;
	else if (s.compare("dpchappfmncsepmnsampledata") == 0) return DPCHAPPFMNCSEPMNSAMPLEDATA;
	else if (s.compare("dpchappfmncsepmnsampledo") == 0) return DPCHAPPFMNCSEPMNSAMPLEDO;
	else if (s.compare("dpchappfmncseprecdo") == 0) return DPCHAPPFMNCSEPRECDO;
	else if (s.compare("dpchappfmncsepref1nfiledata") == 0) return DPCHAPPFMNCSEPREF1NFILEDATA;
	else if (s.compare("dpchappfmncsepref1nfiledo") == 0) return DPCHAPPFMNCSEPREF1NFILEDO;
	else if (s.compare("dpchappfmncskidetaildata") == 0) return DPCHAPPFMNCSKIDETAILDATA;
	else if (s.compare("dpchappfmncskidetaildo") == 0) return DPCHAPPFMNCSKIDETAILDO;
	else if (s.compare("dpchappfmncskido") == 0) return DPCHAPPFMNCSKIDO;
	else if (s.compare("dpchappfmncskilistdata") == 0) return DPCHAPPFMNCSKILISTDATA;
	else if (s.compare("dpchappfmncskilistdo") == 0) return DPCHAPPFMNCSKILISTDO;
	else if (s.compare("dpchappfmncskirecdo") == 0) return DPCHAPPFMNCSKIRECDO;
	else if (s.compare("dpchappfmncsmpapardata") == 0) return DPCHAPPFMNCSMPAPARDATA;
	else if (s.compare("dpchappfmncsmpapardo") == 0) return DPCHAPPFMNCSMPAPARDO;
	else if (s.compare("dpchappfmncsmpdetaildata") == 0) return DPCHAPPFMNCSMPDETAILDATA;
	else if (s.compare("dpchappfmncsmpdetaildo") == 0) return DPCHAPPFMNCSMPDETAILDO;
	else if (s.compare("dpchappfmncsmpdo") == 0) return DPCHAPPFMNCSMPDO;
	else if (s.compare("dpchappfmncsmplistdata") == 0) return DPCHAPPFMNCSMPLISTDATA;
	else if (s.compare("dpchappfmncsmplistdo") == 0) return DPCHAPPFMNCSMPLISTDO;
	else if (s.compare("dpchappfmncsmpmnfiledata") == 0) return DPCHAPPFMNCSMPMNFILEDATA;
	else if (s.compare("dpchappfmncsmpmnfiledo") == 0) return DPCHAPPFMNCSMPMNFILEDO;
	else if (s.compare("dpchappfmncsmpmnrundata") == 0) return DPCHAPPFMNCSMPMNRUNDATA;
	else if (s.compare("dpchappfmncsmpmnrundo") == 0) return DPCHAPPFMNCSMPMNRUNDO;
	else if (s.compare("dpchappfmncsmpmnstepdata") == 0) return DPCHAPPFMNCSMPMNSTEPDATA;
	else if (s.compare("dpchappfmncsmpmnstepdo") == 0) return DPCHAPPFMNCSMPMNSTEPDO;
	else if (s.compare("dpchappfmncsmprecdo") == 0) return DPCHAPPFMNCSMPRECDO;
	else if (s.compare("dpchappfmncsmpref1nfiledata") == 0) return DPCHAPPFMNCSMPREF1NFILEDATA;
	else if (s.compare("dpchappfmncsmpref1nfiledo") == 0) return DPCHAPPFMNCSMPREF1NFILEDO;
	else if (s.compare("dpchappfmncsmpsup1nsampledata") == 0) return DPCHAPPFMNCSMPSUP1NSAMPLEDATA;
	else if (s.compare("dpchappfmncsmpsup1nsampledo") == 0) return DPCHAPPFMNCSMPSUP1NSAMPLEDO;
	else if (s.compare("dpchappfmncstpapardata") == 0) return DPCHAPPFMNCSTPAPARDATA;
	else if (s.compare("dpchappfmncstpapardo") == 0) return DPCHAPPFMNCSTPAPARDO;
	else if (s.compare("dpchappfmncstpdetaildata") == 0) return DPCHAPPFMNCSTPDETAILDATA;
	else if (s.compare("dpchappfmncstpdetaildo") == 0) return DPCHAPPFMNCSTPDETAILDO;
	else if (s.compare("dpchappfmncstpdo") == 0) return DPCHAPPFMNCSTPDO;
	else if (s.compare("dpchappfmncstpksteppardata") == 0) return DPCHAPPFMNCSTPKSTEPPARDATA;
	else if (s.compare("dpchappfmncstpksteppardo") == 0) return DPCHAPPFMNCSTPKSTEPPARDO;
	else if (s.compare("dpchappfmncstplistdata") == 0) return DPCHAPPFMNCSTPLISTDATA;
	else if (s.compare("dpchappfmncstplistdo") == 0) return DPCHAPPFMNCSTPLISTDO;
	else if (s.compare("dpchappfmncstpmnfiledata") == 0) return DPCHAPPFMNCSTPMNFILEDATA;
	else if (s.compare("dpchappfmncstpmnfiledo") == 0) return DPCHAPPFMNCSTPMNFILEDO;
	else if (s.compare("dpchappfmncstprecdo") == 0) return DPCHAPPFMNCSTPRECDO;
	else if (s.compare("dpchappfmncstpref1nfiledata") == 0) return DPCHAPPFMNCSTPREF1NFILEDATA;
	else if (s.compare("dpchappfmncstpref1nfiledo") == 0) return DPCHAPPFMNCSTPREF1NFILEDO;
	else if (s.compare("dpchappfmncstptpl1nstepdata") == 0) return DPCHAPPFMNCSTPTPL1NSTEPDATA;
	else if (s.compare("dpchappfmncstptpl1nstepdo") == 0) return DPCHAPPFMNCSTPTPL1NSTEPDO;
	else if (s.compare("dpchappfmnctol1narticledata") == 0) return DPCHAPPFMNCTOL1NARTICLEDATA;
	else if (s.compare("dpchappfmnctol1narticledo") == 0) return DPCHAPPFMNCTOL1NARTICLEDO;
	else if (s.compare("dpchappfmnctolaavldata") == 0) return DPCHAPPFMNCTOLAAVLDATA;
	else if (s.compare("dpchappfmnctolaavldo") == 0) return DPCHAPPFMNCTOLAAVLDO;
	else if (s.compare("dpchappfmnctolachardata") == 0) return DPCHAPPFMNCTOLACHARDATA;
	else if (s.compare("dpchappfmnctolachardo") == 0) return DPCHAPPFMNCTOLACHARDO;
	else if (s.compare("dpchappfmnctolaresdata") == 0) return DPCHAPPFMNCTOLARESDATA;
	else if (s.compare("dpchappfmnctolaresdo") == 0) return DPCHAPPFMNCTOLARESDO;
	else if (s.compare("dpchappfmnctolautildata") == 0) return DPCHAPPFMNCTOLAUTILDATA;
	else if (s.compare("dpchappfmnctolautildo") == 0) return DPCHAPPFMNCTOLAUTILDO;
	else if (s.compare("dpchappfmnctoldetaildata") == 0) return DPCHAPPFMNCTOLDETAILDATA;
	else if (s.compare("dpchappfmnctoldetaildo") == 0) return DPCHAPPFMNCTOLDETAILDO;
	else if (s.compare("dpchappfmnctoldo") == 0) return DPCHAPPFMNCTOLDO;
	else if (s.compare("dpchappfmnctolksteppardata") == 0) return DPCHAPPFMNCTOLKSTEPPARDATA;
	else if (s.compare("dpchappfmnctolksteppardo") == 0) return DPCHAPPFMNCTOLKSTEPPARDO;
	else if (s.compare("dpchappfmnctolktoolchardata") == 0) return DPCHAPPFMNCTOLKTOOLCHARDATA;
	else if (s.compare("dpchappfmnctolktoolchardo") == 0) return DPCHAPPFMNCTOLKTOOLCHARDO;
	else if (s.compare("dpchappfmnctollistdata") == 0) return DPCHAPPFMNCTOLLISTDATA;
	else if (s.compare("dpchappfmnctollistdo") == 0) return DPCHAPPFMNCTOLLISTDO;
	else if (s.compare("dpchappfmnctolmnfabuserdata") == 0) return DPCHAPPFMNCTOLMNFABUSERDATA;
	else if (s.compare("dpchappfmnctolmnfabuserdo") == 0) return DPCHAPPFMNCTOLMNFABUSERDO;
	else if (s.compare("dpchappfmnctolmntooltypedata") == 0) return DPCHAPPFMNCTOLMNTOOLTYPEDATA;
	else if (s.compare("dpchappfmnctolmntooltypedo") == 0) return DPCHAPPFMNCTOLMNTOOLTYPEDO;
	else if (s.compare("dpchappfmnctolrecdo") == 0) return DPCHAPPFMNCTOLRECDO;
	else if (s.compare("dpchappfmnctolref1nfiledata") == 0) return DPCHAPPFMNCTOLREF1NFILEDATA;
	else if (s.compare("dpchappfmnctolref1nfiledo") == 0) return DPCHAPPFMNCTOLREF1NFILEDO;
	else if (s.compare("dpchappfmnctolrlv1nstepdata") == 0) return DPCHAPPFMNCTOLRLV1NSTEPDATA;
	else if (s.compare("dpchappfmnctolrlv1nstepdo") == 0) return DPCHAPPFMNCTOLRLV1NSTEPDO;
	else if (s.compare("dpchappfmnctolsvcmnorgdata") == 0) return DPCHAPPFMNCTOLSVCMNORGDATA;
	else if (s.compare("dpchappfmnctolsvcmnorgdo") == 0) return DPCHAPPFMNCTOLSVCMNORGDO;
	else if (s.compare("dpchappfmncttydetaildata") == 0) return DPCHAPPFMNCTTYDETAILDATA;
	else if (s.compare("dpchappfmncttydetaildo") == 0) return DPCHAPPFMNCTTYDETAILDO;
	else if (s.compare("dpchappfmncttydo") == 0) return DPCHAPPFMNCTTYDO;
	else if (s.compare("dpchappfmncttyksteppardata") == 0) return DPCHAPPFMNCTTYKSTEPPARDATA;
	else if (s.compare("dpchappfmncttyksteppardo") == 0) return DPCHAPPFMNCTTYKSTEPPARDO;
	else if (s.compare("dpchappfmncttyktoolchardata") == 0) return DPCHAPPFMNCTTYKTOOLCHARDATA;
	else if (s.compare("dpchappfmncttyktoolchardo") == 0) return DPCHAPPFMNCTTYKTOOLCHARDO;
	else if (s.compare("dpchappfmncttylistdata") == 0) return DPCHAPPFMNCTTYLISTDATA;
	else if (s.compare("dpchappfmncttylistdo") == 0) return DPCHAPPFMNCTTYLISTDO;
	else if (s.compare("dpchappfmncttymntooldata") == 0) return DPCHAPPFMNCTTYMNTOOLDATA;
	else if (s.compare("dpchappfmncttymntooldo") == 0) return DPCHAPPFMNCTTYMNTOOLDO;
	else if (s.compare("dpchappfmncttyrecdo") == 0) return DPCHAPPFMNCTTYRECDO;
	else if (s.compare("dpchappfmncttyrlv1nstepdata") == 0) return DPCHAPPFMNCTTYRLV1NSTEPDATA;
	else if (s.compare("dpchappfmncttyrlv1nstepdo") == 0) return DPCHAPPFMNCTTYRLV1NSTEPDO;
	else if (s.compare("dpchappfmncttysup1ntooltypedata") == 0) return DPCHAPPFMNCTTYSUP1NTOOLTYPEDATA;
	else if (s.compare("dpchappfmncttysup1ntooltypedo") == 0) return DPCHAPPFMNCTTYSUP1NTOOLTYPEDO;
	else if (s.compare("dpchappfmncusgaaccessdata") == 0) return DPCHAPPFMNCUSGAACCESSDATA;
	else if (s.compare("dpchappfmncusgaaccessdo") == 0) return DPCHAPPFMNCUSGAACCESSDO;
	else if (s.compare("dpchappfmncusgdetaildata") == 0) return DPCHAPPFMNCUSGDETAILDATA;
	else if (s.compare("dpchappfmncusgdetaildo") == 0) return DPCHAPPFMNCUSGDETAILDO;
	else if (s.compare("dpchappfmncusgdo") == 0) return DPCHAPPFMNCUSGDO;
	else if (s.compare("dpchappfmncusglistdata") == 0) return DPCHAPPFMNCUSGLISTDATA;
	else if (s.compare("dpchappfmncusglistdo") == 0) return DPCHAPPFMNCUSGLISTDO;
	else if (s.compare("dpchappfmncusgmnuserdata") == 0) return DPCHAPPFMNCUSGMNUSERDATA;
	else if (s.compare("dpchappfmncusgmnuserdo") == 0) return DPCHAPPFMNCUSGMNUSERDO;
	else if (s.compare("dpchappfmncusgrecdo") == 0) return DPCHAPPFMNCUSGRECDO;
	else if (s.compare("dpchappfmncusr1nsessiondata") == 0) return DPCHAPPFMNCUSR1NSESSIONDATA;
	else if (s.compare("dpchappfmncusr1nsessiondo") == 0) return DPCHAPPFMNCUSR1NSESSIONDO;
	else if (s.compare("dpchappfmncusraaccessdata") == 0) return DPCHAPPFMNCUSRAACCESSDATA;
	else if (s.compare("dpchappfmncusraaccessdo") == 0) return DPCHAPPFMNCUSRAACCESSDO;
	else if (s.compare("dpchappfmncusrdetaildata") == 0) return DPCHAPPFMNCUSRDETAILDATA;
	else if (s.compare("dpchappfmncusrdetaildo") == 0) return DPCHAPPFMNCUSRDETAILDO;
	else if (s.compare("dpchappfmncusrdo") == 0) return DPCHAPPFMNCUSRDO;
	else if (s.compare("dpchappfmncusrlistdata") == 0) return DPCHAPPFMNCUSRLISTDATA;
	else if (s.compare("dpchappfmncusrlistdo") == 0) return DPCHAPPFMNCUSRLISTDO;
	else if (s.compare("dpchappfmncusrmnusergroupdata") == 0) return DPCHAPPFMNCUSRMNUSERGROUPDATA;
	else if (s.compare("dpchappfmncusrmnusergroupdo") == 0) return DPCHAPPFMNCUSRMNUSERGROUPDO;
	else if (s.compare("dpchappfmncusrrecdo") == 0) return DPCHAPPFMNCUSRRECDO;
	else if (s.compare("dpchapprootfmnclogin") == 0) return DPCHAPPROOTFMNCLOGIN;

	return(0);
};

string VecFmncVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHENGDLGFMNCACTNEWDATA) return("DpchEngDlgFmncActNewData");
	else if (ix == DPCHENGDLGFMNCFABEXPFABDATA) return("DpchEngDlgFmncFabExpfabData");
	else if (ix == DPCHENGDLGFMNCFABIMPFABDATA) return("DpchEngDlgFmncFabImpfabData");
	else if (ix == DPCHENGDLGFMNCFABNEWDATA) return("DpchEngDlgFmncFabNewData");
	else if (ix == DPCHENGDLGFMNCNAVLOAINIDATA) return("DpchEngDlgFmncNavLoainiData");
	else if (ix == DPCHENGDLGFMNCORGEXPORGDATA) return("DpchEngDlgFmncOrgExporgData");
	else if (ix == DPCHENGDLGFMNCORGIMPORGDATA) return("DpchEngDlgFmncOrgImporgData");
	else if (ix == DPCHENGDLGFMNCORGNEWDATA) return("DpchEngDlgFmncOrgNewData");
	else if (ix == DPCHENGDLGFMNCPRJEXPELBDATA) return("DpchEngDlgFmncPrjExpelbData");
	else if (ix == DPCHENGDLGFMNCPRJIMPELBDATA) return("DpchEngDlgFmncPrjImpelbData");
	else if (ix == DPCHENGDLGFMNCPRJNEWDATA) return("DpchEngDlgFmncPrjNewData");
	else if (ix == DPCHENGDLGFMNCRUNGENREPDATA) return("DpchEngDlgFmncRunGenrepData");
	else if (ix == DPCHENGDLGFMNCRUNNEWDATA) return("DpchEngDlgFmncRunNewData");
	else if (ix == DPCHENGDLGFMNCSMPGENREPDATA) return("DpchEngDlgFmncSmpGenrepData");
	else if (ix == DPCHENGDLGFMNCSMPNEWDATA) return("DpchEngDlgFmncSmpNewData");
	else if (ix == DPCHENGFMNCACK) return("DpchEngFmncAck");
	else if (ix == DPCHENGFMNCACT1NSTEPDATA) return("DpchEngFmncAct1NStepData");
	else if (ix == DPCHENGFMNCACTDATA) return("DpchEngFmncActData");
	else if (ix == DPCHENGFMNCACTDETAILDATA) return("DpchEngFmncActDetailData");
	else if (ix == DPCHENGFMNCACTHEADBARDATA) return("DpchEngFmncActHeadbarData");
	else if (ix == DPCHENGFMNCACTLISTDATA) return("DpchEngFmncActListData");
	else if (ix == DPCHENGFMNCACTRECDATA) return("DpchEngFmncActRecData");
	else if (ix == DPCHENGFMNCADRDATA) return("DpchEngFmncAdrData");
	else if (ix == DPCHENGFMNCADRDETAILDATA) return("DpchEngFmncAdrDetailData");
	else if (ix == DPCHENGFMNCADRHEADBARDATA) return("DpchEngFmncAdrHeadbarData");
	else if (ix == DPCHENGFMNCADRLISTDATA) return("DpchEngFmncAdrListData");
	else if (ix == DPCHENGFMNCADRRECDATA) return("DpchEngFmncAdrRecData");
	else if (ix == DPCHENGFMNCALERT) return("DpchEngFmncAlert");
	else if (ix == DPCHENGFMNCART1NSAMPLEDATA) return("DpchEngFmncArt1NSampleData");
	else if (ix == DPCHENGFMNCART1NSTOCKITEMDATA) return("DpchEngFmncArt1NStockitemData");
	else if (ix == DPCHENGFMNCARTDATA) return("DpchEngFmncArtData");
	else if (ix == DPCHENGFMNCARTDETAILDATA) return("DpchEngFmncArtDetailData");
	else if (ix == DPCHENGFMNCARTHEADBARDATA) return("DpchEngFmncArtHeadbarData");
	else if (ix == DPCHENGFMNCARTLISTDATA) return("DpchEngFmncArtListData");
	else if (ix == DPCHENGFMNCARTMNORGDATA) return("DpchEngFmncArtMNOrgData");
	else if (ix == DPCHENGFMNCARTRECDATA) return("DpchEngFmncArtRecData");
	else if (ix == DPCHENGFMNCARTREF1NFILEDATA) return("DpchEngFmncArtRef1NFileData");
	else if (ix == DPCHENGFMNCBILAPOSDATA) return("DpchEngFmncBilAPosData");
	else if (ix == DPCHENGFMNCBILDATA) return("DpchEngFmncBilData");
	else if (ix == DPCHENGFMNCBILDETAILDATA) return("DpchEngFmncBilDetailData");
	else if (ix == DPCHENGFMNCBILHEADBARDATA) return("DpchEngFmncBilHeadbarData");
	else if (ix == DPCHENGFMNCBILLISTDATA) return("DpchEngFmncBilListData");
	else if (ix == DPCHENGFMNCBILRECDATA) return("DpchEngFmncBilRecData");
	else if (ix == DPCHENGFMNCCONFIRM) return("DpchEngFmncConfirm");
	else if (ix == DPCHENGFMNCFAB1NFABPROJECTDATA) return("DpchEngFmncFab1NFabprojectData");
	else if (ix == DPCHENGFMNCFAB1NFABUSERDATA) return("DpchEngFmncFab1NFabuserData");
	else if (ix == DPCHENGFMNCFABDATA) return("DpchEngFmncFabData");
	else if (ix == DPCHENGFMNCFABDETAILDATA) return("DpchEngFmncFabDetailData");
	else if (ix == DPCHENGFMNCFABFAB1NTOOLDATA) return("DpchEngFmncFabFab1NToolData");
	else if (ix == DPCHENGFMNCFABHEADBARDATA) return("DpchEngFmncFabHeadbarData");
	else if (ix == DPCHENGFMNCFABLISTDATA) return("DpchEngFmncFabListData");
	else if (ix == DPCHENGFMNCFABMNRUNDATA) return("DpchEngFmncFabMNRunData");
	else if (ix == DPCHENGFMNCFABRECDATA) return("DpchEngFmncFabRecData");
	else if (ix == DPCHENGFMNCFILDATA) return("DpchEngFmncFilData");
	else if (ix == DPCHENGFMNCFILDETAILDATA) return("DpchEngFmncFilDetailData");
	else if (ix == DPCHENGFMNCFILHEADBARDATA) return("DpchEngFmncFilHeadbarData");
	else if (ix == DPCHENGFMNCFILLISTDATA) return("DpchEngFmncFilListData");
	else if (ix == DPCHENGFMNCFILMNSAMPLEDATA) return("DpchEngFmncFilMNSampleData");
	else if (ix == DPCHENGFMNCFILMNSTEPDATA) return("DpchEngFmncFilMNStepData");
	else if (ix == DPCHENGFMNCFILRECDATA) return("DpchEngFmncFilRecData");
	else if (ix == DPCHENGFMNCFPJ1NBILLDATA) return("DpchEngFmncFpj1NBillData");
	else if (ix == DPCHENGFMNCFPJDATA) return("DpchEngFmncFpjData");
	else if (ix == DPCHENGFMNCFPJDETAILDATA) return("DpchEngFmncFpjDetailData");
	else if (ix == DPCHENGFMNCFPJHEADBARDATA) return("DpchEngFmncFpjHeadbarData");
	else if (ix == DPCHENGFMNCFPJLISTDATA) return("DpchEngFmncFpjListData");
	else if (ix == DPCHENGFMNCFPJMNFABUSERDATA) return("DpchEngFmncFpjMNFabuserData");
	else if (ix == DPCHENGFMNCFPJRECDATA) return("DpchEngFmncFpjRecData");
	else if (ix == DPCHENGFMNCFUSDATA) return("DpchEngFmncFusData");
	else if (ix == DPCHENGFMNCFUSDETAILDATA) return("DpchEngFmncFusDetailData");
	else if (ix == DPCHENGFMNCFUSHEADBARDATA) return("DpchEngFmncFusHeadbarData");
	else if (ix == DPCHENGFMNCFUSLISTDATA) return("DpchEngFmncFusListData");
	else if (ix == DPCHENGFMNCFUSMNFABPROJECTDATA) return("DpchEngFmncFusMNFabprojectData");
	else if (ix == DPCHENGFMNCFUSMNTOOLDATA) return("DpchEngFmncFusMNToolData");
	else if (ix == DPCHENGFMNCFUSRECDATA) return("DpchEngFmncFusRecData");
	else if (ix == DPCHENGFMNCNAVADMINDATA) return("DpchEngFmncNavAdminData");
	else if (ix == DPCHENGFMNCNAVDATA) return("DpchEngFmncNavData");
	else if (ix == DPCHENGFMNCNAVFABMGMTDATA) return("DpchEngFmncNavFabmgmtData");
	else if (ix == DPCHENGFMNCNAVHEADBARDATA) return("DpchEngFmncNavHeadbarData");
	else if (ix == DPCHENGFMNCNAVLABBOOKDATA) return("DpchEngFmncNavLabbookData");
	else if (ix == DPCHENGFMNCNAVPREDATA) return("DpchEngFmncNavPreData");
	else if (ix == DPCHENGFMNCNAVSUPPLYDATA) return("DpchEngFmncNavSupplyData");
	else if (ix == DPCHENGFMNCORG1NARTICLEDATA) return("DpchEngFmncOrg1NArticleData");
	else if (ix == DPCHENGFMNCORG1NSTOCKITEMDATA) return("DpchEngFmncOrg1NStockitemData");
	else if (ix == DPCHENGFMNCORGADETAILDATA) return("DpchEngFmncOrgADetailData");
	else if (ix == DPCHENGFMNCORGBIO1NFABPROJECTDATA) return("DpchEngFmncOrgBio1NFabprojectData");
	else if (ix == DPCHENGFMNCORGDATA) return("DpchEngFmncOrgData");
	else if (ix == DPCHENGFMNCORGDETAILDATA) return("DpchEngFmncOrgDetailData");
	else if (ix == DPCHENGFMNCORGHEADBARDATA) return("DpchEngFmncOrgHeadbarData");
	else if (ix == DPCHENGFMNCORGHK1NADDRESSDATA) return("DpchEngFmncOrgHk1NAddressData");
	else if (ix == DPCHENGFMNCORGKSTOCKLCNDATA) return("DpchEngFmncOrgKStocklcnData");
	else if (ix == DPCHENGFMNCORGLISTDATA) return("DpchEngFmncOrgListData");
	else if (ix == DPCHENGFMNCORGMNARTICLEDATA) return("DpchEngFmncOrgMNArticleData");
	else if (ix == DPCHENGFMNCORGMNF1NTOOLDATA) return("DpchEngFmncOrgMnf1NToolData");
	else if (ix == DPCHENGFMNCORGMNPERSONDATA) return("DpchEngFmncOrgMNPersonData");
	else if (ix == DPCHENGFMNCORGPCO1NPURCHORDERDATA) return("DpchEngFmncOrgPco1NPurchorderData");
	else if (ix == DPCHENGFMNCORGRECDATA) return("DpchEngFmncOrgRecData");
	else if (ix == DPCHENGFMNCORGSPL1NPURCHORDERDATA) return("DpchEngFmncOrgSpl1NPurchorderData");
	else if (ix == DPCHENGFMNCORGSUP1NORGDATA) return("DpchEngFmncOrgSup1NOrgData");
	else if (ix == DPCHENGFMNCORGSVCMNTOOLDATA) return("DpchEngFmncOrgSvcMNToolData");
	else if (ix == DPCHENGFMNCPCOAPOSDATA) return("DpchEngFmncPcoAPosData");
	else if (ix == DPCHENGFMNCPCODATA) return("DpchEngFmncPcoData");
	else if (ix == DPCHENGFMNCPCODETAILDATA) return("DpchEngFmncPcoDetailData");
	else if (ix == DPCHENGFMNCPCOHEADBARDATA) return("DpchEngFmncPcoHeadbarData");
	else if (ix == DPCHENGFMNCPCOLISTDATA) return("DpchEngFmncPcoListData");
	else if (ix == DPCHENGFMNCPCORECDATA) return("DpchEngFmncPcoRecData");
	else if (ix == DPCHENGFMNCPRJ1NRUNDATA) return("DpchEngFmncPrj1NRunData");
	else if (ix == DPCHENGFMNCPRJDATA) return("DpchEngFmncPrjData");
	else if (ix == DPCHENGFMNCPRJDETAILDATA) return("DpchEngFmncPrjDetailData");
	else if (ix == DPCHENGFMNCPRJHEADBARDATA) return("DpchEngFmncPrjHeadbarData");
	else if (ix == DPCHENGFMNCPRJLISTDATA) return("DpchEngFmncPrjListData");
	else if (ix == DPCHENGFMNCPRJRECDATA) return("DpchEngFmncPrjRecData");
	else if (ix == DPCHENGFMNCPRSADETAILDATA) return("DpchEngFmncPrsADetailData");
	else if (ix == DPCHENGFMNCPRSDATA) return("DpchEngFmncPrsData");
	else if (ix == DPCHENGFMNCPRSDETAILDATA) return("DpchEngFmncPrsDetailData");
	else if (ix == DPCHENGFMNCPRSHEADBARDATA) return("DpchEngFmncPrsHeadbarData");
	else if (ix == DPCHENGFMNCPRSHK1NADDRESSDATA) return("DpchEngFmncPrsHk1NAddressData");
	else if (ix == DPCHENGFMNCPRSLISTDATA) return("DpchEngFmncPrsListData");
	else if (ix == DPCHENGFMNCPRSMNORGDATA) return("DpchEngFmncPrsMNOrgData");
	else if (ix == DPCHENGFMNCPRSMNRUNDATA) return("DpchEngFmncPrsMNRunData");
	else if (ix == DPCHENGFMNCPRSRECDATA) return("DpchEngFmncPrsRecData");
	else if (ix == DPCHENGFMNCRUNDATA) return("DpchEngFmncRunData");
	else if (ix == DPCHENGFMNCRUNDETAILDATA) return("DpchEngFmncRunDetailData");
	else if (ix == DPCHENGFMNCRUNHEADBARDATA) return("DpchEngFmncRunHeadbarData");
	else if (ix == DPCHENGFMNCRUNLISTDATA) return("DpchEngFmncRunListData");
	else if (ix == DPCHENGFMNCRUNMNFABDATA) return("DpchEngFmncRunMNFabData");
	else if (ix == DPCHENGFMNCRUNMNPERSONDATA) return("DpchEngFmncRunMNPersonData");
	else if (ix == DPCHENGFMNCRUNMNSAMPLEDATA) return("DpchEngFmncRunMNSampleData");
	else if (ix == DPCHENGFMNCRUNRECDATA) return("DpchEngFmncRunRecData");
	else if (ix == DPCHENGFMNCRUNREF1NFILEDATA) return("DpchEngFmncRunRef1NFileData");
	else if (ix == DPCHENGFMNCRUNRUN1NACTIVITYDATA) return("DpchEngFmncRunRun1NActivityData");
	else if (ix == DPCHENGFMNCSEPAPARDATA) return("DpchEngFmncSepAParData");
	else if (ix == DPCHENGFMNCSEPDATA) return("DpchEngFmncSepData");
	else if (ix == DPCHENGFMNCSEPDETAILDATA) return("DpchEngFmncSepDetailData");
	else if (ix == DPCHENGFMNCSEPHEADBARDATA) return("DpchEngFmncSepHeadbarData");
	else if (ix == DPCHENGFMNCSEPLISTDATA) return("DpchEngFmncSepListData");
	else if (ix == DPCHENGFMNCSEPMNFILEDATA) return("DpchEngFmncSepMNFileData");
	else if (ix == DPCHENGFMNCSEPMNSAMPLEDATA) return("DpchEngFmncSepMNSampleData");
	else if (ix == DPCHENGFMNCSEPRECDATA) return("DpchEngFmncSepRecData");
	else if (ix == DPCHENGFMNCSEPREF1NFILEDATA) return("DpchEngFmncSepRef1NFileData");
	else if (ix == DPCHENGFMNCSKIDATA) return("DpchEngFmncSkiData");
	else if (ix == DPCHENGFMNCSKIDETAILDATA) return("DpchEngFmncSkiDetailData");
	else if (ix == DPCHENGFMNCSKIHEADBARDATA) return("DpchEngFmncSkiHeadbarData");
	else if (ix == DPCHENGFMNCSKILISTDATA) return("DpchEngFmncSkiListData");
	else if (ix == DPCHENGFMNCSKIRECDATA) return("DpchEngFmncSkiRecData");
	else if (ix == DPCHENGFMNCSMPAPARDATA) return("DpchEngFmncSmpAParData");
	else if (ix == DPCHENGFMNCSMPDATA) return("DpchEngFmncSmpData");
	else if (ix == DPCHENGFMNCSMPDETAILDATA) return("DpchEngFmncSmpDetailData");
	else if (ix == DPCHENGFMNCSMPHEADBARDATA) return("DpchEngFmncSmpHeadbarData");
	else if (ix == DPCHENGFMNCSMPLISTDATA) return("DpchEngFmncSmpListData");
	else if (ix == DPCHENGFMNCSMPMNFILEDATA) return("DpchEngFmncSmpMNFileData");
	else if (ix == DPCHENGFMNCSMPMNRUNDATA) return("DpchEngFmncSmpMNRunData");
	else if (ix == DPCHENGFMNCSMPMNSTEPDATA) return("DpchEngFmncSmpMNStepData");
	else if (ix == DPCHENGFMNCSMPRECDATA) return("DpchEngFmncSmpRecData");
	else if (ix == DPCHENGFMNCSMPREF1NFILEDATA) return("DpchEngFmncSmpRef1NFileData");
	else if (ix == DPCHENGFMNCSMPSUP1NSAMPLEDATA) return("DpchEngFmncSmpSup1NSampleData");
	else if (ix == DPCHENGFMNCSTPAPARDATA) return("DpchEngFmncStpAParData");
	else if (ix == DPCHENGFMNCSTPDATA) return("DpchEngFmncStpData");
	else if (ix == DPCHENGFMNCSTPDETAILDATA) return("DpchEngFmncStpDetailData");
	else if (ix == DPCHENGFMNCSTPHEADBARDATA) return("DpchEngFmncStpHeadbarData");
	else if (ix == DPCHENGFMNCSTPKSTEPPARDATA) return("DpchEngFmncStpKStepparData");
	else if (ix == DPCHENGFMNCSTPLISTDATA) return("DpchEngFmncStpListData");
	else if (ix == DPCHENGFMNCSTPMNFILEDATA) return("DpchEngFmncStpMNFileData");
	else if (ix == DPCHENGFMNCSTPRECDATA) return("DpchEngFmncStpRecData");
	else if (ix == DPCHENGFMNCSTPREF1NFILEDATA) return("DpchEngFmncStpRef1NFileData");
	else if (ix == DPCHENGFMNCSTPTPL1NSTEPDATA) return("DpchEngFmncStpTpl1NStepData");
	else if (ix == DPCHENGFMNCSUSPEND) return("DpchEngFmncSuspend");
	else if (ix == DPCHENGFMNCTOL1NARTICLEDATA) return("DpchEngFmncTol1NArticleData");
	else if (ix == DPCHENGFMNCTOLAAVLDATA) return("DpchEngFmncTolAAvlData");
	else if (ix == DPCHENGFMNCTOLACHARDATA) return("DpchEngFmncTolACharData");
	else if (ix == DPCHENGFMNCTOLARESDATA) return("DpchEngFmncTolAResData");
	else if (ix == DPCHENGFMNCTOLAUTILDATA) return("DpchEngFmncTolAUtilData");
	else if (ix == DPCHENGFMNCTOLDATA) return("DpchEngFmncTolData");
	else if (ix == DPCHENGFMNCTOLDETAILDATA) return("DpchEngFmncTolDetailData");
	else if (ix == DPCHENGFMNCTOLHEADBARDATA) return("DpchEngFmncTolHeadbarData");
	else if (ix == DPCHENGFMNCTOLKSTEPPARDATA) return("DpchEngFmncTolKStepparData");
	else if (ix == DPCHENGFMNCTOLKTOOLCHARDATA) return("DpchEngFmncTolKToolcharData");
	else if (ix == DPCHENGFMNCTOLLISTDATA) return("DpchEngFmncTolListData");
	else if (ix == DPCHENGFMNCTOLMNFABUSERDATA) return("DpchEngFmncTolMNFabuserData");
	else if (ix == DPCHENGFMNCTOLMNTOOLTYPEDATA) return("DpchEngFmncTolMNTooltypeData");
	else if (ix == DPCHENGFMNCTOLRECDATA) return("DpchEngFmncTolRecData");
	else if (ix == DPCHENGFMNCTOLREF1NFILEDATA) return("DpchEngFmncTolRef1NFileData");
	else if (ix == DPCHENGFMNCTOLRLV1NSTEPDATA) return("DpchEngFmncTolRlv1NStepData");
	else if (ix == DPCHENGFMNCTOLSVCMNORGDATA) return("DpchEngFmncTolSvcMNOrgData");
	else if (ix == DPCHENGFMNCTTYDATA) return("DpchEngFmncTtyData");
	else if (ix == DPCHENGFMNCTTYDETAILDATA) return("DpchEngFmncTtyDetailData");
	else if (ix == DPCHENGFMNCTTYHEADBARDATA) return("DpchEngFmncTtyHeadbarData");
	else if (ix == DPCHENGFMNCTTYKSTEPPARDATA) return("DpchEngFmncTtyKStepparData");
	else if (ix == DPCHENGFMNCTTYKTOOLCHARDATA) return("DpchEngFmncTtyKToolcharData");
	else if (ix == DPCHENGFMNCTTYLISTDATA) return("DpchEngFmncTtyListData");
	else if (ix == DPCHENGFMNCTTYMNTOOLDATA) return("DpchEngFmncTtyMNToolData");
	else if (ix == DPCHENGFMNCTTYRECDATA) return("DpchEngFmncTtyRecData");
	else if (ix == DPCHENGFMNCTTYRLV1NSTEPDATA) return("DpchEngFmncTtyRlv1NStepData");
	else if (ix == DPCHENGFMNCTTYSUP1NTOOLTYPEDATA) return("DpchEngFmncTtySup1NTooltypeData");
	else if (ix == DPCHENGFMNCUSGAACCESSDATA) return("DpchEngFmncUsgAAccessData");
	else if (ix == DPCHENGFMNCUSGDATA) return("DpchEngFmncUsgData");
	else if (ix == DPCHENGFMNCUSGDETAILDATA) return("DpchEngFmncUsgDetailData");
	else if (ix == DPCHENGFMNCUSGHEADBARDATA) return("DpchEngFmncUsgHeadbarData");
	else if (ix == DPCHENGFMNCUSGLISTDATA) return("DpchEngFmncUsgListData");
	else if (ix == DPCHENGFMNCUSGMNUSERDATA) return("DpchEngFmncUsgMNUserData");
	else if (ix == DPCHENGFMNCUSGRECDATA) return("DpchEngFmncUsgRecData");
	else if (ix == DPCHENGFMNCUSR1NSESSIONDATA) return("DpchEngFmncUsr1NSessionData");
	else if (ix == DPCHENGFMNCUSRAACCESSDATA) return("DpchEngFmncUsrAAccessData");
	else if (ix == DPCHENGFMNCUSRDATA) return("DpchEngFmncUsrData");
	else if (ix == DPCHENGFMNCUSRDETAILDATA) return("DpchEngFmncUsrDetailData");
	else if (ix == DPCHENGFMNCUSRHEADBARDATA) return("DpchEngFmncUsrHeadbarData");
	else if (ix == DPCHENGFMNCUSRLISTDATA) return("DpchEngFmncUsrListData");
	else if (ix == DPCHENGFMNCUSRMNUSERGROUPDATA) return("DpchEngFmncUsrMNUsergroupData");
	else if (ix == DPCHENGFMNCUSRRECDATA) return("DpchEngFmncUsrRecData");
	else if (ix == DPCHENGSESSFMNCDATA) return("DpchEngSessFmncData");
	else if (ix == DPCHAPPDLGFMNCACTNEWDATA) return("DpchAppDlgFmncActNewData");
	else if (ix == DPCHAPPDLGFMNCACTNEWDO) return("DpchAppDlgFmncActNewDo");
	else if (ix == DPCHAPPDLGFMNCFABEXPFABDATA) return("DpchAppDlgFmncFabExpfabData");
	else if (ix == DPCHAPPDLGFMNCFABEXPFABDO) return("DpchAppDlgFmncFabExpfabDo");
	else if (ix == DPCHAPPDLGFMNCFABIMPFABDATA) return("DpchAppDlgFmncFabImpfabData");
	else if (ix == DPCHAPPDLGFMNCFABIMPFABDO) return("DpchAppDlgFmncFabImpfabDo");
	else if (ix == DPCHAPPDLGFMNCFABNEWDATA) return("DpchAppDlgFmncFabNewData");
	else if (ix == DPCHAPPDLGFMNCFABNEWDO) return("DpchAppDlgFmncFabNewDo");
	else if (ix == DPCHAPPDLGFMNCNAVLOAINIDATA) return("DpchAppDlgFmncNavLoainiData");
	else if (ix == DPCHAPPDLGFMNCNAVLOAINIDO) return("DpchAppDlgFmncNavLoainiDo");
	else if (ix == DPCHAPPDLGFMNCORGEXPORGDATA) return("DpchAppDlgFmncOrgExporgData");
	else if (ix == DPCHAPPDLGFMNCORGEXPORGDO) return("DpchAppDlgFmncOrgExporgDo");
	else if (ix == DPCHAPPDLGFMNCORGIMPORGDATA) return("DpchAppDlgFmncOrgImporgData");
	else if (ix == DPCHAPPDLGFMNCORGIMPORGDO) return("DpchAppDlgFmncOrgImporgDo");
	else if (ix == DPCHAPPDLGFMNCORGNEWDATA) return("DpchAppDlgFmncOrgNewData");
	else if (ix == DPCHAPPDLGFMNCORGNEWDO) return("DpchAppDlgFmncOrgNewDo");
	else if (ix == DPCHAPPDLGFMNCPRJEXPELBDATA) return("DpchAppDlgFmncPrjExpelbData");
	else if (ix == DPCHAPPDLGFMNCPRJEXPELBDO) return("DpchAppDlgFmncPrjExpelbDo");
	else if (ix == DPCHAPPDLGFMNCPRJIMPELBDATA) return("DpchAppDlgFmncPrjImpelbData");
	else if (ix == DPCHAPPDLGFMNCPRJIMPELBDO) return("DpchAppDlgFmncPrjImpelbDo");
	else if (ix == DPCHAPPDLGFMNCPRJNEWDATA) return("DpchAppDlgFmncPrjNewData");
	else if (ix == DPCHAPPDLGFMNCPRJNEWDO) return("DpchAppDlgFmncPrjNewDo");
	else if (ix == DPCHAPPDLGFMNCRUNGENREPDATA) return("DpchAppDlgFmncRunGenrepData");
	else if (ix == DPCHAPPDLGFMNCRUNGENREPDO) return("DpchAppDlgFmncRunGenrepDo");
	else if (ix == DPCHAPPDLGFMNCRUNNEWDATA) return("DpchAppDlgFmncRunNewData");
	else if (ix == DPCHAPPDLGFMNCRUNNEWDO) return("DpchAppDlgFmncRunNewDo");
	else if (ix == DPCHAPPDLGFMNCSMPGENREPDATA) return("DpchAppDlgFmncSmpGenrepData");
	else if (ix == DPCHAPPDLGFMNCSMPGENREPDO) return("DpchAppDlgFmncSmpGenrepDo");
	else if (ix == DPCHAPPDLGFMNCSMPNEWDATA) return("DpchAppDlgFmncSmpNewData");
	else if (ix == DPCHAPPDLGFMNCSMPNEWDO) return("DpchAppDlgFmncSmpNewDo");
	else if (ix == DPCHAPPFMNCACT1NSTEPDATA) return("DpchAppFmncAct1NStepData");
	else if (ix == DPCHAPPFMNCACT1NSTEPDO) return("DpchAppFmncAct1NStepDo");
	else if (ix == DPCHAPPFMNCACTDETAILDATA) return("DpchAppFmncActDetailData");
	else if (ix == DPCHAPPFMNCACTDETAILDO) return("DpchAppFmncActDetailDo");
	else if (ix == DPCHAPPFMNCACTDO) return("DpchAppFmncActDo");
	else if (ix == DPCHAPPFMNCACTLISTDATA) return("DpchAppFmncActListData");
	else if (ix == DPCHAPPFMNCACTLISTDO) return("DpchAppFmncActListDo");
	else if (ix == DPCHAPPFMNCACTRECDO) return("DpchAppFmncActRecDo");
	else if (ix == DPCHAPPFMNCADRDETAILDATA) return("DpchAppFmncAdrDetailData");
	else if (ix == DPCHAPPFMNCADRDETAILDO) return("DpchAppFmncAdrDetailDo");
	else if (ix == DPCHAPPFMNCADRDO) return("DpchAppFmncAdrDo");
	else if (ix == DPCHAPPFMNCADRLISTDATA) return("DpchAppFmncAdrListData");
	else if (ix == DPCHAPPFMNCADRLISTDO) return("DpchAppFmncAdrListDo");
	else if (ix == DPCHAPPFMNCADRRECDO) return("DpchAppFmncAdrRecDo");
	else if (ix == DPCHAPPFMNCALERT) return("DpchAppFmncAlert");
	else if (ix == DPCHAPPFMNCART1NSAMPLEDATA) return("DpchAppFmncArt1NSampleData");
	else if (ix == DPCHAPPFMNCART1NSAMPLEDO) return("DpchAppFmncArt1NSampleDo");
	else if (ix == DPCHAPPFMNCART1NSTOCKITEMDATA) return("DpchAppFmncArt1NStockitemData");
	else if (ix == DPCHAPPFMNCART1NSTOCKITEMDO) return("DpchAppFmncArt1NStockitemDo");
	else if (ix == DPCHAPPFMNCARTDETAILDATA) return("DpchAppFmncArtDetailData");
	else if (ix == DPCHAPPFMNCARTDETAILDO) return("DpchAppFmncArtDetailDo");
	else if (ix == DPCHAPPFMNCARTDO) return("DpchAppFmncArtDo");
	else if (ix == DPCHAPPFMNCARTLISTDATA) return("DpchAppFmncArtListData");
	else if (ix == DPCHAPPFMNCARTLISTDO) return("DpchAppFmncArtListDo");
	else if (ix == DPCHAPPFMNCARTMNORGDATA) return("DpchAppFmncArtMNOrgData");
	else if (ix == DPCHAPPFMNCARTMNORGDO) return("DpchAppFmncArtMNOrgDo");
	else if (ix == DPCHAPPFMNCARTRECDO) return("DpchAppFmncArtRecDo");
	else if (ix == DPCHAPPFMNCARTREF1NFILEDATA) return("DpchAppFmncArtRef1NFileData");
	else if (ix == DPCHAPPFMNCARTREF1NFILEDO) return("DpchAppFmncArtRef1NFileDo");
	else if (ix == DPCHAPPFMNCBILAPOSDATA) return("DpchAppFmncBilAPosData");
	else if (ix == DPCHAPPFMNCBILAPOSDO) return("DpchAppFmncBilAPosDo");
	else if (ix == DPCHAPPFMNCBILDETAILDATA) return("DpchAppFmncBilDetailData");
	else if (ix == DPCHAPPFMNCBILDETAILDO) return("DpchAppFmncBilDetailDo");
	else if (ix == DPCHAPPFMNCBILDO) return("DpchAppFmncBilDo");
	else if (ix == DPCHAPPFMNCBILLISTDATA) return("DpchAppFmncBilListData");
	else if (ix == DPCHAPPFMNCBILLISTDO) return("DpchAppFmncBilListDo");
	else if (ix == DPCHAPPFMNCBILRECDO) return("DpchAppFmncBilRecDo");
	else if (ix == DPCHAPPFMNCFAB1NFABPROJECTDATA) return("DpchAppFmncFab1NFabprojectData");
	else if (ix == DPCHAPPFMNCFAB1NFABPROJECTDO) return("DpchAppFmncFab1NFabprojectDo");
	else if (ix == DPCHAPPFMNCFAB1NFABUSERDATA) return("DpchAppFmncFab1NFabuserData");
	else if (ix == DPCHAPPFMNCFAB1NFABUSERDO) return("DpchAppFmncFab1NFabuserDo");
	else if (ix == DPCHAPPFMNCFABDETAILDO) return("DpchAppFmncFabDetailDo");
	else if (ix == DPCHAPPFMNCFABDO) return("DpchAppFmncFabDo");
	else if (ix == DPCHAPPFMNCFABFAB1NTOOLDATA) return("DpchAppFmncFabFab1NToolData");
	else if (ix == DPCHAPPFMNCFABFAB1NTOOLDO) return("DpchAppFmncFabFab1NToolDo");
	else if (ix == DPCHAPPFMNCFABLISTDATA) return("DpchAppFmncFabListData");
	else if (ix == DPCHAPPFMNCFABLISTDO) return("DpchAppFmncFabListDo");
	else if (ix == DPCHAPPFMNCFABMNRUNDATA) return("DpchAppFmncFabMNRunData");
	else if (ix == DPCHAPPFMNCFABMNRUNDO) return("DpchAppFmncFabMNRunDo");
	else if (ix == DPCHAPPFMNCFABRECDO) return("DpchAppFmncFabRecDo");
	else if (ix == DPCHAPPFMNCFILDETAILDATA) return("DpchAppFmncFilDetailData");
	else if (ix == DPCHAPPFMNCFILDETAILDO) return("DpchAppFmncFilDetailDo");
	else if (ix == DPCHAPPFMNCFILDO) return("DpchAppFmncFilDo");
	else if (ix == DPCHAPPFMNCFILLISTDATA) return("DpchAppFmncFilListData");
	else if (ix == DPCHAPPFMNCFILLISTDO) return("DpchAppFmncFilListDo");
	else if (ix == DPCHAPPFMNCFILMNSAMPLEDATA) return("DpchAppFmncFilMNSampleData");
	else if (ix == DPCHAPPFMNCFILMNSAMPLEDO) return("DpchAppFmncFilMNSampleDo");
	else if (ix == DPCHAPPFMNCFILMNSTEPDATA) return("DpchAppFmncFilMNStepData");
	else if (ix == DPCHAPPFMNCFILMNSTEPDO) return("DpchAppFmncFilMNStepDo");
	else if (ix == DPCHAPPFMNCFILRECDO) return("DpchAppFmncFilRecDo");
	else if (ix == DPCHAPPFMNCFPJ1NBILLDATA) return("DpchAppFmncFpj1NBillData");
	else if (ix == DPCHAPPFMNCFPJ1NBILLDO) return("DpchAppFmncFpj1NBillDo");
	else if (ix == DPCHAPPFMNCFPJDETAILDATA) return("DpchAppFmncFpjDetailData");
	else if (ix == DPCHAPPFMNCFPJDETAILDO) return("DpchAppFmncFpjDetailDo");
	else if (ix == DPCHAPPFMNCFPJDO) return("DpchAppFmncFpjDo");
	else if (ix == DPCHAPPFMNCFPJLISTDATA) return("DpchAppFmncFpjListData");
	else if (ix == DPCHAPPFMNCFPJLISTDO) return("DpchAppFmncFpjListDo");
	else if (ix == DPCHAPPFMNCFPJMNFABUSERDATA) return("DpchAppFmncFpjMNFabuserData");
	else if (ix == DPCHAPPFMNCFPJMNFABUSERDO) return("DpchAppFmncFpjMNFabuserDo");
	else if (ix == DPCHAPPFMNCFPJRECDO) return("DpchAppFmncFpjRecDo");
	else if (ix == DPCHAPPFMNCFUSDETAILDATA) return("DpchAppFmncFusDetailData");
	else if (ix == DPCHAPPFMNCFUSDETAILDO) return("DpchAppFmncFusDetailDo");
	else if (ix == DPCHAPPFMNCFUSDO) return("DpchAppFmncFusDo");
	else if (ix == DPCHAPPFMNCFUSLISTDATA) return("DpchAppFmncFusListData");
	else if (ix == DPCHAPPFMNCFUSLISTDO) return("DpchAppFmncFusListDo");
	else if (ix == DPCHAPPFMNCFUSMNFABPROJECTDATA) return("DpchAppFmncFusMNFabprojectData");
	else if (ix == DPCHAPPFMNCFUSMNFABPROJECTDO) return("DpchAppFmncFusMNFabprojectDo");
	else if (ix == DPCHAPPFMNCFUSMNTOOLDATA) return("DpchAppFmncFusMNToolData");
	else if (ix == DPCHAPPFMNCFUSMNTOOLDO) return("DpchAppFmncFusMNToolDo");
	else if (ix == DPCHAPPFMNCFUSRECDO) return("DpchAppFmncFusRecDo");
	else if (ix == DPCHAPPFMNCINIT) return("DpchAppFmncInit");
	else if (ix == DPCHAPPFMNCNAVADMINDATA) return("DpchAppFmncNavAdminData");
	else if (ix == DPCHAPPFMNCNAVADMINDO) return("DpchAppFmncNavAdminDo");
	else if (ix == DPCHAPPFMNCNAVDO) return("DpchAppFmncNavDo");
	else if (ix == DPCHAPPFMNCNAVFABMGMTDATA) return("DpchAppFmncNavFabmgmtData");
	else if (ix == DPCHAPPFMNCNAVFABMGMTDO) return("DpchAppFmncNavFabmgmtDo");
	else if (ix == DPCHAPPFMNCNAVLABBOOKDATA) return("DpchAppFmncNavLabbookData");
	else if (ix == DPCHAPPFMNCNAVLABBOOKDO) return("DpchAppFmncNavLabbookDo");
	else if (ix == DPCHAPPFMNCNAVPREDO) return("DpchAppFmncNavPreDo");
	else if (ix == DPCHAPPFMNCNAVSUPPLYDATA) return("DpchAppFmncNavSupplyData");
	else if (ix == DPCHAPPFMNCNAVSUPPLYDO) return("DpchAppFmncNavSupplyDo");
	else if (ix == DPCHAPPFMNCORG1NARTICLEDATA) return("DpchAppFmncOrg1NArticleData");
	else if (ix == DPCHAPPFMNCORG1NARTICLEDO) return("DpchAppFmncOrg1NArticleDo");
	else if (ix == DPCHAPPFMNCORG1NSTOCKITEMDATA) return("DpchAppFmncOrg1NStockitemData");
	else if (ix == DPCHAPPFMNCORG1NSTOCKITEMDO) return("DpchAppFmncOrg1NStockitemDo");
	else if (ix == DPCHAPPFMNCORGADETAILDATA) return("DpchAppFmncOrgADetailData");
	else if (ix == DPCHAPPFMNCORGADETAILDO) return("DpchAppFmncOrgADetailDo");
	else if (ix == DPCHAPPFMNCORGBIO1NFABPROJECTDATA) return("DpchAppFmncOrgBio1NFabprojectData");
	else if (ix == DPCHAPPFMNCORGBIO1NFABPROJECTDO) return("DpchAppFmncOrgBio1NFabprojectDo");
	else if (ix == DPCHAPPFMNCORGDETAILDATA) return("DpchAppFmncOrgDetailData");
	else if (ix == DPCHAPPFMNCORGDETAILDO) return("DpchAppFmncOrgDetailDo");
	else if (ix == DPCHAPPFMNCORGDO) return("DpchAppFmncOrgDo");
	else if (ix == DPCHAPPFMNCORGHK1NADDRESSDATA) return("DpchAppFmncOrgHk1NAddressData");
	else if (ix == DPCHAPPFMNCORGHK1NADDRESSDO) return("DpchAppFmncOrgHk1NAddressDo");
	else if (ix == DPCHAPPFMNCORGKSTOCKLCNDATA) return("DpchAppFmncOrgKStocklcnData");
	else if (ix == DPCHAPPFMNCORGKSTOCKLCNDO) return("DpchAppFmncOrgKStocklcnDo");
	else if (ix == DPCHAPPFMNCORGLISTDATA) return("DpchAppFmncOrgListData");
	else if (ix == DPCHAPPFMNCORGLISTDO) return("DpchAppFmncOrgListDo");
	else if (ix == DPCHAPPFMNCORGMNARTICLEDATA) return("DpchAppFmncOrgMNArticleData");
	else if (ix == DPCHAPPFMNCORGMNARTICLEDO) return("DpchAppFmncOrgMNArticleDo");
	else if (ix == DPCHAPPFMNCORGMNF1NTOOLDATA) return("DpchAppFmncOrgMnf1NToolData");
	else if (ix == DPCHAPPFMNCORGMNF1NTOOLDO) return("DpchAppFmncOrgMnf1NToolDo");
	else if (ix == DPCHAPPFMNCORGMNPERSONDATA) return("DpchAppFmncOrgMNPersonData");
	else if (ix == DPCHAPPFMNCORGMNPERSONDO) return("DpchAppFmncOrgMNPersonDo");
	else if (ix == DPCHAPPFMNCORGPCO1NPURCHORDERDATA) return("DpchAppFmncOrgPco1NPurchorderData");
	else if (ix == DPCHAPPFMNCORGPCO1NPURCHORDERDO) return("DpchAppFmncOrgPco1NPurchorderDo");
	else if (ix == DPCHAPPFMNCORGRECDO) return("DpchAppFmncOrgRecDo");
	else if (ix == DPCHAPPFMNCORGSPL1NPURCHORDERDATA) return("DpchAppFmncOrgSpl1NPurchorderData");
	else if (ix == DPCHAPPFMNCORGSPL1NPURCHORDERDO) return("DpchAppFmncOrgSpl1NPurchorderDo");
	else if (ix == DPCHAPPFMNCORGSUP1NORGDATA) return("DpchAppFmncOrgSup1NOrgData");
	else if (ix == DPCHAPPFMNCORGSUP1NORGDO) return("DpchAppFmncOrgSup1NOrgDo");
	else if (ix == DPCHAPPFMNCORGSVCMNTOOLDATA) return("DpchAppFmncOrgSvcMNToolData");
	else if (ix == DPCHAPPFMNCORGSVCMNTOOLDO) return("DpchAppFmncOrgSvcMNToolDo");
	else if (ix == DPCHAPPFMNCPCOAPOSDATA) return("DpchAppFmncPcoAPosData");
	else if (ix == DPCHAPPFMNCPCOAPOSDO) return("DpchAppFmncPcoAPosDo");
	else if (ix == DPCHAPPFMNCPCODETAILDATA) return("DpchAppFmncPcoDetailData");
	else if (ix == DPCHAPPFMNCPCODETAILDO) return("DpchAppFmncPcoDetailDo");
	else if (ix == DPCHAPPFMNCPCODO) return("DpchAppFmncPcoDo");
	else if (ix == DPCHAPPFMNCPCOLISTDATA) return("DpchAppFmncPcoListData");
	else if (ix == DPCHAPPFMNCPCOLISTDO) return("DpchAppFmncPcoListDo");
	else if (ix == DPCHAPPFMNCPCORECDO) return("DpchAppFmncPcoRecDo");
	else if (ix == DPCHAPPFMNCPRJ1NRUNDATA) return("DpchAppFmncPrj1NRunData");
	else if (ix == DPCHAPPFMNCPRJ1NRUNDO) return("DpchAppFmncPrj1NRunDo");
	else if (ix == DPCHAPPFMNCPRJDETAILDATA) return("DpchAppFmncPrjDetailData");
	else if (ix == DPCHAPPFMNCPRJDETAILDO) return("DpchAppFmncPrjDetailDo");
	else if (ix == DPCHAPPFMNCPRJDO) return("DpchAppFmncPrjDo");
	else if (ix == DPCHAPPFMNCPRJLISTDATA) return("DpchAppFmncPrjListData");
	else if (ix == DPCHAPPFMNCPRJLISTDO) return("DpchAppFmncPrjListDo");
	else if (ix == DPCHAPPFMNCPRJRECDO) return("DpchAppFmncPrjRecDo");
	else if (ix == DPCHAPPFMNCPRSADETAILDATA) return("DpchAppFmncPrsADetailData");
	else if (ix == DPCHAPPFMNCPRSADETAILDO) return("DpchAppFmncPrsADetailDo");
	else if (ix == DPCHAPPFMNCPRSDETAILDATA) return("DpchAppFmncPrsDetailData");
	else if (ix == DPCHAPPFMNCPRSDETAILDO) return("DpchAppFmncPrsDetailDo");
	else if (ix == DPCHAPPFMNCPRSDO) return("DpchAppFmncPrsDo");
	else if (ix == DPCHAPPFMNCPRSHK1NADDRESSDATA) return("DpchAppFmncPrsHk1NAddressData");
	else if (ix == DPCHAPPFMNCPRSHK1NADDRESSDO) return("DpchAppFmncPrsHk1NAddressDo");
	else if (ix == DPCHAPPFMNCPRSLISTDATA) return("DpchAppFmncPrsListData");
	else if (ix == DPCHAPPFMNCPRSLISTDO) return("DpchAppFmncPrsListDo");
	else if (ix == DPCHAPPFMNCPRSMNORGDATA) return("DpchAppFmncPrsMNOrgData");
	else if (ix == DPCHAPPFMNCPRSMNORGDO) return("DpchAppFmncPrsMNOrgDo");
	else if (ix == DPCHAPPFMNCPRSMNRUNDATA) return("DpchAppFmncPrsMNRunData");
	else if (ix == DPCHAPPFMNCPRSMNRUNDO) return("DpchAppFmncPrsMNRunDo");
	else if (ix == DPCHAPPFMNCPRSRECDO) return("DpchAppFmncPrsRecDo");
	else if (ix == DPCHAPPFMNCRESUME) return("DpchAppFmncResume");
	else if (ix == DPCHAPPFMNCRUNDETAILDATA) return("DpchAppFmncRunDetailData");
	else if (ix == DPCHAPPFMNCRUNDETAILDO) return("DpchAppFmncRunDetailDo");
	else if (ix == DPCHAPPFMNCRUNDO) return("DpchAppFmncRunDo");
	else if (ix == DPCHAPPFMNCRUNLISTDATA) return("DpchAppFmncRunListData");
	else if (ix == DPCHAPPFMNCRUNLISTDO) return("DpchAppFmncRunListDo");
	else if (ix == DPCHAPPFMNCRUNMNFABDATA) return("DpchAppFmncRunMNFabData");
	else if (ix == DPCHAPPFMNCRUNMNFABDO) return("DpchAppFmncRunMNFabDo");
	else if (ix == DPCHAPPFMNCRUNMNPERSONDATA) return("DpchAppFmncRunMNPersonData");
	else if (ix == DPCHAPPFMNCRUNMNPERSONDO) return("DpchAppFmncRunMNPersonDo");
	else if (ix == DPCHAPPFMNCRUNMNSAMPLEDATA) return("DpchAppFmncRunMNSampleData");
	else if (ix == DPCHAPPFMNCRUNMNSAMPLEDO) return("DpchAppFmncRunMNSampleDo");
	else if (ix == DPCHAPPFMNCRUNRECDO) return("DpchAppFmncRunRecDo");
	else if (ix == DPCHAPPFMNCRUNREF1NFILEDATA) return("DpchAppFmncRunRef1NFileData");
	else if (ix == DPCHAPPFMNCRUNREF1NFILEDO) return("DpchAppFmncRunRef1NFileDo");
	else if (ix == DPCHAPPFMNCRUNRUN1NACTIVITYDATA) return("DpchAppFmncRunRun1NActivityData");
	else if (ix == DPCHAPPFMNCRUNRUN1NACTIVITYDO) return("DpchAppFmncRunRun1NActivityDo");
	else if (ix == DPCHAPPFMNCSEPAPARDATA) return("DpchAppFmncSepAParData");
	else if (ix == DPCHAPPFMNCSEPAPARDO) return("DpchAppFmncSepAParDo");
	else if (ix == DPCHAPPFMNCSEPDETAILDATA) return("DpchAppFmncSepDetailData");
	else if (ix == DPCHAPPFMNCSEPDETAILDO) return("DpchAppFmncSepDetailDo");
	else if (ix == DPCHAPPFMNCSEPDO) return("DpchAppFmncSepDo");
	else if (ix == DPCHAPPFMNCSEPLISTDATA) return("DpchAppFmncSepListData");
	else if (ix == DPCHAPPFMNCSEPLISTDO) return("DpchAppFmncSepListDo");
	else if (ix == DPCHAPPFMNCSEPMNFILEDATA) return("DpchAppFmncSepMNFileData");
	else if (ix == DPCHAPPFMNCSEPMNFILEDO) return("DpchAppFmncSepMNFileDo");
	else if (ix == DPCHAPPFMNCSEPMNSAMPLEDATA) return("DpchAppFmncSepMNSampleData");
	else if (ix == DPCHAPPFMNCSEPMNSAMPLEDO) return("DpchAppFmncSepMNSampleDo");
	else if (ix == DPCHAPPFMNCSEPRECDO) return("DpchAppFmncSepRecDo");
	else if (ix == DPCHAPPFMNCSEPREF1NFILEDATA) return("DpchAppFmncSepRef1NFileData");
	else if (ix == DPCHAPPFMNCSEPREF1NFILEDO) return("DpchAppFmncSepRef1NFileDo");
	else if (ix == DPCHAPPFMNCSKIDETAILDATA) return("DpchAppFmncSkiDetailData");
	else if (ix == DPCHAPPFMNCSKIDETAILDO) return("DpchAppFmncSkiDetailDo");
	else if (ix == DPCHAPPFMNCSKIDO) return("DpchAppFmncSkiDo");
	else if (ix == DPCHAPPFMNCSKILISTDATA) return("DpchAppFmncSkiListData");
	else if (ix == DPCHAPPFMNCSKILISTDO) return("DpchAppFmncSkiListDo");
	else if (ix == DPCHAPPFMNCSKIRECDO) return("DpchAppFmncSkiRecDo");
	else if (ix == DPCHAPPFMNCSMPAPARDATA) return("DpchAppFmncSmpAParData");
	else if (ix == DPCHAPPFMNCSMPAPARDO) return("DpchAppFmncSmpAParDo");
	else if (ix == DPCHAPPFMNCSMPDETAILDATA) return("DpchAppFmncSmpDetailData");
	else if (ix == DPCHAPPFMNCSMPDETAILDO) return("DpchAppFmncSmpDetailDo");
	else if (ix == DPCHAPPFMNCSMPDO) return("DpchAppFmncSmpDo");
	else if (ix == DPCHAPPFMNCSMPLISTDATA) return("DpchAppFmncSmpListData");
	else if (ix == DPCHAPPFMNCSMPLISTDO) return("DpchAppFmncSmpListDo");
	else if (ix == DPCHAPPFMNCSMPMNFILEDATA) return("DpchAppFmncSmpMNFileData");
	else if (ix == DPCHAPPFMNCSMPMNFILEDO) return("DpchAppFmncSmpMNFileDo");
	else if (ix == DPCHAPPFMNCSMPMNRUNDATA) return("DpchAppFmncSmpMNRunData");
	else if (ix == DPCHAPPFMNCSMPMNRUNDO) return("DpchAppFmncSmpMNRunDo");
	else if (ix == DPCHAPPFMNCSMPMNSTEPDATA) return("DpchAppFmncSmpMNStepData");
	else if (ix == DPCHAPPFMNCSMPMNSTEPDO) return("DpchAppFmncSmpMNStepDo");
	else if (ix == DPCHAPPFMNCSMPRECDO) return("DpchAppFmncSmpRecDo");
	else if (ix == DPCHAPPFMNCSMPREF1NFILEDATA) return("DpchAppFmncSmpRef1NFileData");
	else if (ix == DPCHAPPFMNCSMPREF1NFILEDO) return("DpchAppFmncSmpRef1NFileDo");
	else if (ix == DPCHAPPFMNCSMPSUP1NSAMPLEDATA) return("DpchAppFmncSmpSup1NSampleData");
	else if (ix == DPCHAPPFMNCSMPSUP1NSAMPLEDO) return("DpchAppFmncSmpSup1NSampleDo");
	else if (ix == DPCHAPPFMNCSTPAPARDATA) return("DpchAppFmncStpAParData");
	else if (ix == DPCHAPPFMNCSTPAPARDO) return("DpchAppFmncStpAParDo");
	else if (ix == DPCHAPPFMNCSTPDETAILDATA) return("DpchAppFmncStpDetailData");
	else if (ix == DPCHAPPFMNCSTPDETAILDO) return("DpchAppFmncStpDetailDo");
	else if (ix == DPCHAPPFMNCSTPDO) return("DpchAppFmncStpDo");
	else if (ix == DPCHAPPFMNCSTPKSTEPPARDATA) return("DpchAppFmncStpKStepparData");
	else if (ix == DPCHAPPFMNCSTPKSTEPPARDO) return("DpchAppFmncStpKStepparDo");
	else if (ix == DPCHAPPFMNCSTPLISTDATA) return("DpchAppFmncStpListData");
	else if (ix == DPCHAPPFMNCSTPLISTDO) return("DpchAppFmncStpListDo");
	else if (ix == DPCHAPPFMNCSTPMNFILEDATA) return("DpchAppFmncStpMNFileData");
	else if (ix == DPCHAPPFMNCSTPMNFILEDO) return("DpchAppFmncStpMNFileDo");
	else if (ix == DPCHAPPFMNCSTPRECDO) return("DpchAppFmncStpRecDo");
	else if (ix == DPCHAPPFMNCSTPREF1NFILEDATA) return("DpchAppFmncStpRef1NFileData");
	else if (ix == DPCHAPPFMNCSTPREF1NFILEDO) return("DpchAppFmncStpRef1NFileDo");
	else if (ix == DPCHAPPFMNCSTPTPL1NSTEPDATA) return("DpchAppFmncStpTpl1NStepData");
	else if (ix == DPCHAPPFMNCSTPTPL1NSTEPDO) return("DpchAppFmncStpTpl1NStepDo");
	else if (ix == DPCHAPPFMNCTOL1NARTICLEDATA) return("DpchAppFmncTol1NArticleData");
	else if (ix == DPCHAPPFMNCTOL1NARTICLEDO) return("DpchAppFmncTol1NArticleDo");
	else if (ix == DPCHAPPFMNCTOLAAVLDATA) return("DpchAppFmncTolAAvlData");
	else if (ix == DPCHAPPFMNCTOLAAVLDO) return("DpchAppFmncTolAAvlDo");
	else if (ix == DPCHAPPFMNCTOLACHARDATA) return("DpchAppFmncTolACharData");
	else if (ix == DPCHAPPFMNCTOLACHARDO) return("DpchAppFmncTolACharDo");
	else if (ix == DPCHAPPFMNCTOLARESDATA) return("DpchAppFmncTolAResData");
	else if (ix == DPCHAPPFMNCTOLARESDO) return("DpchAppFmncTolAResDo");
	else if (ix == DPCHAPPFMNCTOLAUTILDATA) return("DpchAppFmncTolAUtilData");
	else if (ix == DPCHAPPFMNCTOLAUTILDO) return("DpchAppFmncTolAUtilDo");
	else if (ix == DPCHAPPFMNCTOLDETAILDATA) return("DpchAppFmncTolDetailData");
	else if (ix == DPCHAPPFMNCTOLDETAILDO) return("DpchAppFmncTolDetailDo");
	else if (ix == DPCHAPPFMNCTOLDO) return("DpchAppFmncTolDo");
	else if (ix == DPCHAPPFMNCTOLKSTEPPARDATA) return("DpchAppFmncTolKStepparData");
	else if (ix == DPCHAPPFMNCTOLKSTEPPARDO) return("DpchAppFmncTolKStepparDo");
	else if (ix == DPCHAPPFMNCTOLKTOOLCHARDATA) return("DpchAppFmncTolKToolcharData");
	else if (ix == DPCHAPPFMNCTOLKTOOLCHARDO) return("DpchAppFmncTolKToolcharDo");
	else if (ix == DPCHAPPFMNCTOLLISTDATA) return("DpchAppFmncTolListData");
	else if (ix == DPCHAPPFMNCTOLLISTDO) return("DpchAppFmncTolListDo");
	else if (ix == DPCHAPPFMNCTOLMNFABUSERDATA) return("DpchAppFmncTolMNFabuserData");
	else if (ix == DPCHAPPFMNCTOLMNFABUSERDO) return("DpchAppFmncTolMNFabuserDo");
	else if (ix == DPCHAPPFMNCTOLMNTOOLTYPEDATA) return("DpchAppFmncTolMNTooltypeData");
	else if (ix == DPCHAPPFMNCTOLMNTOOLTYPEDO) return("DpchAppFmncTolMNTooltypeDo");
	else if (ix == DPCHAPPFMNCTOLRECDO) return("DpchAppFmncTolRecDo");
	else if (ix == DPCHAPPFMNCTOLREF1NFILEDATA) return("DpchAppFmncTolRef1NFileData");
	else if (ix == DPCHAPPFMNCTOLREF1NFILEDO) return("DpchAppFmncTolRef1NFileDo");
	else if (ix == DPCHAPPFMNCTOLRLV1NSTEPDATA) return("DpchAppFmncTolRlv1NStepData");
	else if (ix == DPCHAPPFMNCTOLRLV1NSTEPDO) return("DpchAppFmncTolRlv1NStepDo");
	else if (ix == DPCHAPPFMNCTOLSVCMNORGDATA) return("DpchAppFmncTolSvcMNOrgData");
	else if (ix == DPCHAPPFMNCTOLSVCMNORGDO) return("DpchAppFmncTolSvcMNOrgDo");
	else if (ix == DPCHAPPFMNCTTYDETAILDATA) return("DpchAppFmncTtyDetailData");
	else if (ix == DPCHAPPFMNCTTYDETAILDO) return("DpchAppFmncTtyDetailDo");
	else if (ix == DPCHAPPFMNCTTYDO) return("DpchAppFmncTtyDo");
	else if (ix == DPCHAPPFMNCTTYKSTEPPARDATA) return("DpchAppFmncTtyKStepparData");
	else if (ix == DPCHAPPFMNCTTYKSTEPPARDO) return("DpchAppFmncTtyKStepparDo");
	else if (ix == DPCHAPPFMNCTTYKTOOLCHARDATA) return("DpchAppFmncTtyKToolcharData");
	else if (ix == DPCHAPPFMNCTTYKTOOLCHARDO) return("DpchAppFmncTtyKToolcharDo");
	else if (ix == DPCHAPPFMNCTTYLISTDATA) return("DpchAppFmncTtyListData");
	else if (ix == DPCHAPPFMNCTTYLISTDO) return("DpchAppFmncTtyListDo");
	else if (ix == DPCHAPPFMNCTTYMNTOOLDATA) return("DpchAppFmncTtyMNToolData");
	else if (ix == DPCHAPPFMNCTTYMNTOOLDO) return("DpchAppFmncTtyMNToolDo");
	else if (ix == DPCHAPPFMNCTTYRECDO) return("DpchAppFmncTtyRecDo");
	else if (ix == DPCHAPPFMNCTTYRLV1NSTEPDATA) return("DpchAppFmncTtyRlv1NStepData");
	else if (ix == DPCHAPPFMNCTTYRLV1NSTEPDO) return("DpchAppFmncTtyRlv1NStepDo");
	else if (ix == DPCHAPPFMNCTTYSUP1NTOOLTYPEDATA) return("DpchAppFmncTtySup1NTooltypeData");
	else if (ix == DPCHAPPFMNCTTYSUP1NTOOLTYPEDO) return("DpchAppFmncTtySup1NTooltypeDo");
	else if (ix == DPCHAPPFMNCUSGAACCESSDATA) return("DpchAppFmncUsgAAccessData");
	else if (ix == DPCHAPPFMNCUSGAACCESSDO) return("DpchAppFmncUsgAAccessDo");
	else if (ix == DPCHAPPFMNCUSGDETAILDATA) return("DpchAppFmncUsgDetailData");
	else if (ix == DPCHAPPFMNCUSGDETAILDO) return("DpchAppFmncUsgDetailDo");
	else if (ix == DPCHAPPFMNCUSGDO) return("DpchAppFmncUsgDo");
	else if (ix == DPCHAPPFMNCUSGLISTDATA) return("DpchAppFmncUsgListData");
	else if (ix == DPCHAPPFMNCUSGLISTDO) return("DpchAppFmncUsgListDo");
	else if (ix == DPCHAPPFMNCUSGMNUSERDATA) return("DpchAppFmncUsgMNUserData");
	else if (ix == DPCHAPPFMNCUSGMNUSERDO) return("DpchAppFmncUsgMNUserDo");
	else if (ix == DPCHAPPFMNCUSGRECDO) return("DpchAppFmncUsgRecDo");
	else if (ix == DPCHAPPFMNCUSR1NSESSIONDATA) return("DpchAppFmncUsr1NSessionData");
	else if (ix == DPCHAPPFMNCUSR1NSESSIONDO) return("DpchAppFmncUsr1NSessionDo");
	else if (ix == DPCHAPPFMNCUSRAACCESSDATA) return("DpchAppFmncUsrAAccessData");
	else if (ix == DPCHAPPFMNCUSRAACCESSDO) return("DpchAppFmncUsrAAccessDo");
	else if (ix == DPCHAPPFMNCUSRDETAILDATA) return("DpchAppFmncUsrDetailData");
	else if (ix == DPCHAPPFMNCUSRDETAILDO) return("DpchAppFmncUsrDetailDo");
	else if (ix == DPCHAPPFMNCUSRDO) return("DpchAppFmncUsrDo");
	else if (ix == DPCHAPPFMNCUSRLISTDATA) return("DpchAppFmncUsrListData");
	else if (ix == DPCHAPPFMNCUSRLISTDO) return("DpchAppFmncUsrListDo");
	else if (ix == DPCHAPPFMNCUSRMNUSERGROUPDATA) return("DpchAppFmncUsrMNUsergroupData");
	else if (ix == DPCHAPPFMNCUSRMNUSERGROUPDO) return("DpchAppFmncUsrMNUsergroupDo");
	else if (ix == DPCHAPPFMNCUSRRECDO) return("DpchAppFmncUsrRecDo");
	else if (ix == DPCHAPPROOTFMNCLOGIN) return("DpchAppRootFmncLogin");

	return("");
};

