CREATE DATABASE DbsFmnc;
USE DbsFmnc;

GRANT ALL ON DbsFmnc.* TO 'epsi'@'localhost' IDENTIFIED BY 'f9w8feeh';
GRANT ALL ON DbsFmnc.* TO 'epsi'@'%' IDENTIFIED BY 'f9w8feeh';

DROP TABLE IF EXISTS TblFmncAccRMUserUniversal;
DROP TABLE IF EXISTS TblFmncAMBillPos;
DROP TABLE IF EXISTS TblFmncAMOrgDetail;
DROP TABLE IF EXISTS TblFmncAMPersonDetail;
DROP TABLE IF EXISTS TblFmncAMPurchorderPos;
DROP TABLE IF EXISTS TblFmncAMSamplePar;
DROP TABLE IF EXISTS TblFmncAMStepPar;
DROP TABLE IF EXISTS TblFmncAMToolAvl;
DROP TABLE IF EXISTS TblFmncAMToolChar;
DROP TABLE IF EXISTS TblFmncAMToolRes;
DROP TABLE IF EXISTS TblFmncAMToolUtil;
DROP TABLE IF EXISTS TblFmncAMUserAccess;
DROP TABLE IF EXISTS TblFmncAMUsergroupAccess;
DROP TABLE IF EXISTS TblFmncAVControlPar;
DROP TABLE IF EXISTS TblFmncAVKeylistKey;
DROP TABLE IF EXISTS TblFmncAVValuelistVal;
DROP TABLE IF EXISTS TblFmncCFile;
DROP TABLE IF EXISTS TblFmncFabSMPersonMTool;
DROP TABLE IF EXISTS TblFmncHistRMUserUniversal;
DROP TABLE IF EXISTS TblFmncJAVKeylistKey;
DROP TABLE IF EXISTS TblFmncJMBillState;
DROP TABLE IF EXISTS TblFmncJMFabprojectState;
DROP TABLE IF EXISTS TblFmncJMFabuserState;
DROP TABLE IF EXISTS TblFmncJMOrgTitle;
DROP TABLE IF EXISTS TblFmncJMPersonLastname;
DROP TABLE IF EXISTS TblFmncJMProjectState;
DROP TABLE IF EXISTS TblFmncJMPurchorderState;
DROP TABLE IF EXISTS TblFmncJMRunState;
DROP TABLE IF EXISTS TblFmncJMSampleState;
DROP TABLE IF EXISTS TblFmncJMStockitemQuantity;
DROP TABLE IF EXISTS TblFmncJMToolUnitprice;
DROP TABLE IF EXISTS TblFmncJMUserState;
DROP TABLE IF EXISTS TblFmncMActivity;
DROP TABLE IF EXISTS TblFmncMAddress;
DROP TABLE IF EXISTS TblFmncMArticle;
DROP TABLE IF EXISTS TblFmncMBill;
DROP TABLE IF EXISTS TblFmncMFab;
DROP TABLE IF EXISTS TblFmncMFabproject;
DROP TABLE IF EXISTS TblFmncMFabuser;
DROP TABLE IF EXISTS TblFmncMFile;
DROP TABLE IF EXISTS TblFmncMnfSMPersonMTool;
DROP TABLE IF EXISTS TblFmncMOrg;
DROP TABLE IF EXISTS TblFmncMPerson;
DROP TABLE IF EXISTS TblFmncMProject;
DROP TABLE IF EXISTS TblFmncMPurchorder;
DROP TABLE IF EXISTS TblFmncMRun;
DROP TABLE IF EXISTS TblFmncMSample;
DROP TABLE IF EXISTS TblFmncMSession;
DROP TABLE IF EXISTS TblFmncMStep;
DROP TABLE IF EXISTS TblFmncMStockitem;
DROP TABLE IF EXISTS TblFmncMTool;
DROP TABLE IF EXISTS TblFmncMTooltype;
DROP TABLE IF EXISTS TblFmncMUser;
DROP TABLE IF EXISTS TblFmncMUsergroup;
DROP TABLE IF EXISTS TblFmncRMArticleMOrg;
DROP TABLE IF EXISTS TblFmncRMFabMRun;
DROP TABLE IF EXISTS TblFmncRMFabprojectMFabuser;
DROP TABLE IF EXISTS TblFmncRMFabuserMTool;
DROP TABLE IF EXISTS TblFmncRMFileMSample;
DROP TABLE IF EXISTS TblFmncRMFileMStep;
DROP TABLE IF EXISTS TblFmncRMOrgMPerson;
DROP TABLE IF EXISTS TblFmncRMPersonMRun;
DROP TABLE IF EXISTS TblFmncRMRunMSample;
DROP TABLE IF EXISTS TblFmncRMSampleMStep;
DROP TABLE IF EXISTS TblFmncRMToolMTooltype;
DROP TABLE IF EXISTS TblFmncRMUsergroupUniversal;
DROP TABLE IF EXISTS TblFmncRMUserMUsergroup;
DROP TABLE IF EXISTS TblFmncSvcRMOrgMTool;
DROP TABLE IF EXISTS TblFmncSvcTMPersonMTool;
DROP TABLE IF EXISTS TblFmncTMFileMSample;

DROP TABLE IF EXISTS TblFmncQAct1NStep;
DROP TABLE IF EXISTS TblFmncQActList;
DROP TABLE IF EXISTS TblFmncQAdrList;
DROP TABLE IF EXISTS TblFmncQArt1NSample;
DROP TABLE IF EXISTS TblFmncQArt1NStockitem;
DROP TABLE IF EXISTS TblFmncQArtList;
DROP TABLE IF EXISTS TblFmncQArtMNOrg;
DROP TABLE IF EXISTS TblFmncQArtRef1NFile;
DROP TABLE IF EXISTS TblFmncQBilAPos;
DROP TABLE IF EXISTS TblFmncQBilList;
DROP TABLE IF EXISTS TblFmncQFab1NFabproject;
DROP TABLE IF EXISTS TblFmncQFab1NFabuser;
DROP TABLE IF EXISTS TblFmncQFabFab1NTool;
DROP TABLE IF EXISTS TblFmncQFabList;
DROP TABLE IF EXISTS TblFmncQFabMNRun;
DROP TABLE IF EXISTS TblFmncQFilList;
DROP TABLE IF EXISTS TblFmncQFilMNSample;
DROP TABLE IF EXISTS TblFmncQFilMNStep;
DROP TABLE IF EXISTS TblFmncQFpj1NBill;
DROP TABLE IF EXISTS TblFmncQFpjList;
DROP TABLE IF EXISTS TblFmncQFpjMNFabuser;
DROP TABLE IF EXISTS TblFmncQFusList;
DROP TABLE IF EXISTS TblFmncQFusMNFabproject;
DROP TABLE IF EXISTS TblFmncQFusMNTool;
DROP TABLE IF EXISTS TblFmncQOrg1NArticle;
DROP TABLE IF EXISTS TblFmncQOrg1NStockitem;
DROP TABLE IF EXISTS TblFmncQOrgADetail;
DROP TABLE IF EXISTS TblFmncQOrgBio1NFabproject;
DROP TABLE IF EXISTS TblFmncQOrgHk1NAddress;
DROP TABLE IF EXISTS TblFmncQOrgKStocklcn;
DROP TABLE IF EXISTS TblFmncQOrgList;
DROP TABLE IF EXISTS TblFmncQOrgMNArticle;
DROP TABLE IF EXISTS TblFmncQOrgMnf1NTool;
DROP TABLE IF EXISTS TblFmncQOrgMNPerson;
DROP TABLE IF EXISTS TblFmncQOrgPco1NPurchorder;
DROP TABLE IF EXISTS TblFmncQOrgSpl1NPurchorder;
DROP TABLE IF EXISTS TblFmncQOrgSup1NOrg;
DROP TABLE IF EXISTS TblFmncQOrgSvcMNTool;
DROP TABLE IF EXISTS TblFmncQPcoAPos;
DROP TABLE IF EXISTS TblFmncQPcoList;
DROP TABLE IF EXISTS TblFmncQPreselect;
DROP TABLE IF EXISTS TblFmncQPrj1NRun;
DROP TABLE IF EXISTS TblFmncQPrjList;
DROP TABLE IF EXISTS TblFmncQPrsADetail;
DROP TABLE IF EXISTS TblFmncQPrsHk1NAddress;
DROP TABLE IF EXISTS TblFmncQPrsList;
DROP TABLE IF EXISTS TblFmncQPrsMNOrg;
DROP TABLE IF EXISTS TblFmncQPrsMNRun;
DROP TABLE IF EXISTS TblFmncQRunList;
DROP TABLE IF EXISTS TblFmncQRunMNFab;
DROP TABLE IF EXISTS TblFmncQRunMNPerson;
DROP TABLE IF EXISTS TblFmncQRunMNSample;
DROP TABLE IF EXISTS TblFmncQRunRef1NFile;
DROP TABLE IF EXISTS TblFmncQRunRun1NActivity;
DROP TABLE IF EXISTS TblFmncQSelect;
DROP TABLE IF EXISTS TblFmncQSepAPar;
DROP TABLE IF EXISTS TblFmncQSepList;
DROP TABLE IF EXISTS TblFmncQSepMNFile;
DROP TABLE IF EXISTS TblFmncQSepMNSample;
DROP TABLE IF EXISTS TblFmncQSepRef1NFile;
DROP TABLE IF EXISTS TblFmncQSkiList;
DROP TABLE IF EXISTS TblFmncQSmpAPar;
DROP TABLE IF EXISTS TblFmncQSmpList;
DROP TABLE IF EXISTS TblFmncQSmpMNFile;
DROP TABLE IF EXISTS TblFmncQSmpMNRun;
DROP TABLE IF EXISTS TblFmncQSmpMNStep;
DROP TABLE IF EXISTS TblFmncQSmpRef1NFile;
DROP TABLE IF EXISTS TblFmncQSmpSup1NSample;
DROP TABLE IF EXISTS TblFmncQStpAPar;
DROP TABLE IF EXISTS TblFmncQStpKSteppar;
DROP TABLE IF EXISTS TblFmncQStpList;
DROP TABLE IF EXISTS TblFmncQStpMNFile;
DROP TABLE IF EXISTS TblFmncQStpRef1NFile;
DROP TABLE IF EXISTS TblFmncQStpTpl1NStep;
DROP TABLE IF EXISTS TblFmncQTol1NArticle;
DROP TABLE IF EXISTS TblFmncQTolAAvl;
DROP TABLE IF EXISTS TblFmncQTolAChar;
DROP TABLE IF EXISTS TblFmncQTolARes;
DROP TABLE IF EXISTS TblFmncQTolAUtil;
DROP TABLE IF EXISTS TblFmncQTolKSteppar;
DROP TABLE IF EXISTS TblFmncQTolKToolchar;
DROP TABLE IF EXISTS TblFmncQTolList;
DROP TABLE IF EXISTS TblFmncQTolMNFabuser;
DROP TABLE IF EXISTS TblFmncQTolMNTooltype;
DROP TABLE IF EXISTS TblFmncQTolRef1NFile;
DROP TABLE IF EXISTS TblFmncQTolRlv1NStep;
DROP TABLE IF EXISTS TblFmncQTolSvcMNOrg;
DROP TABLE IF EXISTS TblFmncQTtyKSteppar;
DROP TABLE IF EXISTS TblFmncQTtyKToolchar;
DROP TABLE IF EXISTS TblFmncQTtyList;
DROP TABLE IF EXISTS TblFmncQTtyMNTool;
DROP TABLE IF EXISTS TblFmncQTtyRlv1NStep;
DROP TABLE IF EXISTS TblFmncQTtySup1NTooltype;
DROP TABLE IF EXISTS TblFmncQUsgAAccess;
DROP TABLE IF EXISTS TblFmncQUsgList;
DROP TABLE IF EXISTS TblFmncQUsgMNUser;
DROP TABLE IF EXISTS TblFmncQUsr1NSession;
DROP TABLE IF EXISTS TblFmncQUsrAAccess;
DROP TABLE IF EXISTS TblFmncQUsrList;
DROP TABLE IF EXISTS TblFmncQUsrMNUsergroup;

CREATE TABLE TblFmncAccRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	unvIxFmncVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixFmncVAccess INT UNSIGNED,
	INDEX (refFmncMUser),
	INDEX (unvIxFmncVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMBillPos(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	bilRefFmncMBill BIGINT UNSIGNED,
	bilNum INT UNSIGNED,
	x1RefFmncMFabuser BIGINT UNSIGNED,
	x2RefFmncMTool BIGINT UNSIGNED,
	Quantity DOUBLE,
	Article VARCHAR(255),
	Unitprice DOUBLE,
	Price DOUBLE,
	INDEX (bilRefFmncMBill),
	INDEX (bilNum),
	INDEX (x1RefFmncMFabuser),
	INDEX (x2RefFmncMTool)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMOrgDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMOrg BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refFmncMOrg)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMPersonDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (refFmncMPerson)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMPurchorderPos(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	pcoRefFmncMPurchorder BIGINT UNSIGNED,
	pcoNum INT UNSIGNED,
	Quantity DOUBLE,
	Itemno VARCHAR(30),
	refFmncMArticle BIGINT UNSIGNED,
	Unitprice DOUBLE,
	Price DOUBLE,
	INDEX (pcoRefFmncMPurchorder),
	INDEX (pcoNum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMSamplePar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMSample BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	osrefKVal VARCHAR(50),
	INDEX (refFmncMSample)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMStepPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMStep BIGINT UNSIGNED,
	x1OsrefFmncKSteppar VARCHAR(50),
	x2IxVTbl INT UNSIGNED,
	x2Uref BIGINT UNSIGNED,
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (refFmncMStep),
	INDEX (x2IxVTbl),
	INDEX (x2Uref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMToolAvl(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x2IxVWkday INT UNSIGNED,
	x3Startt INT UNSIGNED,
	x3Stopt INT UNSIGNED,
	srefKAvltype VARCHAR(50),
	INDEX (refFmncMTool),
	INDEX (x1Startd),
	INDEX (x2IxVWkday),
	INDEX (x3Startt),
	INDEX (x3Stopt)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMToolChar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	x1OsrefFmncKToolchar VARCHAR(50),
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (refFmncMTool)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMToolRes(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	x1RefFmncMFabuser BIGINT UNSIGNED,
	startd INT UNSIGNED,
	startt INT UNSIGNED,
	stopt INT UNSIGNED,
	srefKRestype VARCHAR(50),
	Comment TEXT,
	INDEX (refFmncMTool),
	INDEX (x1RefFmncMFabuser),
	INDEX (startd),
	INDEX (startt)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMToolUtil(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	x1RefFmncMFabproject BIGINT UNSIGNED,
	x2RefFmncMFabuser BIGINT UNSIGNED,
	startd INT UNSIGNED,
	startt INT UNSIGNED,
	stopt INT UNSIGNED,
	Unitprice DOUBLE,
	Comment TEXT,
	INDEX (refFmncMTool),
	INDEX (x1RefFmncMFabproject),
	INDEX (x2RefFmncMFabuser),
	INDEX (startd),
	INDEX (startt)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMUserAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	x1IxFmncVCard INT UNSIGNED,
	ixFmncWUiaccess INT UNSIGNED,
	INDEX (refFmncMUser),
	INDEX (x1IxFmncVCard)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAMUsergroupAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUsergroup BIGINT UNSIGNED,
	x1IxFmncVCard INT UNSIGNED,
	ixFmncWUiaccess INT UNSIGNED,
	INDEX (refFmncMUsergroup),
	INDEX (x1IxFmncVCard)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAVControlPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixFmncVControl INT UNSIGNED,
	x1RefFmncMUser BIGINT UNSIGNED,
	x2IxFmncVLocale INT UNSIGNED,
	Par VARCHAR(255),
	Val VARCHAR(255),
	INDEX (ixFmncVControl),
	INDEX (x1RefFmncMUser),
	INDEX (x2IxFmncVLocale),
	INDEX (Par)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	klsIxFmncVKeylist INT UNSIGNED,
	klsNum INT UNSIGNED,
	x1IxFmncVMaintable INT UNSIGNED,
	x1Uref BIGINT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (klsIxFmncVKeylist),
	INDEX (klsNum),
	INDEX (x1IxFmncVMaintable),
	INDEX (x1Uref),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncAVValuelistVal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vlsIxFmncVValuelist INT UNSIGNED,
	vlsNum INT UNSIGNED,
	x1IxFmncVLocale INT UNSIGNED,
	Val VARCHAR(255),
	INDEX (vlsIxFmncVValuelist),
	INDEX (vlsNum),
	INDEX (x1IxFmncVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblFmncCFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = MYISAM;

CREATE TABLE TblFmncFabSMPersonMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	refM BIGINT UNSIGNED,
	numM INT UNSIGNED,
	INDEX (refFmncMPerson),
	INDEX (refM),
	INDEX (numM)
) ENGINE = MYISAM;

CREATE TABLE TblFmncHistRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	unvIxFmncVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixFmncVCard INT UNSIGNED,
	ixFmncVPreset INT UNSIGNED,
	preIxFmncVMaintable INT UNSIGNED,
	preUref BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (refFmncMUser),
	INDEX (unvIxFmncVMaintable),
	INDEX (unvUref),
	INDEX (ixFmncVCard),
	INDEX (ixFmncVPreset),
	INDEX (preIxFmncVMaintable),
	INDEX (preUref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncAVKeylistKey BIGINT UNSIGNED,
	x1IxFmncVLocale INT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (refFmncAVKeylistKey),
	INDEX (x1IxFmncVLocale)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMBillState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMBill BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMBill),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMFabprojectState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFabproject BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMFabproject),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMFabuserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFabuser BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMFabuser),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMOrgTitle(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMOrg BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Title VARCHAR(50),
	INDEX (refFmncMOrg),
	INDEX (x1Startd),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMPersonLastname(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Lastname VARCHAR(50),
	INDEX (refFmncMPerson),
	INDEX (x1Startd),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMProjectState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMProject BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMProject),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMPurchorderState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPurchorder BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMPurchorder),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMRunState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMRun BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMRun),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMSampleState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMSample BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMSample),
	INDEX (x1Start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMStockitemQuantity(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMStockitem BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Quantity VARCHAR(10),
	INDEX (refFmncMStockitem),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMToolUnitprice(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Unitprice DOUBLE,
	INDEX (refFmncMTool),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncJMUserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refFmncMUser),
	INDEX (x1Startd)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMActivity(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	runRefFmncMRun BIGINT UNSIGNED,
	runNum INT UNSIGNED,
	Title VARCHAR(100),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (runRefFmncMRun),
	INDEX (runNum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMAddress(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	srefKAdrtype VARCHAR(50),
	Address1 VARCHAR(100),
	Address2 VARCHAR(100),
	Zipcode VARCHAR(10),
	City VARCHAR(50),
	State VARCHAR(50),
	srefKCountry VARCHAR(50),
	INDEX (grp),
	INDEX (own),
	INDEX (x1Startd),
	INDEX (hkIxVTbl),
	INDEX (hkUref),
	INDEX (srefKAdrtype),
	INDEX (City),
	INDEX (srefKCountry)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMArticle(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMTool BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(100),
	srefKType VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMOrg),
	INDEX (refFmncMTool),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMBill(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMFabproject BIGINT UNSIGNED,
	refFmncMFile BIGINT UNSIGNED,
	sref VARCHAR(50),
	Date INT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Prdstart INT UNSIGNED,
	Prdstop INT UNSIGNED,
	Amount DOUBLE,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMFabproject),
	INDEX (refFmncMFile),
	INDEX (sref),
	INDEX (Date),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMFab(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMOrg)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMFabproject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMFab BIGINT UNSIGNED,
	bioRefFmncMOrg BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(100),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	bipRefFmncMPerson BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMFab),
	INDEX (bioRefFmncMOrg),
	INDEX (sref),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMFabuser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMFab BIGINT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	refRFabproject BIGINT UNSIGNED,
	refFmncMFabproject BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMFab),
	INDEX (refFmncMPerson),
	INDEX (refFmncMFabproject),
	INDEX (sref),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncCFile BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	Archived INT UNSIGNED,
	Filename VARCHAR(50),
	Archivename VARCHAR(30),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncCFile),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (Filename)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMnfSMPersonMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	refM BIGINT UNSIGNED,
	INDEX (refFmncMPerson),
	INDEX (refM)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMOrg(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixWDerivate INT UNSIGNED,
	refFmncMAddress BIGINT UNSIGNED,
	supRefFmncMOrg BIGINT UNSIGNED,
	supLvl SMALLINT UNSIGNED,
	sref VARCHAR(50),
	refJTitle BIGINT UNSIGNED,
	Title VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	Tel VARCHAR(255),
	emlRefADetail BIGINT UNSIGNED,
	Eml VARCHAR(255),
	INDEX (ixWDerivate),
	INDEX (refFmncMAddress),
	INDEX (supRefFmncMOrg),
	INDEX (supLvl),
	INDEX (sref),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixWDerivate INT UNSIGNED,
	refROrg BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMAddress BIGINT UNSIGNED,
	ixVSex INT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	refJLastname BIGINT UNSIGNED,
	Lastname VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	Tel VARCHAR(255),
	emlRefADetail BIGINT UNSIGNED,
	Eml VARCHAR(255),
	Salutation VARCHAR(100),
	INDEX (grp),
	INDEX (own),
	INDEX (ixWDerivate),
	INDEX (refFmncMOrg),
	INDEX (refFmncMAddress),
	INDEX (Lastname)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMProject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Title VARCHAR(100),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (Title),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMPurchorder(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	pcoRefFmncMOrg BIGINT UNSIGNED,
	splRefFmncMOrg BIGINT UNSIGNED,
	refFmncMFile BIGINT UNSIGNED,
	sref VARCHAR(50),
	Date INT UNSIGNED,
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Amount DOUBLE,
	pcpRefFmncMPerson BIGINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (pcoRefFmncMOrg),
	INDEX (splRefFmncMOrg),
	INDEX (refFmncMFile),
	INDEX (sref),
	INDEX (Date),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMRun(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMProject BIGINT UNSIGNED,
	Title VARCHAR(100),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMProject),
	INDEX (Title),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMSample(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	supRefFmncMSample BIGINT UNSIGNED,
	supLvl SMALLINT UNSIGNED,
	refFmncMArticle BIGINT UNSIGNED,
	sref VARCHAR(50),
	Material VARCHAR(100),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (supRefFmncMSample),
	INDEX (supLvl),
	INDEX (refFmncMArticle),
	INDEX (sref),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMSession(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (refFmncMUser),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMStep(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMActivity BIGINT UNSIGNED,
	rlvIxVTbl INT UNSIGNED,
	rlvUref BIGINT UNSIGNED,
	tplRefFmncMStep BIGINT UNSIGNED,
	ixWFilecfg INT UNSIGNED,
	Title VARCHAR(100),
	start INT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMActivity),
	INDEX (rlvIxVTbl),
	INDEX (rlvUref),
	INDEX (tplRefFmncMStep),
	INDEX (ixWFilecfg),
	INDEX (start)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMStockitem(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMArticle BIGINT UNSIGNED,
	refJQuantity BIGINT UNSIGNED,
	Quantity VARCHAR(10),
	osrefFmncKStocklcn VARCHAR(50),
	Expdate INT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMOrg),
	INDEX (refFmncMArticle)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	fabRefFmncMFab BIGINT UNSIGNED,
	mnfRefFmncMOrg BIGINT UNSIGNED,
	Title VARCHAR(50),
	refJUnitprice BIGINT UNSIGNED,
	Unitprice DOUBLE,
	Training VARCHAR(100),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (fabRefFmncMFab),
	INDEX (mnfRefFmncMOrg),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMTooltype(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	supRefFmncMTooltype BIGINT UNSIGNED,
	supLvl SMALLINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	INDEX (grp),
	INDEX (own),
	INDEX (supRefFmncMTooltype),
	INDEX (supLvl),
	INDEX (sref),
	INDEX (Title)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMUser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refRUsergroup BIGINT UNSIGNED,
	refFmncMUsergroup BIGINT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixFmncVLocale INT UNSIGNED,
	ixFmncVUserlevel INT UNSIGNED,
	Password VARCHAR(30),
	INDEX (grp),
	INDEX (own),
	INDEX (refFmncMUsergroup),
	INDEX (refFmncMPerson),
	INDEX (sref),
	INDEX (ixVState)
) ENGINE = MYISAM;

CREATE TABLE TblFmncMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (sref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMArticleMOrg(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMArticle BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	Itemno VARCHAR(30),
	INDEX (refFmncMArticle),
	INDEX (refFmncMOrg)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMFabMRun(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFab BIGINT UNSIGNED,
	refFmncMRun BIGINT UNSIGNED,
	INDEX (refFmncMFab),
	INDEX (refFmncMRun)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMFabprojectMFabuser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFabproject BIGINT UNSIGNED,
	refFmncMFabuser BIGINT UNSIGNED,
	INDEX (refFmncMFabproject),
	INDEX (refFmncMFabuser)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMFabuserMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFabuser BIGINT UNSIGNED,
	refFmncMTool BIGINT UNSIGNED,
	trnRefFmncMPerson BIGINT UNSIGNED,
	srefKLvl VARCHAR(50),
	INDEX (refFmncMFabuser),
	INDEX (refFmncMTool)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMFileMSample(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFile BIGINT UNSIGNED,
	refFmncMSample BIGINT UNSIGNED,
	INDEX (refFmncMFile),
	INDEX (refFmncMSample)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMFileMStep(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMFile BIGINT UNSIGNED,
	refFmncMStep BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (refFmncMFile),
	INDEX (refFmncMStep)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMOrgMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (x1Startd),
	INDEX (x1Stopd),
	INDEX (refFmncMOrg),
	INDEX (refFmncMPerson),
	INDEX (srefKFunction)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMPersonMRun(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	refFmncMRun BIGINT UNSIGNED,
	INDEX (refFmncMPerson),
	INDEX (refFmncMRun)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMRunMSample(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMRun BIGINT UNSIGNED,
	refFmncMSample BIGINT UNSIGNED,
	INDEX (refFmncMRun),
	INDEX (refFmncMSample)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMSampleMStep(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMSample BIGINT UNSIGNED,
	refFmncMStep BIGINT UNSIGNED,
	INDEX (refFmncMSample),
	INDEX (refFmncMStep)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMToolMTooltype(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMTool BIGINT UNSIGNED,
	refFmncMTooltype BIGINT UNSIGNED,
	srefsFmncKToolchar VARCHAR(255),
	defSrefsFmncKSteppar VARCHAR(255),
	optSrefsFmncKSteppar VARCHAR(255),
	INDEX (refFmncMTool),
	INDEX (refFmncMTooltype)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMUsergroupUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUsergroup BIGINT UNSIGNED,
	unvIxFmncVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixFmncVAccess INT UNSIGNED,
	INDEX (refFmncMUsergroup),
	INDEX (unvIxFmncVMaintable),
	INDEX (unvUref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncRMUserMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMUser BIGINT UNSIGNED,
	refFmncMUsergroup BIGINT UNSIGNED,
	ixFmncVUserlevel INT UNSIGNED,
	INDEX (refFmncMUser),
	INDEX (refFmncMUsergroup)
) ENGINE = MYISAM;

CREATE TABLE TblFmncSvcRMOrgMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMTool BIGINT UNSIGNED,
	INDEX (refFmncMOrg),
	INDEX (refFmncMTool)
) ENGINE = MYISAM;

CREATE TABLE TblFmncSvcTMPersonMTool(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMPerson BIGINT UNSIGNED,
	refR BIGINT UNSIGNED,
	INDEX (refFmncMPerson),
	INDEX (refR)
) ENGINE = MYISAM;

CREATE TABLE TblFmncTMFileMSample(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refFmncMSample BIGINT UNSIGNED,
	refR BIGINT UNSIGNED,
	INDEX (refFmncMSample),
	INDEX (refR)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQAct1NStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQActList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	runRefFmncMRun BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQAdrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Address1 VARCHAR(100),
	City VARCHAR(50),
	hkIxVTbl INT UNSIGNED,
	hkUref BIGINT UNSIGNED,
	srefKAdrtype VARCHAR(50),
	Zipcode VARCHAR(10),
	srefKCountry VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQArt1NSample(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQArt1NStockitem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQArtList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(100),
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMTool BIGINT UNSIGNED,
	srefKType VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQArtMNOrg(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	Itemno VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQArtRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQBilAPos(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	bilNum INT UNSIGNED,
	x1RefFmncMFabuser BIGINT UNSIGNED,
	x2RefFmncMTool BIGINT UNSIGNED,
	Quantity DOUBLE,
	Article VARCHAR(255),
	Unitprice DOUBLE,
	Price DOUBLE,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQBilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Date INT UNSIGNED,
	refFmncMFabproject BIGINT UNSIGNED,
	refFmncMFile BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Prdstart INT UNSIGNED,
	Prdstop INT UNSIGNED,
	Amount DOUBLE,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFab1NFabproject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFab1NFabuser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFabFab1NTool(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFabList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFabMNRun(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Filename VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFilMNSample(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFilMNStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFpj1NBill(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFpjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(100),
	refFmncMFab BIGINT UNSIGNED,
	bioRefFmncMOrg BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFpjMNFabuser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFusList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refFmncMFab BIGINT UNSIGNED,
	refFmncMFabproject BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFusMNFabproject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQFusMNTool(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	trnRefFmncMPerson BIGINT UNSIGNED,
	srefKLvl VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrg1NArticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrg1NStockitem(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgBio1NFabproject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgHk1NAddress(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgKStocklcn(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	ixWDerivate INT UNSIGNED,
	refFmncMAddress BIGINT UNSIGNED,
	supRefFmncMOrg BIGINT UNSIGNED,
	Tel VARCHAR(255),
	Eml VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgMNArticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	Itemno VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgMnf1NTool(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgPco1NPurchorder(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgSpl1NPurchorder(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgSup1NOrg(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQOrgSvcMNTool(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPcoAPos(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	pcoNum INT UNSIGNED,
	Quantity DOUBLE,
	Itemno VARCHAR(30),
	refFmncMArticle BIGINT UNSIGNED,
	Unitprice DOUBLE,
	Price DOUBLE,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPcoList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Date INT UNSIGNED,
	pcoRefFmncMOrg BIGINT UNSIGNED,
	splRefFmncMOrg BIGINT UNSIGNED,
	refFmncMFile BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	Amount DOUBLE,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPreselect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrj1NRun(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrsADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrsHk1NAddress(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	Lastname VARCHAR(50),
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMAddress BIGINT UNSIGNED,
	ixVSex INT UNSIGNED,
	Tel VARCHAR(255),
	Eml VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrsMNOrg(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x1Stopd INT UNSIGNED,
	srefKFunction VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQPrsMNRun(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	refFmncMProject BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunMNFab(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunMNPerson(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunMNSample(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQRunRun1NActivity(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	runNum INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSelect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ix INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (ix)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSepAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1OsrefFmncKSteppar VARCHAR(50),
	x2IxVTbl INT UNSIGNED,
	x2Uref BIGINT UNSIGNED,
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSepList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	refFmncMActivity BIGINT UNSIGNED,
	rlvIxVTbl INT UNSIGNED,
	rlvUref BIGINT UNSIGNED,
	tplRefFmncMStep BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSepMNFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSepMNSample(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSepRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSkiList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refFmncMOrg BIGINT UNSIGNED,
	refFmncMArticle BIGINT UNSIGNED,
	Quantity VARCHAR(10),
	osrefFmncKStocklcn VARCHAR(50),
	Expdate INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	osrefKVal VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	supRefFmncMSample BIGINT UNSIGNED,
	refFmncMArticle BIGINT UNSIGNED,
	Material VARCHAR(100),
	ixVState INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpMNFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpMNRun(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpMNStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQSmpSup1NSample(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1OsrefFmncKSteppar VARCHAR(50),
	x2IxVTbl INT UNSIGNED,
	x2Uref BIGINT UNSIGNED,
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpKSteppar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	refFmncMActivity BIGINT UNSIGNED,
	rlvIxVTbl INT UNSIGNED,
	rlvUref BIGINT UNSIGNED,
	tplRefFmncMStep BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpMNFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixVDir INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQStpTpl1NStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTol1NArticle(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolAAvl(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	x2IxVWkday INT UNSIGNED,
	x3Startt INT UNSIGNED,
	x3Stopt INT UNSIGNED,
	srefKAvltype VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolAChar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1OsrefFmncKToolchar VARCHAR(50),
	Val VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolARes(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefFmncMFabuser BIGINT UNSIGNED,
	startd INT UNSIGNED,
	startt INT UNSIGNED,
	stopt INT UNSIGNED,
	srefKRestype VARCHAR(50),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolAUtil(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1RefFmncMFabproject BIGINT UNSIGNED,
	x2RefFmncMFabuser BIGINT UNSIGNED,
	startd INT UNSIGNED,
	startt INT UNSIGNED,
	stopt INT UNSIGNED,
	Unitprice DOUBLE,
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolKSteppar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolKToolchar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(50),
	fabRefFmncMFab BIGINT UNSIGNED,
	mnfRefFmncMOrg BIGINT UNSIGNED,
	Unitprice DOUBLE,
	Training VARCHAR(100),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolMNFabuser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	trnRefFmncMPerson BIGINT UNSIGNED,
	srefKLvl VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolMNTooltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefsFmncKToolchar VARCHAR(255),
	defSrefsFmncKSteppar VARCHAR(255),
	optSrefsFmncKSteppar VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolRlv1NStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTolSvcMNOrg(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtyKSteppar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtyKToolchar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	klsNum INT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(255),
	Implied VARCHAR(255),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(255),
	Comment TEXT,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtyList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(50),
	supRefFmncMTooltype BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtyMNTool(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	srefsFmncKToolchar VARCHAR(255),
	defSrefsFmncKSteppar VARCHAR(255),
	optSrefsFmncKSteppar VARCHAR(255),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtyRlv1NStep(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQTtySup1NTooltype(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsgAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxFmncVCard INT UNSIGNED,
	ixFmncWUiaccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsgMNUser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixFmncVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsr1NSession(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsrAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxFmncVCard INT UNSIGNED,
	ixFmncWUiaccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refFmncMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refFmncMUsergroup BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixFmncVLocale INT UNSIGNED,
	ixFmncVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

CREATE TABLE TblFmncQUsrMNUsergroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixFmncVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = MYISAM;

